### ISSUE TITLE
selector-class-pattern to exclude (or specify different pattern for) LESS mixins?

### ISSUE THREAD

**Issue by diagramatics** [stylelint/stylelint#1077]
Apologies if I raised an issue incorrectly.

> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This is a tough one, I'm not sure whether to file this request to webschik/postcss-less or to here, but I think this is only able to be properly handled if Stylelint understands the exclusion?

Basically, you have the `selector-class-pattern` linting on the mixin usage too. I'm hoping for an option to ignore these or to specify a different pattern for them only. I haven't checked how the SCSS parser does this, although I would guess that their mixins are essentially at-rules so they don't get parsed?

> Which rule, if any, is this issue related to?

`selector-class-pattern`

> What CSS is needed to reproduce this issue?

```less
.mixin-blue() {
  color: blue;
}

.a-selector {
  .mixin-blue();
}
```

The naming convention I'm using is more complicated than this. Pascal case SUITCSS for normal classes, snake-case for mixins, and it's a legacy naming convention that I can't change unfortunately plus snake-case are banned for normal classes so there needs to be a clear separation between them.

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "selector-class-pattern": "a-[a-z]+
  }
}
```

> Which version of stylelint are you using?

5.4.0 with `postcss-less` running on 0.9.0.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`gulp-postcss` with `stylelint`, `postcss-less` and `postcss-reporter`, but I believe this is irrelevant.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Related to webschik/postcss-less

> What did you expect to happen?

... a new option to exclude LESS mixins or specify patterns for them?

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
Expected class selector ".mixin-blue" to match specified pattern (selector-class-pattern) [stylelint]
```

**Comment by jeddy3** [comment]
> Apologies if I raised an issue incorrectly.

It looks great :)

> I think this is only able to be properly handled if Stylelint understands the exclusion?

We can add an exclusion to stylelint. The rule already excludes selectors that contain scss interpolation (and custom property sets).

We need some way of determining if a *class* selector is actually a *mixin* though. Similar to [how we detect](https://github.com/stylelint/stylelint/blob/master/src/utils/cssDeclarationIsMap.js) is a declaration is actually a SCSS map.

Can anyone see any issue with just testing if the last character in the class selector is a closing bracket? `postcss-selector-parser` will account for the likes of `.class:not(h1)` but parsing the brackets here as part of the pseudo.

> or to specify a different pattern for them only.

Once this rule ignores Less mixins, feel free to [create a plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) which solely targets them e.g. `stylelint-dot-mixin-pattern`. All the rules in stylelint focus on just standard-css syntax, but we created a plugin system for non-standard syntax.

---

Does this sound about right to everyone? If so, I'll label this up as "help wanted".

**Comment by diagramatics** [comment]
AFAIK the other way to call a selector as a mixin in LESS can be like `.a-mixin;`. So I suppose anything that ends with a semicolon and starts with a dot?

**Comment by Nirazul** [comment]
Less mixins can also be written as IDs, so a mixin call can be:
```
.a-mixin;
.another-mixin();
#such-mixin();
#that-too;
```

They can also live within an ID as group:
```
#outer > .inner;
#outer > .inner();
#outer .inner;
#outer .inner();
#outer.inner;
#outer.inner();
```

[see less documentation](http://lesscss.org/features/#mixins-feature)

**Comment by davidtheclark** [comment]
Could you check if you have a selector that for a rule that actually has no block (different from an existing but empty block)? Like we do for blockless at-rules?

**Comment by diagramatics** [comment]
I guess not since you can have mixins as functions. http://lesscss.org/features/#mixins-as-functions-feature

**Comment by jeddy3** [comment]
I have to admit, I'm a bit stumped. I'm not sure how we can distinguish between standard classes/ids and Less mixins at the stylelint end. 

Can something be done in `postcss-less` so that mixins aren't categorised as class/id selectors?

**Comment by diagramatics** [comment]
I don't think so because LESS is loosely typed and that a "mixin usage" on a LESS selector can make a normal CSS selector behave as that and a mixin both at once. The only way to understand this is to specifically specify a mixin-only declaration (a selector always with a parantheses) to be mixins.

So we make `less-non-outputting-mixin-name-pattern`? This sounds like such an edge case though, and if this doesn't sound like something we can add into the default rules I might just make my own.

**Comment by jeddy3** [comment]
@diagramatics Thanks for the clear explanation.

> So we make `less-non-outputting-mixin-name-pattern`?

Yep, as a plugin. Rules are for standard css syntax and plugins are for "methodologies, toolsets, non-standard CSS features, or very specific use cases". However, we always try to make the rules as useful as possible across all the different syntaxes by having them ignore (rather than trip-up on) non-standard syntax. As you pointed out, as "outputting" Less mixins can be both a normal CSS selector and a minix at once, then there's not much we can do about that. But we can make`selector-class-pattern` detect and ignore both "non-outputting" Less mixin definitions and "called" Less mixins.

I've created a [PR](https://github.com/stylelint/stylelint/pull/1114) to do this.

`less-non-outputting-mixin-name-pattern` is a great name for your plugin btw :) Be sure to prefix your npm module name with `stylelint` though i.e. `stylelint-less-non-outputting-mixin-name-pattern`.

Does this sounds like an acceptable solution to everyone?

**Comment by diagramatics** [comment]
I'm not sure if we should ignore all LESS mixins without giving people the option to turn it off. Mine is such an edge case from the codebase I'm working on and some people might not have the same issues with it – maybe they have a similar naming convention to it?

**Comment by jeddy3** [comment]
I think ignoring:

```less
.mixin() {}
```

and:

```less
a {
  .mixin();
}
```

by default in `selector-class-pattern` *is* consistent with our approach to dealing with non-standard syntax in other rules. I think it was a mistake that the `selector-class-pattern` checked `.mixin() {}` and `a { .mixin; }` as neither of those are *standard class selectors* :)

I think those should be checked by a plugin dedicated to the task. If a person uses the same naming scheme across their classes and non-outputting Less mixins, then they'll need to turn on both the class rule and the plugin. Much in the same way as when a person uses the same naming scheme for *custom properties* and *custom media*... there's two specific rules for those: [`custom-property-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/custom-property-pattern/README.md) and [`custom-media-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules//README.md) respectively.

I think consistency of behaviour is important across the rule because we have so many and consistency makes them easier to work with. As such, I'm in favour of `selector-class-pattern` ignoring `.mixin() {}` and `a { .mixin; }` by default.

**Comment by davidtheclark** [comment]
I agree, @jeddy3 .

**Comment by diagramatics** [comment]
In that case, I have no concerns then. Thanks for the clarification and the help!

**Comment by jeddy3** [comment]
This was done in the [utilities restructuring](https://github.com/stylelint/stylelint/pull/1128).

**Comment by anselmbradford** [comment]
I have this pattern for matching BEM naming:

```
'selector-class-pattern': [
    '^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$',
    { resolveNestedSelectors: true },
],
```

And it is flagging my Less mixins. For example, `Expected ".heading-5( @fs: @size-v )" to match pattern "^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$"`

Did ignoring Less mixins get reverted at some point?
