### ISSUE TITLE
Option to ignore alphabetical ordering or vendor prefixes

### ISSUE THREAD

**Issue by MrFirthy** [stylelint/stylelint#1087]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request/Question

> Which rule, if any, is this issue related to?

declaration-block-properties-order

Is it possible to apply a flag to prevent Stylelint from enforcing an alphabetical order on vendor prefixes? I have a declaration order that I'm pleased with in my config, but my vendor prefixes are automatically generated through Autoprefixer within a gulp task on my SASS files. However I want to lint the final CSS file on the fly using Circle CI, so the CLI is perfect for that. 

The issue is that by the time the file is being linted, Autoprefixer has added vendor prefixes in a non-alphabetical order, and I receive warnings and the automated tests fail. I cannot see a way to dictate the order that autoprefixer provides vendor prefixes, and these are the only warnings being thrown on my CSS at this point. 

Your docs clearly state `Prefixed properties must always be alphabetically ordered and must always precede the unprefixed version.` but is there a way around this within the config?

> Which version of stylelint are you using?

Latest

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint styles.css`"

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

No warning to be flagged

> What actually happened (e.g. what warnings or errors you are getting)?

You get warning such as:

```
Expected property "-moz-appearance" to come before property "-webkit-appearance"
```

**Comment by ntwb** [comment]
Should you lint your CSS, then run Autoprefixer so those vendor prefixes are added after the fact?

**Comment by jeddy3** [comment]
> However I want to lint the *final CSS file* on the fly using Circle CI, so the CLI is perfect for that.

@MrFirthy It'd be very interesting to hear a little more about your use case. 

As @ntwb mention, the recommended approach is to lint your source files *before* any transformations. But I *can* think of a couple of use cases where you might want to lint *your transformed CSS* with a *specific* configuration. For example:

```json
{
   "rules": {
     "declaration-block-no-shorthand-property-overrides": true,
     "function-url-data-uris": "always"
   }
}
```

Here we're checking two things:

- that the transformations haven't created a declaration order where a shorthand property overwrites a longhand one. 
- that a transformation tool that inlines assets has correctly converted all the function URLs to data URIs.

Checking the *entire declaration order* of the *transformed CSS* doesn't seem valuable to me, and so that's why it'd be great to find out a little more about your use case. So that we can find the right solution to this issue.

**Comment by MrFirthy** [comment]
@jeddy3 @ntwb Thank you both for the replies. My particular use case was as follows:

I wanted to use Stylelint to lint my CSS both manually, and as part of our continuous integration tests when branches are pushed/deployed. I initially tried to use the CLI and run it on the compiled CSS file, but as my original post said, Autoprefixer's way of providing vendor prefixes didn't match up with Stylelint's rule to always alphabetise them. Therefore I would always be getting Stylelint errors even if the original source files were lint free.

Secondly, I tried using gulp-stylelint so I could lint the original SASS files before Autoprefixer did anything. This was successful locally, however it threw up an issue with the continuous integration tests. This was because when an error was found in the SASS files, it would display it in the console but wouldn't actually exit with an error code. I'm not particularly sure why this is, so if either of you know it'd be great to understand, but the result is that although Stylelint would successfully lint and discover errors, my CI tests would always pass because no exit code was thrown when an error was found.

I finally settled on breaking up my gulp CSS task into two parts. The first would handle the compiling of SASS into CSS renaming it and moving it to the `dist/` folder, and the second part would first run Stylelint on that CSS, and would then continue to Autoprefixer if it found no linting errors. 

The result is that it still lints successfully, doesn't throw up errors relating to vendor prefixes, and fails with an error code greater than 0 when it finds a linting error (thereby satisfying the CI tests).

The solution feels a little hacky so if either of you have a suggestion about improving it then I'd be grateful, but all in all this was an issue with my setup rather than Stylelint, and thank you to @ntwb for suggesting his approach.

**Comment by ntwb** [comment]
Interestingly, Autoprefixer does indeed use non-alphabetical order as it needs to order the properties so that they can be correctly overridden, e.g:

```css
a {
    display: flex;
}
```

Becomes:
```css
a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-box;
    display: -ms-flexbox;
    display: flex;
}
```

Should there be an exception option for vendor prefixes (or based on Autoprefixer settings) for the `declaration-block-properties-order` rule?

By breaking up your Gulp task into the two parts that works around your original issue, we'd need to see what your original Gulp task was here to help track down exactly what was causing your issues.

**Comment by jeddy3** [comment]
@MrFirthy Thanks for the write up. I've a couple of questions and suggestions.

> I wanted to use Stylelint to lint my CSS both manually

What do you mean by "manually"? Do you mean locally?

> I initially tried to use the CLI and run it on the compiled CSS file

I'm still not quite sure *why* you're doing this? What specifically are you checking for? e.g. to check your CSS processor tooling worked?

> This was because when an error was found in the SASS files, it would display it in the console but wouldn't actually exit with an error code. 

Did you set the [`failAfterError` option](https://github.com/olegskl/gulp-stylelint#failaftererror)? If that didn't work then you might want to raise an issue on the `gulp-stylelint` repo.

> I finally settled on breaking up my gulp CSS task into two parts. The first would handle the compiling of SASS into CSS renaming it and moving it to the dist/ folder, and the second part would first run Stylelint on that CSS, and would then continue to Autoprefixer if it found no linting errors. 

Having a separate tasks for linting *your source code* and compiling *your source code* is the recommended way to do things.

Like I said above, I'd be great to know exactly why you're linting your *compiled CSS*. If, for example, it because you want to check that your tooling worked, then that's cool. You can then have three tasks:

1. linting *your source code*.
2. compiling *your source code*.
3. linting *your compiled css*

You'll probably want to use different configuration objects for the two linting tasks as I suspect they have different goals e.g. 

- linting *your source code* (locally and via your CI) to ensure only consistent code in stored in your repo
- linting *your compiled css* (locally and via your CI) to check, for example, your tooling worked.

> @ntwb said: Should there be an exception option for vendor prefixes (or based on Autoprefixer settings) for the declaration-block-properties-order rule?

Yep, that sounds like a sensible addition for your scenario @ntwb, where you're committing vendor prefixes to your source files.

**Comment by MrFirthy** [comment]
@jeddy3 

> What do you mean by "manually"? Do you mean locally?  

Yes. I would run it as an npm command locally to check if it was passing before pushing the branch 

As for why I was originally using the CLI, it was for the same purpose as using `gulp-stylelint`; to check if the CSS passed linting. I originally tried to use the CLI as I thought it would work more neatly with automated CI tests, but the gulp plugin works just as well in that department.

> Did you set the failAfterError option? If that didn't work then you might want to raise an issue on the gulp-stylelint repo.  

Yes I did try that and it didn't work. I will raise that as an issue 👍 

> Like I said above, I'd be great to know exactly why you're linting your compiled CSS  

This comes back to the topic you raised above. I resorted to linting the compiled CSS as when I was linting on the source files (SASS), stylelint wouldn't exit with an error code, and therefore it was no good for me re: my CI tests. I think if I can get it error'ing properly on the `.scss` files through `gulp-stylelint`, I would no longer need to run it on compiled CSS.

Let me know if there's anything else you're unsure about. @ntwb idea of an exception option would have helped in my scenario.

**Comment by MrFirthy** [comment]
https://github.com/olegskl/gulp-stylelint/issues/24

Issue logged with `gulp-stylelint`

**Comment by jeddy3** [comment]
@MrFirthy Thanks for clarifying things.

> I think if I can get it error'ing properly on the .scss files through gulp-stylelint, I would no longer need to run it on compiled CSS

Fingers crossed you getting it working as linting your source code *is a lot more useful* than linting your  compiled CSS. 

> @ntwb idea of an exception option would have helped in my scenario.

Agreed. It'll likely help @ntwb manage flexbox prefixes in the Wordpress codebase too and so it's a feature worth adding. I'll create a separate issue for that though and close this one.
