### ISSUE TITLE
404 errors in documentation

### ISSUE THREAD

**Issue by pawelgrzybek** [stylelint/stylelint#1113]
Some links in documentation point to 404 error. Mainly links to all new rules announced in 6.1.

http://stylelint.io/user-guide/rules/selector-attribute-square-brackets-space-inside/
http://stylelint.io/user-guide/rules/selector-parentheses-space-inside/
http://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values/

**Comment by jeddy3** [comment]
@pawelgrzybek Thanks for reporting this.

Fixed in https://github.com/stylelint/stylelint/commit/5ca4e0374cc33a5a3841ebae3ccecec1057154dc and https://github.com/stylelint/stylelint.io/commit/9c4b97d7fd7623b32fce762f9b05ce70042fee48

And released as `6.1.1`. 

These are the correct links:

http://stylelint.io/user-guide/rules/selector-attribute-brackets-space-inside/
http://stylelint.io/user-guide/rules/selector-pseudo-class-parentheses-space-inside/
http://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values/
