### ISSUE TITLE
config: include files pattern

### ISSUE THREAD

**Issue by Guria** [stylelint/stylelint#1227]
Need a way to define include files pattern in `.stylelintrc` config file which will be respected both with `stylelint` cli and editor plugins. I have my styles in `*.pcss` files. Currently it's only possible to lint with `stylelint **/*.pcss` command. Would be great to have a way to define it in config.

**Comment by davidtheclark** [comment]
> Would be great to have a way to define it in config.

Why would that be great?

**Comment by evilebottnawi** [comment]
@Guria close inactive, if you found reason why would that be great, create new issue.

**Comment by DesignByOnyx** [comment]
It would be great because, like other linters, you could keep all of your config... in a config file. This enables the following:

- with an `include` option you could:
    - provide a single place to define files which should be linted
    - define multiple glob patterns within a single config
    - dynamically build the includes (with .stylelintrc.js only)
- the `include` option gives way to an `exclude/ignore` option:
    - includes and excludes defined in same place
    - multiple excludes can be defined
    - eliminates the need for a separate `.stylelintignore` file

**Comment by ntwb** [comment]
@DesignByOnyx stylelint has changed significantly since this issue was created, could you please create a new issue outlining your request please?

Please also follow the template and give us examples of the configuration you currently use and the configuration you would like to use please.

stylelint supports "nested" configurations which should cover your monorepo requirements so including that information also would be beneficial to help us understand your use case please
