### ISSUE TITLE
Semver and rule enchancement

### ISSUE THREAD

**Issue by dzhiriki** [stylelint/stylelint#1236]
6.3.3 contains #1205 which contains declaration-block-no-ignored-properties improvements, but it's a breaking change, because in 6.3.2 I can have no errors, but i will get it in 6.3.3. And it can break CI builds.
Same problem will be with #1234 and other PRs with improvements of *exists* rules.

Why it's a patch? Should not it be major changes and produce new major version?

**Comment by davidtheclark** [comment]
We are considering them bug fixes because they are making the rule behave as originally intended. Otherwise we would need to do a major release whenever we fixed *any* bug that meant a warning was not being triggered when it should have been.

For any bug on any package there's the same risk, that a user could come to rely on a bug and then when the bug is fixed it's a "breaking change" for that user.

**Comment by dzhiriki** [comment]
I am disagree.

Rule works same as it was described in Readme. The rule does not contain any errors that were fixed. #1205 contains *new* functional.

If new functional *can* break *any* build, then it should produce new major version.

If you originally intended that rule should work as in 6.3.3 than it all should be described in readme and it should not be merged before it was fully created and tested. Or you can add new config for new features – then it was not break anything.

Anyway, *same* major version with *same* config *should* produce identical result.

I started use stylelint from version 6.2.2 and *each* new version break my builds: 6.3.0 contains two bugs, 6.3.3 contains some breaking changes. It is really-really bad.

**Comment by davidtheclark** [comment]
> If new functional can break any build, then it should produce new major version.

I understand what you're saying, but I'm also not sure that's a reasonable approach for this linter, for the reasons described above. With so many rules in play, I think if we did a major release whenever any rule gets a fix that might break somebody's build, then semver would lose meaning in another way.

If you or anyone else wants to research how other linters like ESLint have handled this problem, I'm curious and would be open to concrete suggestions. I honestly don't know what the best solution is. It's quite possible that what we're doing isn't the best, but I don't think that super frequent major releases is the best, either.

**Comment by davidtheclark** [comment]
@dzhiriki Have you encountered other semver violations outside of this particular rule, or has it just been this rule?

**Comment by dzhiriki** [comment]
I started using stylelint only from 6.2.2, so i can only say about violations inside 6.3.*.

**Comment by davidtheclark** [comment]
Yeah, and for what you've used has the violator only been this one particular rule?

**Comment by davidtheclark** [comment]
I'm asking because I agree with you now that the way this particular rule was released was wrong. I do think we can try to stick to this standard: You build should only break if we've done a major release, you've changed your config, or you were relying on some undocumented behavior.

I think that's been our implicit guide so far and it may be that we just blew it with that one rule (and maybe a bug here and there, which is natural). But if there are more ways we've violated it, I'd like to know.

**Comment by jeddy3** [comment]
> I think that's been our implicit guide so far and it may be that we just blew it with that one rule

Agreed. We're normally very good at correctly categorising changelog items (e.g. fixes vs breaking changes), but, as you said, we got this one wrong. 

> But if there are more ways we've violated it, I'd like to know

I can't think of any, so I'm going to close this issue for now. @dzhiriki Feel free to reopen if any other instances spring to mind.
