### ISSUE TITLE
Clarify "getting started" in the docs

### ISSUE THREAD

**Issue by mikeerickson** [stylelint/stylelint#1271]
I started using Stylelint yesterday.  All in all, it was a pretty painless process.  The only thing that got me hung up was create the necessary `.stylelintrc` (or `.stylelint.config.js`) file.

I am proposing to add a new CLI command:

$ stylelint init

This would create a default `.stylelintrc` file containing sensible defaults.  As I have covered in other posts, the initial usage of Stylelint could be  a simple 3 step process

```
$ npm i -D stylelint
$ npm init (this will create default .stylelint file, ala npm init, karma init, etc.)
$ stylelint ./app/css/*.css
```

First pass of CLI command would just create a simple `.stylelintrc` file with sensible defaults. it could surely be extended, perhaps prompting user to pick any extended modules (ie `stylelint-config-standard`)

If end user decides to use the `stylelint-config-standard` it could be installed for user during configuration process.

Just a thought :-)
Mike Erickson

**Comment by jeddy3** [comment]
> This would create a default .stylelintrc file containing sensible defaults.

`stylelint-config-standard` is where we maintain a list of rules with sensible defaults, that we recommend extending.

So, I guess we could have:

```
$ npm i -D stylelint stylelint-config-standard
$ stylelint init
$ stylelint ./app/css/*.css
```

Where `stylelint init` creates a `.stylelintrc` file in the cwd with:

```json
{
  "extends": "stylelint-config-standard",
  "rules": {}
}
```

**Comment by mikeerickson** [comment]
@jeddy3 at a minimum, yes.

There seems to be some "confusion" as to where config files are stored

```
.stylintrc or .stylelint.config.js

```
I know it seems trivial, but thinking the "init" command could also be extended to create a config file which contains sensible defaults as opposed to requiring the `stylelint-config-standard`

Thanks for considering...

Now that I have undestood what it takes to get stylelint configured for any project, it is less important, but would surely be helpful for those who are getting started.   

I noticed may issue reports which request assistance for the very same thing I originally asked, having this method would have avoided all of this :-)

**Comment by davidtheclark** [comment]
I think if `stylelint init` just creates a JSON object that extends `stylelint-config-standard`, it is not worth implementing. I am not interested in building features to shorten an already trivial task.

I also am not a big fan of the idea that it just copy-pastes that config from `stylelint-config-standard`, because that is also a trivial task. Maybe we should ensure there is a prominent link to it in the docs.

I tried `eslint --init` and I guess I'm not seeing it adding enough value that I'd want to code it — except the part about inspecting your JS and automatically building rules (depending of course on how thorough that is, which I don't know).

What I'm saying, then, is that I'm only interested in this feature if I don't have to build it, and if it does not add any significant maintenance. So although I am open to a PR, I'd also be surprised if one comes along — so I wonder if we should close this.

**Comment by mikeerickson** [comment]
I think your mention of improving documentation would more than suffice.  I do agree, it is indeed trivial to get started (just a bit of clarification in docs)

**Comment by jeddy3** [comment]
> There seems to be some "confusion" as to where config files are stored

User's have different preferences to where they like to store their configs, which we try to accommodate. `cosmiconfig`, which stylelint uses, [supports](https://github.com/davidtheclark/cosmiconfig#cosmiconfig) a few of these.

> I know it seems trivial, but thinking the "init" command could also be extended to create a config file which contains sensible defaults as opposed to requiring the stylelint-config-standard

I'm not sure why you'd want to do this. [`extends`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) is a powerful feature. It means a user can update to the latest rules (that aren't divisive) using a simple `npm i -D stylelint-config-standard@latest`, rather than having go read through the notes of a new release and *then manually add the new rules to their config*.

> I think your mention of improving documentation would more than suffice

Sounds good to me. Can you please send us a PR with improvements that would've helped you get started. I think we're perhaps too close to the project to see how the [configuration guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#configuration) could be made more clear?

**Comment by davidtheclark** [comment]
Closing because I believe the [Quick Start](http://stylelint.io/#quick-start) section of the README already addresses this: it provides all the suggestions and links needed.

**Comment by wjandrea** [comment]
FWIW, I was also confused about the config, but I'm using the Atom plugin [linter-stylelint](https://atom.io/packages/linter-stylelint) and I just hadn't noticed it has a setting to use `stylelint-config-standard`.

> **Use standard**
> Use the stylelint-config-standard lint configuration when no other configuration is found. Disables the "Disable when no config" option.
