### ISSUE TITLE
Check that each selector in a list, rather than the whole list, is standard

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1330]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

In rules:
- [ ] `selector-no-attribute`
- [ ] `selector-no-combinator`
- [ ] `selector-no-id`
- [ ] `selector-no-qualifying-type`
- [ ] `selector-no-type`
- [ ] `selector-no-universal`
- [ ] `selector-no-vendor-prefix`
- [ ] `selector-type-case`
- [ ] `selector-type-no-unknown`

We use `isStandardSelector` util. But

``` css
#some-#{$variable} { } // It is ID selector and can checks rule.
.class#{$variable} { }
a:#{$variable} { }
:-webkit-full-screen #{$variable} { }
```

What do you think about? I think we should check `isStandardSelector` inside `selectorAST.walk*`.
/cc @davidtheclark @jeddy3

**Comment by davidtheclark** [comment]
If you can provide example code showing what behavior would change, that would help me understand the goal.

**Comment by evilebottnawi** [comment]
@davidtheclark 
```scss
#id,
.class-#{$variable} { }
```
I set `selector-no-id` to `true`, but no we ignore all selector. `isStandardSelector` should not check all selector, i think each selector separetly

**Comment by evilebottnawi** [comment]
@jeddy3 ping

**Comment by jeddy3** [comment]
This will have to wait a while. I've probably got enough time to sort https://github.com/stylelint/stylelint/pull/1333 before I go away, but not much else I'm afraid.

**Comment by davidtheclark** [comment]
@evilebottnawi I think I agree. To clarify: You're saying that right now with `#id, .class-#{$variable} { }` the entire selector is ignored, so `#id` is not checked. So we should modify the `isStandardSelector` to check each compound selector individually: that way, `#id` would be checked but `.class-#{$variable}` would be ignored. Is that right?

If my summary is correct, then I do agree. It's not a trivial change, though, because we'd have to modify rules, probably. It would also be a breaking change, right? I'd be happy to mark it down for v7.

**Comment by evilebottnawi** [comment]
@davidtheclark yep, no need change `isStandardSelector`, we can move `isStandardSelector` inside `walk*` and all tests ok, i think v7 milestone, breaking change :cry:

**Comment by evilebottnawi** [comment]
@davidtheclark ping me then need fire PR, I'll take care of this issue

**Comment by davidtheclark** [comment]
@evilebottnawi Go for it!

**Comment by jeddy3** [comment]
@evilebottnawi Is this something I can help with, or are you working on it at the moment?

**Comment by evilebottnawi** [comment]
@jeddy3 be cool if help, few time in this week :disappointed:

**Comment by jeddy3** [comment]
I've looked into this some more. We use `postcss-selector-parser` to parser the whole *selector list* (e.g. `a, b {}`) and the *complex selectors* within them (e.g. `a b, c  {}`). We do this because we rely on `postcss-selector-parser`'s sourceIndex feature to accurately and easily locate each of the offending *simple selector* within the *selector list* or *complex selector*. 

`postcss-selector-parser` *can not parse* non-standard CSS syntax, which is why we check that the whole selector uses standard syntax before passing it on to parser.

So, I don't think there's much we could do with *complex selectors* i.e. we can't catch the *id selector* in `#id .class-#{$var}`. 

For *selector lists*, we could try to [safely split](https://github.com/postcss/postcss/blob/master/lib/list.es6#L12-L53) them and check that each item uses standard syntax i.e. we could catch the *id selector* in `#id, .class-#{var}`. *However*, this would need a means of calculating the index of each *selector* within a *selector list*.

This seems like a fair bit of effort for supporting the *selector list* non-standard syntax edge-case, especially as I can't see a way to tackle the *complex selector* one.

Perhaps we should push this to `future-major`? Or is this something you'd like to tackle soon @evilebottnawi?

**Comment by evilebottnawi** [comment]
@jeddy3 agree, need more investigation, add `future-major`

**Comment by jeddy3** [comment]
I'm going to close this. It's more work, and adds complexity, for a slightly improved handling of non-standard syntax, which isn't a priority.

**Comment by evilebottnawi** [comment]
@jeddy3 i think it is easy as we think, we don't check all selector on `isStandard`, then `walk` on selectors and check each on `isStandard`.
