### ISSUE TITLE
ES6 style: arrow functions or not?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#142]
I know I've been pretty inconsistent in whether I use arrow functions or regular old anonymous functions. My general tendency is to use regular functions unless I want `this` to be affected or I can be especially concise with an arrow. Do we *want* to establish some consistency? Not that important, of course, but was wondering if you had opinions.

**Comment by MoOx** [comment]
Since the current codebase is more following a functional style, the usage of this doesn't make a lot of sense, so "fat arrow function"  should be the most used :)
The good part of this (not really relevant for us) is for example when you are in a react component or a similar class, you don't need to rebind callback to get the proper "this" :)

**Comment by jeddy3** [comment]
> Do we want to establish some consistency?

I'm always keen to establish consistency where possible, as I find it generally helps everyone collaborate more efficiently.

Having said that, I'm not too sure about the intricacies of the different function types, so I'll leave it to you guys to decide what's best in this instance :)

**Comment by davidtheclark** [comment]
@MoOx is the connection to "functional style" because other functional languages have similar shorthands? Just curious.

I'll start using arrow functions regularly. When we do a refactor we can swap out anonymous for arrows for consistency's sake.

**Comment by jeddy3** [comment]
> I'll start using arrow functions regularly. When we do a refactor we can swap out anonymous for arrows for consistency's sake.

sgtm.
