### ISSUE TITLE
Deprecate extraction feature and build sufficient insertion system for modules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1509]
Ref: https://github.com/stylelint/stylelint/pull/1436#issuecomment-225595811

**Comment by davidtheclark** [comment]
I was just going to think about this a little this morning ...

I'm thinking right now maybe we should just drop the feature in v7, taking advantage of the major version bump, and leave an open ticket for someone to figure out how to handle this using an outside module.

I feel like this should be doable without altering stylelint at all except enhancing the Node API to accept sourcemaps. Then I imagine you could write a module that:

- Parses HTML (or something else) to pull out CSS.
- Builds sourcemap(s) for the extracted CSS.
- Runs that CSS through stylelint (probably via Node API).

Seems there's in fact a good opportunity for general purpose modules that extract CSS from non-stylesheets and create a PostCSS Result object *with sourcemap info*, so that CSS can be run through PostCSS plugins. (@ai know if such a tool exists already?)

**Comment by jeddy3** [comment]
> Seems there's in fact a good opportunity for general purpose modules that extract CSS from non-stylesheets and create a PostCSS Result object with sourcemap info

If such a module is doable, then I'm OK with dropping the extraction feature in `v7`. Do we need to rustle up a PoC, or do we just assume someone will find away? 

It's a significant deprecation though (as Atom Linter [uses this feature](https://github.com/AtomLinter/linter-stylelint/blob/master/lib/index.js#L59-L61)), and so I think we should expand the [release planning](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md) doc to outline our plans for this.

**Comment by davidtheclark** [comment]
Yeah. I guess I could try to find time to build the module myself so users don't feel abandoned :(

Might take a little while — but we do have a lot of things to do for v7, so probably there's no hurry.

**Comment by jeddy3** [comment]
> I guess I could try to find time to build the module myself so users don't feel abandoned

Maybe just a nod from @ai that such a tool is viable is all we need to put out the deprecation warning. That'll give the community plenty of time before `v7` to come up with a solution.

**Comment by davidtheclark** [comment]
I think that what we need is a `preprocess` and `postprocess` hook, like in ESLint's plugin system. That should be enough to handle the logic in our current HTML extractor: 

- During `preprocess` extract CSS from the HTML file and return that instead of the raw HTML. Create the sourcemap, too.
- During `postprocess`, match up warning positions with the sourcemap. Return the modified stylelint results instead of the originals.

These could be handled with a `processor` interface: a `processor` is an object with `preprocess` and `postprocess` functions.

The key question is: How do we handle loading processors, and providing that functionality to end users? It seems we'd have to do the same thing we've done with plugins: add `config.processors`, which would be an array of strings that can be either absolute paths, relative paths (relative to the config file), or npm module names.

Any thoughts on the above?

**Comment by jeddy3** [comment]
> I think that what we need is a preprocess and postprocess hook, like in ESLint's plugin system.

Sgtm! That seems like an eloquent way of going about it.

> It seems we'd have to do the same thing we've done with plugins: add config.processors

I think so.

**Comment by Arcanemagus** [comment]
Just a note, deprecation warnings are actually shown to the user now in the latest version of Atom's `linter-stylint` package instead of being silently ignored. Nobody had pointed them out as missing in an issue and I only noticed when testing links to the rule documentation 😛.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1539 & https://github.com/stylelint/stylelint/pull/1535
