### ISSUE TITLE
Consider releasing v7

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#1554]
Looking at the [changelog](https://github.com/stylelint/stylelint/blob/v7/CHANGELOG.md), v7 is one of the biggest stylelint releases in some time, it also contains a few breaking changes. 

However, there's still a number of open issues on the [v7 milestone](https://github.com/stylelint/stylelint/milestones/7.0.0). 

I wonder if it'd be worth moving some (or all) of the remaining v7 issues to a new v8 milestone, then releasing v7 to get the existing set of fixes and breaking changes out into the wild. 

What does the stylelint team think?

**Comment by jeddy3** [comment]
None of the remaining issue are blocked, nor do they seem too substantial. As such, I'm hopeful that we can complete the milestone in the next couple of weeks, and release one big set of breaking changes rather than staggering them. I think this will minimise the number of times users will have to revisit their configs. Anyone else have thoughts on this?

**Comment by davidtheclark** [comment]
@m-allonson Are there bug fixes in the v7 branch that you want now, or just features? We've tried to release bug fixes and minor features in the latest v6 branch instead of deferring it to v7 — in v7 we're packing breaking changes.

**Comment by m-allanson** [comment]
@davidtheclark nope, no fixes in particular. I guess I was concerned that v7 would turn into an eternally-rolling future milestone full of breaking changes that never get released. Feel free to close if that's not a concern :)

**Comment by davidtheclark** [comment]
I understand the feeling, but I'm not concerned :)
