### ISSUE TITLE
CSScomb compatibility

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1556]
Source: https://github.com/csscomb/csscomb.js/blob/master/doc/options.md
Rules:
- [x] `always-semicolon` 

Whether to add a semicolon after the last value/mixin. 

Acceptable value: true.

***Covered by rule `declaration-block-trailing-semicolon` with option `always`.***

Need testing with Less and SCSS syntax:
```scss
div {
    font: {
        family: fantasy;
        size: 16px; // semicolon here
    }
}
```
- [x] `block-indent` 

Set indent for code inside blocks, including media queries and nested rules.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces and tabs. Note that line breaks are not
    allowed here.

***Covered by rule `indentation` with option `int` if set `Number` or length of string if set `String`.***

In docs we have strange example:
```css
a {
    top: 0;
    p {
        color: tomato;
        position: happy;
        }
    }
```
Need investigation about this.
- [X] `color-case`

Unify case of hexadecimal colors.

Acceptable values:

* `lower` — for lowercase,
* `upper` — for uppercase.

***Covered by rule `color-hex-case` with option "lower" or "upper".***
- [X] `color-shorthand`

Whether to expand hexadecimal colors or use shorthands.

Acceptable values:

* `true` — use shorthands;
* `false` — expand hexadecimal colors to 6 symbols.

***Covered by rule `color-hex-length` with option "short" if we have `true` or "long" if we have `false`.***
- [X] `element-case`

Unify case of element selectors.

Acceptable values:

* `lower` — for lowercase;
* `upper` — for uppercase.

***Covered by rule `selector-type-case` with option "lower" or "upper".***
- [x] `eof-newline`

Add/remove line break at EOF.

Acceptable values:

* `true` — add line break;
* `false` – remove line break.

***Covered by rule `no-missing-eof-newline` with option "true" if we want check exist EOF, but it does not cover if we don't want.***
- [x] `exclude` 

List files that should be ignored while combing.

Acceptable value:

* `{String[]}` — array of
  [Ant path patterns](http://ant.apache.org/manual/dirtasks.html#patterns).

***Not covered. Need investigation.***
- [X] `leading-zero`

Add/remove leading zero in dimensions.

Acceptable values:

* `true` — add leading zero;
* `false` — remove leading zero.

***Covered by rule `number-leading-zero` with option "always" if we have `true` or "never" if we have `false`.***
- [ ] `quotes`

Unify quotes style.

Acceptable values:

* `single` — transform all `"` to `'`;
* `double` — transform all `'` to `"`.

***Covered by rule `string-quotes` with option "single" or "double".*** In example we see that it also covered quotes in attribute selector. Need complete rule `selector-attribute-quotes`.
- [X] `remove-empty-rulesets`

Remove all rulesets that contain nothing but spaces.

Acceptable value: `true`
***Covered by rule `block-no-empty`.*** But CSScomb remove empty block, i think this is wrong, we only check this.
- [x] `sort-order`

Set sort order. 

***Covered by partially `declaration-block-properties-order`, if we use only one group.*** In example, before each group we see newline, maybe covered by plugin `stylelint-block-structure`, need investigation and testing, also work fine with Less and SCSS `$variable`, `$include` and `$import`.
- [x] `sort-order-fallback`

Apply a special sort order for properties that are not specified in `sort-order`
list.

***Not covered, need investigation.***
- [x] `space-after-colon`

Set space after `:` in declarations.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `declaration-colon-space-before`. Need discussion.***. In CSScomb we can set how many spaces use.
- [ ] `space-after-combinator`

Set space after combinator (for example, in selectors like `p > a`).

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by rule `selector-combinator-space-after` with option `always`.*** Also in CSScomb support use newline, maybe add new rule `selector-combinator-newline-after`. Also we can use in string spaces after or before newline, we should take account, need discussion.
- [x] `space-between-declarations`

Set space between declarations (i.e. `color: tomato`).

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Not covered***
- [x]  `space-after-opening-brace`

Set space after `{`.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `block-opening-brace-newline-after`. Need investigation.***
- [ ] `space-after-selector-delimiter`
Set space after selector delimiter.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `selector-combinator-space-after`. Need investigation.***
- [x] `space-before-closing-brace`

Set space before `}`.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `block-closing-brace-space-before`. Need investigation.***
- [x] `space-before-colon`

Set space before `:` in declarations.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `declaration-colon-space-before`. Need investigation.***
- [x] `space-before-combinator`

Set space before combinator (for example, in selectors like `p > a`).

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `selector-combinator-space-before`. Need investigation.***
- [x] `space-before-opening-brace`

Set space before `{`.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `block-opening-brace-space-before` and `block-opening-brace-newline-before`***
- [x] `space-before-selector-delimiter`

Set space before selector delimiter.

Acceptable values:

* `{Number}` — number of whitespaces;
* `{String}` — string with whitespaces, tabs or line breaks.

***Covered partially by `selector-list-comma-newline-before` and `selector-list-comma-space-before`***
- [x] `strip-spaces`

Whether to trim trailing spaces.

Acceptable value: `true`.

***Covered by `no-eol-whitespace`*** Need testing with `tab`. Need investigation about `newlines`.
- [x] `tab-size`

Set tab size (number of spaces to replace hard tabs).

Acceptable values:

* `{Number}` — number of whitespaces;

***Covered partially by `indentation`?*** Need investigation.
- [x] `template`

**Note:** See [configuration docs](configuration.md#override-templates-settings)
for more information.

Acceptable value:

* `{String}` — path to the `.css` file.

***Not covered.*** Strange rule?
- [X] `unitless-zero`

Whether to remove units in zero-valued dimensions.

Acceptable value: `true`.

***Covered by rule `length-zero-no-unit`***
- [x] `vendor-prefix-align`

Whether to align prefixes in properties and values.

Acceptable value: `true`.

Example: `{ "vendor-prefix-align": true }`

***Not covered.*** Maybe plugin?
- [x] `verbose`

Whether to use `--verbose` option in CLI.

Acceptable value: `true`.

***Not covered*** Why?

---
Main question about this (in may rules):

Acceptable values:

{Number} — number of whitespaces;
{String} — string with whitespaces, tabs or line breaks.

Should we add ability to set how many spaces/newlines can use and that do we make with tabs?

**Comment by jeddy3** [comment]
@evilebottnawi Thanks for putting the legwork into this.

However, it feels like a slightly backwards way to go about proposing new features. For example, we only allow *single spaces* within our `*-space-before` and `*-space-after` rules. We've never had a request to support more, and so it seems odd to add a proposal for this solely because it "adds CSScomb compatibility". I'd rather wait for a real world requests for these types of things and then triage those issues individually.

With this in mind, I don't think there's harm in quickly running through your list - if only because it might help some future csscomb to stylelint/stylefmt converter author understand the differences between the two tools.

So, comments for the unchecked items above:

- `always-semicolon` - lets bump the non-standard syntax discussion to `stylelint-scss`.
- `block-indent` - done with [`indentClosingBrace`](https://github.com/stylelint/stylelint/blob/master/src/rules/indentation/README.md#indentclosingbrace-truefalse) option.
- `eof-newline` - no one has requested the opposite.
- `quotes` - we have an open `selector-attribute-quotes` issue.
- `sort-order-fallback` - done with [`unspecified`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-properties-order/README.md#unspecified-topbottombottomalphabeticalignore) option.
- `sort-order` - we have an open issue for `stylelint-block-non-properties-order`.
- `space-after-colon` - see multiple space paragraph above.
- `space-after-combinator` - no one has requested newlines before or after combinators.
- `space-after-opening-brace` - see multiple space paragraph above.
- `space-after-selector-delimiter` - see multiple space paragraph above.
- `space-before-closing-brace` - see multiple space paragraph above.
- `space-before-colon` - see multiple space paragraph above.
- `space-before-combinator` - see multiple space paragraph above.
- `space-before-opening-brace` - see multiple space paragraph above.
- `space-before-selector-delimiter` - see multiple space paragraph above.
- `space-between-declarations` - once the proposal in https://github.com/stylelint/stylelint/issues/1500 is agreed on, I'll create an issues for `declaration-empty-line-before` and `stylelint-property-groups-structure`.
- `strip-spaces` - covered by no-eol-whitespace.
- `tab-size` - covered by `indentation`.
- `vendor-prefix-align` - plugin.

`vendor-prefix-align` is a good example of how this approach is kind of backwards. We wouldn't consider including a rule like this in core as the CSS landscape has changed (with the emergence of tooling like autoprefixer) and aligning vendor prefixes in a source file is now a edge-case, rather than useful to the majority of users.

There's no harm in adding a "CSScomb milestone" to the individual related issues I mentioned above. Once this is done I think we can close this issue.

**Comment by evilebottnawi** [comment]
@jeddy3 feel free to edit my post and check and add commented about rules and how implement this, it is allow write coverter CSScomb rules to stylelint rules :smile:

**Comment by davidtheclark** [comment]
Thanks for thinking this through @evilebottnawi and @jeddy3

**Comment by jeddy3** [comment]
> feel free to edit my post and check and add commented about rules and how implement this, it is allow write coverter CSScomb rules to stylelint rules

I looked through the items in your list again and I think I've accounted for everything an author might need in my reply above. So, I've checked all the items.

Having a "CSScomb compatibility" milestone, on second thoughts, doesn't make sense as it's not actually something we're trying to achieve within stylelint core. So, I'll close this issue now as all the relevant bits are covered in the other issues linked to from my reply.

**Comment by aleh-vasilyeu** [comment]
@evilebottnawi, thanks, great job, your comment is very valuable!
I can only add that now sort-order could be easily covered by [stylelint-order](https://github.com/hudochenkov/stylelint-order) plugin: order/properties-order rule.
Perhaps, it will be helpful for someone else.
