### ISSUE TITLE
Add rule which checks invalid negative time 

### ISSUE THREAD

**Issue by nkt** [stylelint/stylelint#1563]
I've sent PR which add support for negative time in `time-no-imperceptible` rule.
But there are rules which not supports negative time. For example negative time is invalid for `animation-duration` and valid for `animation-delay`.
I can contribute this rule on weekend, `no-invalid-negative-time` is good name for this rule?

**Comment by evilebottnawi** [comment]
Maybe `time-animation-no-invalid`?

**Comment by evilebottnawi** [comment]
Though, to tell it again refers to the rule `declaration-no-invalid`, which test property on valid value.

**Comment by nkt** [comment]
So I have to update `declaration-no-invalid`, right?

**Comment by evilebottnawi** [comment]
@nkt for the stability of the core, we have decided to implement this rule as plugin and further after testing include in core. Feel free to create plugin, it is will be awesome!

**Comment by nkt** [comment]
Ok, on this weekend. I'll mention you 😉

**Comment by evilebottnawi** [comment]
@nkt if you need help, ping me :smile:

**Comment by jeddy3** [comment]
@nkt `declaration-no-invalid` is a [*proposed plugin*](https://github.com/stylelint/stylelint/issues/1085) that will be powered by [`css-values`](https://github.com/ben-eb/css-values). It will be capable of checking the validity of *all* property: value pairs.

So, our recommendation is that people contribute to [`css-values`](https://github.com/ben-eb/css-values) so that the `declaration-no-invalid` plugin comes into being, rather than work on a specific plugins that, for example, disallows negative values for certain properties.
