### ISSUE TITLE
Support for array as primary option in plugins

### ISSUE THREAD

**Issue by sh-waqar** [stylelint/stylelint#1579]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A feature may be to add support for array as primary option in custom plugins. I am facing an issue with the Determine options method in stylelint.createPlugin method. Here is the reported [issue](https://github.com/sh-waqar/stylelint-declaration-use-variable/issues/8). I have a scenario in my plugin where the primary option can be an array.

> What stylelint configuration is needed to reproduce this issue?

```json
// .stylelintrc
"plugins": [
  "stylelint-declaration-use-variable"
],
"rules": {
  // ...
  "declaration-use-variable": ["/color/", "z-index", "font-size"],
  // ...
}
```

> Which version of stylelint are you using?

`6.7.1`

**Comment by evilebottnawi** [comment]
@sh-waqar use `"declaration-use-variable": [["/color/", "z-index", "font-size"]]`

**Comment by sh-waqar** [comment]
@evilebottnawi - Yes it works this way but is this the right way to do it? since all the rules in `stylelint` library that have this particular scenario like [function-whitelist](http://stylelint.io/user-guide/rules/function-whitelist/) utilizes the single array as primary option.

**Comment by sh-waqar** [comment]
Providing the same behavior for custom plugins will make it consistent.

**Comment by jeddy3** [comment]
Perhaps there is a way of either:

- a plugin/rule registering as accepting an array as a primary option.
- holistically determining if a plugin/rule accepts an array as a primary option.

Rather, than [maintaining a list](https://github.com/stylelint/stylelint/blob/master/src/normalizeRuleSettings.js) of known rules to do so.

**Comment by davidtheclark** [comment]
For this reason I think we made a mistake originally in following ESLint and using an array with implicit "keys" instead of an object with real keys. People no doubt would have complained about the verbosity of an object for every rule, but there's no disputing the clarity and flexibility it would provide. And verbosity in configuration is not that bad. Anyway, it's probably too late for that. 

From my memory of tinkering with this before, I am not confident there's a good way to determine whether an array should be interpreted as a primary option or a tuple where the first value is the primary option and second is the secondary option.

It makes more sense in my mind, then, for a plugin to register itself as requiring an array as the primary option.

**Comment by jeddy3** [comment]
> using an array with implicit "keys" instead of an object with real keys.

You mean like so?:

```json
{
  "rules": {
    "unit-whitelist": {
      "primaryOption": ["em", "rem", "%"],
      "secondaryOptions": { 
         "ignore": ["made-up-keyword"]
      },
      "message": "Only use a subset of units",
      "severity": "warning"
    }
  }
}
```

Looks pretty dandy to me.

> Anyway, it's probably too late for that.

I see where you're coming from, but is it too late? We're doing a lot in `7.0` to perfect things. Do we think the initial pain of this will be more or less than that of dealing with future bugs around plugins not registering their use of an array? Tough call... either way, after `7.0` it's probably a bad idea.

**Comment by davidtheclark** [comment]
Would be interested to hear others' opinions about this.

**Comment by Nirazul** [comment]
Hah, just thought about leaving my opinion here when your comment popped up ^^

Pretext:
My opinion is built on the perspective I have as a maintainer of a build system at my workplace, a design oriented web and native app company with many different clients. I'm using stylelint as a tool amongst others to enforce a common codebase throughout our frontend team accross a plethora different projects.

So as my team is not primarily concerned about our build tools (that has become my task along with the usual project based work), there lies a big concern in keeping the mental overhead of this part at a minimum. 

What that means is, that for me, it'd be best to maintain all code style and linting tools with one single API or at least something that is as similar to each other as possible. That's what I'm aiming for.

So I'm not too fond of the idea of changing or bloating the config structure, as this is the very core of stylelint. There is probably no other area of this tool that literally everyone uses. I can do without this or that rule, but I can't use stylelint without some sort of config (well, apart from using somebody else's).

Concluding, in a selfish egoistic me-centered world, I'd suggest to, instead of moving further away from eslint config, going all the way and create complete parity. 

I know that this is utopic and probably doesn't make much sense from your perspective as maintainer of this wonderful piece of code. But it's just that, an opinion you wanted to hear :)

**Comment by sh-waqar** [comment]
@Nirazul - Good points. I think as a developer who is using stylelint in multiple code bases there would be a lot of overhead if go towards the configuration @jeddy3 proposed. configuring every single rule in this manner would create a long config file eventually.

In my opinion, its better to do something that make the config as similar to other linting plugins like eslint, jshint as possible.

**Comment by jeddy3** [comment]
> In my opinion, its better to do something that make the config as similar to other linting plugins like eslint, jshint as possible.

I'm not sure there is much consistency between linters.

JsHint looks like this:

```js
{
  "undef": true,
  "unused": true,
  "predef": [ "MY_GLOBAL" ]
}
```

JSCS like:

```js
{
    "requireSpaceBetweenArguments": true,
    "maximumLineLength": {
        "value": 100,
        "tabSize": 4,
        "allExcept": ["urlComments", "regex"]
    },
    "requireOperatorBeforeLineBreak": null, // or false
}
```

Eslint was previously:

```js
{
    "rules": {
        "eqeqeq": 0,
        "curly": 2,
        "quotes": [1, "double", {"avoidEscape": true }]
    }
}
```

But now appears to be:

```js
{
    "rules": {
        "eqeqeq": "off",
        "curly": "error",
        "quotes": ["warning", "double", {"avoidEscape": true }]
    }
}
```

Remark (a markdown linter we use for our docs):

```js
{
  "plugins": {
    "remark-lint": {
      "no-multiple-toplevel-headings": false,
      "list-item-indent": false,
      "maximum-line-length": 79
    }
  }
}
```

Scss-lint (which is pretty similar to the object proposal above in how severities are set):

```yaml
linters:
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    severity: warning
    exclude: ['_normalize.scss']
    order: [
      "position",
      "top",
      "right"
    ]
```

Each seems to have it's own way of turnings rules on and off, setting severties levels and configuring options. So, I think you when you say "similar to other linters" you actually mean similar to eslint. Unfortunately, that's not possible as we had (up to version `3.0.0` I think it was) a config style exactly like eslint's but there were limitations to this syntax (e.g. difficulties supporting custom severities is one I remember off-hand) and so we had to change it to what we have now.

[This issue itself](https://github.com/stylelint/stylelint/issues/1579#issue-163515577) is caused by another limitation of this array with implicit "keys" syntax. One that effects plugin developers. The proposal above attempts to resolve this issue. I understand that this comes with moving the cost to configuration authors. At the moment that cost is felt by plugin developers and by this [bit of fragile code](https://github.com/stylelint/stylelint/blob/master/src/normalizeRuleSettings.js) in core--which has lead to two broken releases in the past.

It's not clear at all what the right balance is, but having you both chime in with your thoughts (which is appreciated) will help us find that balance. Like @davidtheclark said, in a ideal world we would have gone with a more extensible config syntax from the start... but now we also need to take into account the cost to all the existing users of changing configuration syntax, rather than just calculating the cost of new config setups.

> It makes more sense in my mind, then, for a plugin to register itself as requiring an array as the primary option.

So, I think we have two options:

1. Keep the original syntax and requiring plugins to register themselves.
2. Adopt the more extensible syntax detailed above.

Does anyone else have an opinion on the various costs of these?

**Comment by ntwb** [comment]
I've no strong opinion on this per se... 

That said though I have opinions on this if a change was to go forward, in particular:
> _"...but now we also need to take into account the cost to all the existing users of changing configuration syntax, rather than just calculating the cost of new config setups."_

Right now there are ~190 repo's with `stylelint` in their name/description and ~2,836 repos that include `stylelint` in the `package.json` file (These are pretty broad and may include forks), these are not insignificant numbers when it comes to a _major_ change where the onus of configuration change changes from the ~190 repos to the ~2,836 repos.

**Comment by davidtheclark** [comment]
As @jeddy3 said, there is no universal linter syntax standard, so we will not move closer to ESLint's style just because. For the record, I think JSCS and SCSS got it right using key-values. I don't really side with complaints about "bloated" config files, because more explicitness is definitely preferable, and there aren't actual negative consequences to making the files larger so they can be more legible and flexible. Also: If you have teammates who don't want to care much about the linter and just poke in sometimes, it's absolutely better for them to see keys labelling values, instead of having to read up on a convention-based array system. So, again, I still think we were mistaken in following ESLint's lead and using loaded arrays.

Is it worth changing, though, especially considering the usage stats @ntwb cites? ?????? I don't know. I guess given those numbers I'd err on the side of keeping things the same, and making plugins register themselves as requiring (not "accepting", but always *requiring*) arrays for their primary options.

**Comment by Nirazul** [comment]
After having slept about it and looking again at JSCS and SCSS examples, I think I'd like the idea of one single config object per rule as long as it is not nested (for example for secondary options):

```json
{
  "rules": {
    "unit-whitelist": {
      "primaryOption": ["em", "rem", "%"], // could also be called "value"
      "ignore": ["made-up-keyword"],
      "severity": "warning"
    }
  }
}
```

...which could be reduced to following in simple cases:

```json
{
  "rules": {
    "string-no-newline": true,
    "value-keyword-case": "lower",
    "unit-whitelist": ["%"]
  }
}
```

As no rule has an object as primary option (doesn't make sense, anyway.. right?), there's very little overhead when you use a simple config file like [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js).

**Comment by jeddy3** [comment]
> As no rule has an object as primary option (doesn't make sense, anyway.. right?)

The `declaration-property-*-blacklist/whitelist` rules do, e.g. [`declaration-property-unit-blacklist`](https://github.com/stylelint/stylelint/tree/master/src/rules/declaration-property-unit-blacklist).

It's a nice idea though.

> I guess given those numbers I'd err on the side of keeping things the same, and making plugins register themselves as requiring (not "accepting", but always requiring) arrays for their primary options.

This does feel like the most practical way forward, considering those numbers.

**Comment by ntwb** [comment]
> especially considering the usage stats @ntwb cites? ??????

My numbers came from basic GitHub searches, apologies I should have included the links:

• ~190 repo's with `stylelint` in their name/description https://github.com/search?q=stylelint&type=Repositories&utf8=%E2%9C%93
• ~2,836 repos that include `stylelint` in the `package.json` file https://github.com/search?l=json&q=stylelint&type=Code&utf8=%E2%9C%93

** As stated originally, pretty rudimentary GitHub searches, nonetheless not insignificant numbers

**Comment by jeddy3** [comment]
If no one has anything else to add, it looks making plugins register is the most sensible solution. I'll label this up as "enhancement" and "help wanted".

**Comment by sh-waqar** [comment]
@jeddy3 - So how this is going to work? Should we add guidelines in the documentation for custom plugins? If anyone has a custom plugin that needs array support for the primary option they can update the [normalizeRuleSettings.js](https://github.com/stylelint/stylelint/blob/master/src/normalizeRuleSettings.js) file.

**Comment by jeddy3** [comment]
> So how this is going to work?

We need to implement a feature where rules and plugins can *register* themselves as requiring an array for their primary options. I don't think the actual implementation details are worked out though. I assumed registering themselves meant that rule and plugins would set a flag *within themselves*. And I thought that this would replace the hard coded list of rules within ` normalizeRuleSettings.js`. @davidtheclark Is closer to this piece of stylelint than anyone and so he might have a implementation in mind. Otherwise, feel free to fire over a proof-of-concept Pull Request if you have an idea of how to implement this.

> Should we add guidelines in the documentation for custom plugins?

Yes, we'll need to add a note to the [plugin guidelines](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md). But we won't know what to add until the implementation is done.
