### ISSUE TITLE
New rule: `font-weight-notation-no-unknown`

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1701]
Following discussion of  _unknown numerical font weights_ in #1687 proposing a new rule here:

• `font-weight-notation-no-unknown`

https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Values

> * normal
>  * Normal font weight. Same as 400.
> * bold
>  * Bold font weight. Same as 700.
> * lighter
>  * One font weight lighter than the parent element (among the available weights of the font).
> * bolder
>  * One font weight darker than the parent element (among the available weights of the font).
> * 100, 200, 300, 400, 500, 600, 700, 800, 900
>  * Numeric font weights for fonts that provide more than just normal and bold.

**Comment by jeddy3** [comment]
I think we decided in https://github.com/betit/stylelint-known-property/issues/6#issuecomment-229346546 that we'd only add *broad stroke* `*-no-known` rules to core i.e. ones for *units*, *properties*, *at-rules*, *type selectors*, *pseudo-class selectors* and *pseudo-class selectors*. And that anything more fine-grained than that, e.g. property value pairs, would be skipped in favour of work towards boarder `css-values` powered rules like `declaration-no-invalid`. 

This is because these `*-no-unknown` rules will be made redundant by `declaration-no-invalid`. Adding the *broad stroke* `*-no-unknown` made sense because it added *a lot* of *immediate* benefit to most users. In this proposal we'd only be validating the very specific `font` and `font-weight` value pairs. That narrow scope feels like it's no worth the effort, nor redundancy going forward.

We've ruled out other value property pair validation rules in the past for this reason e.g. [invalid negative time](https://github.com/stylelint/stylelint/issues/1563).

**Comment by ntwb** [comment]
Cool, I'm fine with this 👍

**Comment by gitdeepr** [comment]
Sandboxing disabled by user.
Unknown property font-wight
Unknown property font-wight
Unknown property font-wight
[22073:22081:0507/182305.851381:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
Any idea what it is ..

**Comment by jeddy3** [comment]
@gitdeepr I don't think that error is related to stylelint. Whatever tool is reporting it, I'm sure correcting the spelling of `font-wight` to `font-weight` will fix it.
