### ISSUE TITLE
Integrate `https://greenkeeper.io`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1703]
/cc @stylelint/core 
It allows you to conveniently update the dependencies, and not to forget about them.

**Comment by jeddy3** [comment]
Sgtm.

**Comment by TrySound** [comment]
It reacts on every patch and minor which is sucks https://github.com/TrySound/case/pulls

**Comment by evilebottnawi** [comment]
@TrySound and options to change the behavior is not, as I understand it?

**Comment by TrySound** [comment]
Wasn't. And I don't see any mention in docs now.

**Comment by ntwb** [comment]
@TrySound The reason Greenkeeper keeps on opening pull requests is because there is an update to a package not covered by semantic versioning in your `package.json`

Example [in your](https://github.com/TrySound/case/blob/master/package.json#L47) `package.json` you have `"stylelint": "^5.0.1",`, Greenkeeper will create a new pull request for each new release of stylelint. You should close each of [these pull requests](https://github.com/TrySound/case/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20stylelint) except the stylelint 7.0.3 pull request.

**Comment by ntwb** [comment]
I use Greenkeeper on [one of my repo's](https://github.com/ntwb/eslint-plugin-wordpress/pulls?q=is%3Apr+is%3Aclosed+label%3Agreenkeeper) which I've testing for a couple of months, no problem adding here from my perspective, does its job quite well, so sgtm 👍 

I just tried to enable Greenkeeper but repo admin access is required.

Below are the instructions on activating Greenkeeper, they are pretty straight forward:

----

# Getting Started with Greenkeeper
To install Greenkeeper, type: `npm install -g greenkeeper`

Then log in: `greenkeeper login`

> Your browser will open a new window or tab and redirect you to GitHub’s
Application Authentication screen. There is a big green button [Authorize
application] at the bottom. When you click it, Greenkeeper gets the access to
GitHub it needs to do its job, but no more. When all goes well, your browser
will say “Check your Terminal”, and when you switch back here, the login will
be done and Greenkeeper will have started to sync your GitHub repository
information.
>
> Congratulations, you made it past the most complicated step!

Next, you enable a repository of yours. To do this, navigate to a local
copy of your repository (e.g. cd ~/code/myrepo). Then: `greenkeeper enable`

And that’s it already! :)

**Comment by jeddy3** [comment]
> I use Greenkeeper on one of my repo's which I've testing for a couple of months, no problem adding here from my perspective, does its job quite well, so sgtm 

Sounds solid enough for me. 

@davidtheclark Any objections if I enable this?

**Comment by davidtheclark** [comment]
Sure let's give it a try.

**Comment by jeddy3** [comment]
Done

**Comment by Arcanemagus** [comment]
Since it was never explicitly stated here Greenkeeper checks against _every_ new version of your dependencies, it will then open a PR updating to that version if _any_ of the following conditions are met:

* One of the CI builds fails (the update broke it, or something else changed that broke it)
* The update is outside the currently allowed range
* No CI is configured (@TrySound this is where your project is stuck)

**Comment by ntwb** [comment]
Here's an example from overnight for NYC 7.1.0:

![screen shot 2016-07-26 at 8 17 37 am](https://cloud.githubusercontent.com/assets/1016458/17119493/9c27fb6a-5309-11e6-842f-da897932935c.png)

So even though the `7.1.0` is covered by the semantic version `"nyc": "^7.0.0",` a new branch is created for the CI tests to run against, if all returns "green OK" then the branch is deleted, if any CI job fails then a pull request is created.

**Comment by ntwb** [comment]
Ah, that same NYC `7.1.0` release did the exact same thing for stylelint:
• https://travis-ci.org/stylelint/stylelint/builds/147230247
• https://coveralls.io/github/stylelint/stylelint?branch=greenkeeper-nyc-7.1.0

As NYC `7.1.0` is covered by stylelint's semantic version `"nyc": "^7.0.0"` no action is requiried.

The next merge to `master` will update `master` to use NYC 7.1.0 as part of `npm update` in our `.travis.yml` thus uploading the latest coverage from our tests to Coveralls
