### ISSUE TITLE
Synthesize optionsHaveIgnored utils

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1715]
I don't think we should be mass producing `optionHaveIgnored*` util functions the way we are. They are much too simple to justify the additional code and tests. Instead, how about a single function, `optionsHave`, that just does this: `optionsHave('ignore', 'walrus')`, `optionsHave('except', 'kendo')`, `optionsHave('ignoreProperties', 'color')`?

**Comment by jeddy3** [comment]
I agree that they can be synthesised. I experimented with this when working on https://github.com/stylelint/stylelint/pull/1697, but it wasn't obvious what the best solution was.

In https://github.com/stylelint/stylelint/pull/1711#discussion_r72264874 is the suggestion of testing the string, rather than the node. I think the origins of the first `ignores*` rule was [`block-closing-brace-newline-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/block-closing-brace-newline-after/index.js#L50). Where a *statement* node was checked, first to see if it was of `type` `atRule` and then if the name matched. I think it was done this way so that the node type conditional and name extraction logic weren't duplicated across the rule using `ignoresAtRules`.

Also, the `ignore` and `except` keyword options behave quite differently from the `ignore*` options. The former is a simple look-up, whereas the later uses `matchesStringOrRegEx`. Perhaps two functions would work?:

- `optionsHasKeyword(options, "ignore", "after-comment")`
- `optionsMatches(options, "ignoreProperties", propName)`

Either way, I agree that it'll be great to see all the `option*` utils consolidated somehow :)
