### ISSUE TITLE
CSSLint compat

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1739]
# All rules

## Possible Errors

- [ ] [box-model](https://github.com/CSSLint/csslint/wiki/Beware-of-box-model-size)
- [ ] [display-property-grouping](https://github.com/CSSLint/csslint/wiki/Require-properties-appropriate-for-display) -> `"declaration-block-no-ignored-properties": true`, but we have more properties than in `CSSLint` maybe write plugin for this based on this rule and remove all checks not compat with `CSSLint`? I can do this.
- [ ] [duplicate-properties](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties) -> `"declaration-block-no-duplicate-properties": true` and we should add option `ignoreDifferenceValue`(maybe search best name)
- [x] [empty-rules](https://github.com/CSSLint/csslint/wiki/Disallow-empty-rules) -> `"block-no-empty": true`
- [ ] [known-properties](https://github.com/CSSLint/csslint/wiki/Require-use-of-known-properties) -> `"property-no-unknown"` i offer a little remake rule, ignore vendor by default, because all rules default ignore this, and add option `noVendorIgnore`(maybe best name), it is allow in future extend all `*-no-unknown` rules checking vendor prefixes if we have time to write or found repo with list.

## Compatibility

- [ ] [adjoining-classes](https://github.com/CSSLint/csslint/wiki/Disallow-adjoining-classes)
- [x] [box-sizing](https://github.com/CSSLint/csslint/wiki/Disallow-box-sizing) -> `"property-blacklist": ["box-sizing"]`
- [ ] [compatible-vendor-prefixes](https://github.com/CSSLint/csslint/wiki/Require-compatible-vendor-prefixes)
- [ ] [gradients](https://github.com/CSSLint/csslint/wiki/Require-all-gradient-definitions)
- [ ] [text-indent](https://github.com/CSSLint/csslint/wiki/Require-standard-property-with-vendor-prefix)
- [ ] [vendor-prefix](https://github.com/CSSLint/csslint/wiki/Require-standard-property-with-vendor-prefix)
- [ ] [fallback-colors](https://github.com/CSSLint/csslint/wiki/Require-fallback-colors)
- [ ] [star-property-hack](https://github.com/CSSLint/csslint/wiki/Disallow-star-hack)
- [ ] [underscore-property-hack](https://github.com/CSSLint/csslint/wiki/Disallow-underscore-hack)
- [ ] [bulletproof-font-face](https://github.com/CSSLint/csslint/wiki/Bulletproof-font-face)

## Performance

- [ ] [font-faces](https://github.com/CSSLint/csslint/wiki/Don%27t-use-too-many-web-fonts)
- [x] [import](https://github.com/CSSLint/csslint/wiki/Disallow-%40import) -> `'at-rule-blacklist': ['import'],`
- [x] [regex-selectors](https://github.com/CSSLint/csslint/wiki/Disallow-selectors-that-look-like-regular-expressions) -> `"selector-attribute-operator-blacklist": ["~=", "^=", "|=", "$=", "*="]`
- [x] [universal-selector](https://github.com/CSSLint/csslint/wiki/Disallow-universal-selector) -> `"selector-no-universal": true`
- [ ] [unqualified-attributes](https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors)
- [x] [zero-units](https://github.com/CSSLint/csslint/wiki/Disallow-units-for-zero-values) -> `"length-zero-no-unit": true`
- [ ] [overqualified-elements](https://github.com/CSSLint/csslint/wiki/Disallow-overqualified-elements)
- [ ] [shorthand](https://github.com/CSSLint/csslint/wiki/Require-shorthand-properties) -> Ref: https://github.com/stylelint/stylelint/issues/1735
- [ ] [duplicate-background-images](https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-background-images)

## Maintainability & Duplication

- [ ] [floats](https://github.com/CSSLint/csslint/wiki/Disallow-too-many-floats)
- [ ] [font-sizes](https://github.com/CSSLint/csslint/wiki/Don%27t-use-too-many-font-size-declarations)
- [x] [ids](https://github.com/CSSLint/csslint/wiki/Disallow-IDs-in-selectors) -> `"selector-no-id": true`
- [x] [important](https://github.com/CSSLint/csslint/wiki/Disallow-%21important) -> `"declaration-no-important": true`

## Accessibility

- [ ] [outline-none](https://github.com/CSSLint/csslint/wiki/Disallow-outline%3Anone)

## OOCSS 

- [ ] [qualified-headings](https://github.com/CSSLint/csslint/wiki/Disallow-qualified-headings)
- [ ] [unique-headings](https://github.com/CSSLint/csslint/wiki/Headings-should-only-be-defined-once)

Feel free to edit my post. Let's rock!
Ref: https://github.com/CSSLint/csslint/issues/668

**Comment by jeddy3** [comment]
What is the purpose of this issue? 

As the next step is to decide which of these should be rules and which should be plugins, I assume it's to track that a discussion and decision has be made for each of them?

**Comment by evilebottnawi** [comment]
@jeddy3 tracking the overall process, `eslint` is doing the same and it is convenient :smile:

**Comment by evilebottnawi** [comment]
@jeddy3 here it is possible to gather configuration with references to plugins and issue

**Comment by evilebottnawi** [comment]
@jeddy3 and many developers `CSSLint` are have poor knowledge `stylelint`, so it would be better to postpone the discussion here

**Comment by ai** [comment]
I think step 2 should be sort plugins to 2 categories:

1. We should write this plugin as core Stylelint rule.
2. We should create third-party rule.

**Comment by ai** [comment]
I think we should create `stylelint-oocss` for `qualified-headings` and `unique-headings`.

**Comment by ai** [comment]
I think this rules should be in `stylelint-csslint`:

* `font-size` — too unclear what is too often `font-size`, also this recommendation is not popular
* `floats` — not popular recommendation
* `box-model` — CSSLint rule will not work `* { box-siting: border-box }`
* `display-property-grouping` — because our rule is better
* `adjoining-classes` — not popular practice
* `compatible-vendor-prefixes` — we could do it based based on Autoprefixer logic. Just check that all props has Autoprefixer’s prefixes. But maybe we could ignore this rule.
* `gradients` — same, run Autoprefixer and check that user CSS is equal to Autoprefixer output. But maybe we could ignore this rule.
* `fallback-colors` — useful few years ago, but now outdated.
* `star-property-hack` and `underscore-property-hack` — I think it will be more easy to create new rule (it will be very small), rather than add option to Stylelint’s rule.
* `bulletproof-font-face` — useful. but outdated
* `duplicate-background-images` — it is better to do it by PostCSS plugin.

I think this rules could be part of `stylelint` core

* `outline` — important a11n rule
* `duplicate-properties` — I think extra option is fine
* `known-properties` — we already have it, need extra option.
* `vendor-prefix` — very useful recommendation.
* `font-faces` — useful
* `unqualified-attributes` — useful too to every project
* `overqualified-elements` — useful too to every project
* `shorthand` — useful too to every project

@davidtheclark @jeddy3 @evilebottnawi what do you think?

**Comment by delorge** [comment]
as @evilebottnawi said, we should probably make a plugin for 
`font-size`, `floats `, `font-faces` because they are similar. I guess this plugin could be flexible and set to track any properties' repetitions

**Comment by delorge** [comment]
I'd like to take a stab at this

**Comment by evilebottnawi** [comment]
@delorge i think about rule allow set max usage `at-rules`, `properties` and etc, i think it is be good into core, example usage disable use many animation, it is good for performance

**Comment by jeddy3** [comment]
I think the usefulness of such a rule is questionable. If there is a desire to build this then I think it'll need to be a plugin.

- Only really makes sense for compiled stylesheets.
- The number of these things (e.g. font-face) in terms of performance is kind of arbitrary.  

See [this discussion](https://github.com/stylelint/stylelint/issues/964).

**Comment by jeddy3** [comment]
> @davidtheclark @jeddy3 @evilebottnawi what do you think? 

I think all the rules you've suggested go in `stylelint-csslint` are correctly classified.

I've created [new issues](https://github.com/stylelint/stylelint/milestone/22) to discuss:

* `outline` — important a11n rule
* `duplicate-properties` — I think extra option is fine
* `known-properties` — we already have it, need extra option.
* `shorthand` — useful too to every project

I'm think the following four should also be plugins, mainly because it's questionable if they meet the "Useful to the majority of users" [criteria](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#let-everyone-know):

* `vendor-prefix` - unlikely to be used by anyone using autoprefixer.
* `font-faces` - see https://github.com/stylelint/stylelint/issues/1739#issuecomment-237273063
* `unqualified-attributes` - maybe a performance concern a couple of years ago. Either way that rules advocates increasing the specificity, which I suspect most users will likely want to avoid these days.
* `overqualified-elements` I suspect most users would want to disallow qualifying type selectors outright using [`selector-no-qualifying-type`](https://github.com/stylelint/stylelint/tree/master/src/rules/selector-no-qualifying-type).

**Comment by davidtheclark** [comment]
@jeddy3 I agree with your suggestions.

**Comment by evilebottnawi** [comment]
@jeddy3 agree
> overqualified-elements I suspect most users would want to disallow qualifying type selectors outright using selector-no-qualifying-type.
Perhaps in the future if we get a request, we can add an option for this

**Comment by Mouvedia** [comment]
It seems the `stylelint-csslint` plugin was never published.
The only package I could find is [stylelint-csslint-missing](https://www.npmjs.com/package/stylelint-csslint-missing).
