### ISSUE TITLE
Ignore empty blocks in block-no-single-line

### ISSUE THREAD

**Issue by nicothin** [stylelint/stylelint#1828]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

new option

> Which rule, if any, is this issue related to?

block-no-single-line

> What CSS is needed to reproduce this issue?

```less
.foo {
  &__bar {}
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "block-no-single-line": [true],
  }
}
```

> Which version of stylelint are you using?

7.1.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `.stylelintrc`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to LESS, Sass ect.

> What did you expect to happen?

Add ignore option for selectors with `{}` (empty)

**Comment by m-allanson** [comment]
Maybe this could be the default behaviour for the rule?  There's similar behaviour for some other rules, which was discussed here: https://github.com/stylelint/stylelint/issues/160. It wouldn't be a breaking change as it makes the rule more permissive.

Otherwise adding this as an option also sounds good.

**Comment by jeddy3** [comment]
> Maybe this could be the default behaviour for the rule?

Sgtm.

How odd that you dug up #160... I was just recalling that issue over in https://github.com/stylelint/stylelint/issues/1835 :) Nice to see an old three digit issue number pop up.
