### ISSUE TITLE
Can't load configuration file by css file's path

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#1881]
My project files
```
~/myproject/css/.stylelintrc.json
~/myproject/css/test.css
~/myproject/js/.eslintrc.json
~/myproject/js/test.js
```

```bash
cd ~/myproject/
eslint js/*
stylelint css/*
```

When I Change the current working directory to `~/myproject/`, then executed `eslint js/*`, `stylelint` will throw a error: `No configuration found`.

In same case, `ESLint` is work fine.
I hope that, when I didn't set `--config`, stylelint can find configuration file by file path. Just like `ESLint`

**Comment by gucong3000** [comment]
When I use postcss plugin, I have same problem. my build tool use stylelint to lint other multiple projects.
Each project has its own configuration file. So I created a pr: #1836

**Comment by gucong3000** [comment]
Many project are used file‘s’ path to lookup configuration file, not lookup by `process.cwd()`.
like: [eslint](https://www.npmjs.com/package/eslint), [jshint](https://www.npmjs.com/package/jshint), [editorconfig](https://www.npmjs.com/package/editorconfig), [babeljs](https://babeljs.io/).

When multiple CSS files are executed in parallel with stylelint, and these CSS files belong to different projects and have different configurations, this can lead to confusion.

**Comment by davidtheclark** [comment]
@gucong3000 Thanks for writing up the issue. I'm afraid I'm vacation for another week and a half. I just dropped in for a short time to check up on things. So I will have to give this more thought after I get back.

In the meantime, I can say that you accomplish what you want in a pretty straightforward way by adding `.stylelintrc` files in your sub-projects that `extend` the main `.stylelintrc`.

Once I get back I'll think more about the possibility of starting the search for configuration from the file that is being linted.

**Comment by gucong3000** [comment]
@davidtheclark 
#1888 
It is works good.

**Comment by ntwb** [comment]
Thanks @gucong3000, as David is still on holiday it will take some more time before being reviewed further 😄

**Comment by davidtheclark** [comment]
I'm think this would be a fine feature. However, I think it will require a change to cosmiconfig, because we'll want cosmiconfig to cache across all the different calls. If, for example, there are 500 CSS files being linted, we don't want cosmiconfig to run its full check for each of those files. We'd want, I think, to create a cosmiconfig instance that can be repeatedly invoked, and will cache whether or not any given directory has already been inspected. Additionally, if a config is found at the same place for two different files, we don't want to read the file and parse the config each time: we want to cache the read & parse result. I will look into this.

**Comment by Arcanemagus** [comment]
A `cosmiconfig` cache sounds awesome, in my experience watching the timings in `linter-stylelint` the time it takes to run `cosmiconfig` is usually at least half the total time of the entire run.

**Comment by davidtheclark** [comment]
@Arcanemagus and @stylelint/core: I'm preparing a new (major) version of cosmiconfig with caching. To enable the caching, the API changed a little, such that you create cosmiconfig instances, rather than the module just exporting a single function. I would appreciate it if you could find some time in the next few days to check out the master branch on https://github.com/davidtheclark/cosmiconfig and see if the documentation makes sense to you.

I'll wait to deliver that release until I get the 👍 or 👎 from you!

**Comment by davidtheclark** [comment]
Also, about the caching: you should be able to see how it's intended to work [in the cache tests](https://github.com/davidtheclark/cosmiconfig/blob/master/test/caches.test.js) — but they are kind of long. The main idea is that any search path you'd already provided, directory that's already been visited, or file that's already been read & parsed will be cached, so that the next time a search is initialized it can avoid having to hit the file system again for those already-visited paths.

**Comment by Arcanemagus** [comment]
The only potential issue I see with the caching (just by looking at what the specs are testing) would be the following scenario:

* User opens up Atom and loads a CSS file
* First time run of the lint, `cosmiconfig` caches the config
* The user sees that a rule is enabled that they don't like, so they edit the configuration and disable it
* Another lint is triggered with the same `cosmiconfig` instance

Will it check the configuration file(s) it found last time, see a modification, pick up the updated configuration, and return that, or is it a simple cache and it will just return what it found the first time?

**Comment by davidtheclark** [comment]
Hmm ...

> Will it check the configuration file(s) it found last time, see a modification, pick up the updated configuration, and return that, or is it a simple cache and it will just return what it found the first time?

That would nullify the file cache but not the directory cache, right? So you wouldn't pick up whether they create a *new* config that should be loaded instead, but only if they modified an *existing* config? If that's the case, then at least there'd be some caching that might help. If, however, you'd also want to pick up on new configs, then I think you'd need to turn off the cache completely, right?

**Comment by evilebottnawi** [comment]
@davidtheclark This gave me the idea, but why not speedup `stylelint` itself (save last linted files and compare modification time), as it does `eslint`, it is speedup then you use on `watch` files.

**Comment by Arcanemagus** [comment]
@evilebottnawi `eslint` uses a `.eslintcache` file to track their cache, that's something you have to be very careful not to cache too much.

@davidtheclark Ideally the cache should be transparent, working when nothing has changed, and updating if there is any change. If I was doing it I think I would make it:

* Not cache a "not found" result, this can hurt performance (down to the current state) in some cases but should be fine usually
* If a cached configuration is found, monitor the file(s) associated with it for updates or deletions, if any are found, invalidate the cache and generate a fresh configuration

That should cover the general cases I can think of, it's not quite a full cache since you still need to `stat` the config files, but you still have a cache of all the other `stat` calls. I've never implemented a cache like that before though so I'm sure I'm missing something here 😛.

**Comment by Arcanemagus** [comment]
I was just trying to think of a way the cache could be useful in the way `cosmiconfig` is being used there, and still utilizing the caching. If the caching is meant for a single process run over many files, that isn't really what `linter-stylelint` does, as it's more of many different runs on an individual process, that just happens to use a single `cosmiconfig`. As it only takes ~20 ms to run (on my system), it isn't that big of a deal to just disable the cache in `linter-stylelint`.

Either way, the changes to the API don't look like they would be that major to move to. And if `stylelint` exposes a method to get the configuration for a file then I wouldn't even have `cosmiconfig` in `linter-stylelint` 😛.

**Comment by davidtheclark** [comment]
@Arcanemagus: Seems like the *most* useful for linter-stylelint and related packages might be if cosmiconfig could have a watching mode ... sounds interesting. I'll look into it.

**Comment by davidtheclark** [comment]
@gucong3000 @Arcanemagus I'm working on this issue over in https://github.com/stylelint/stylelint/pull/1930.
