### ISSUE TITLE
Proposal for different changelog management

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1913]
The changelog is almost the only merge conflict we have, and we have it all the time. It's especially annoying when we have a few pull requests, one merges, and then all the others have to rebase. It's also annoying to need to remind people to add changelog notes, and to nitpick about their changelog notes not quite fitting the format, etc.

I propose that we no longer include changelog notes in PRs. Instead, when we merge a PR we can add a note to a wiki page. Then when we cut a release, we copy & possibly edit the notes & merge them into CHANGELOG.md.

What do you think?

**Comment by ntwb** [comment]
I agree, rebasing is not great.

ESLint have a tool [eslint-release](https://github.com/eslint/eslint-release#what-it-does), it's very similar to the [npmpub](https://github.com/MoOx/npmpub) we use here for stylelint, the main difference is it includes automatically creating and adding the changelog:

> 4 Calculates the next release version based on the commit message format of the changes since the last release
> 5 Updates CHANGELOG.md and commits the changes

Maybe we could look into automating it rather than manually wiki'ing it?

**Comment by davidtheclark** [comment]
@ntwb Personally I might rather manually do it, to avoid having to bug people about gettign the changelog format correct. Open to others desires, though.

**Comment by Arcanemagus** [comment]
Maybe instead of forcing a specific format, use labels to determine how it shows in the log? I've seen "semver-{major|minor|patch" labels on other projects, and if that alone wasn't enough I'm sure it could be expanded with more labels. With that you would just need to ensure each PR has the appropriate label, as well as a commit title that looks good enough to be in the change log.

**Comment by jeddy3** [comment]
> Instead, when we merge a PR we can add a note to a wiki page

I'd be up for trialling that approach. We can always try something else if it doesn't work out.

**Comment by ntwb** [comment]
Agreed, go the wiki road and see how that goes
