### ISSUE TITLE
Add "How do I disable a rule" to FAQ

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1922]
This question comes up all the time (e.g. [just now](https://twitter.com/andreysitnik/status/778911556872667136)). We should maybe even put it at the top of FAQ.

**Comment by evilebottnawi** [comment]
@davidtheclark sgtm, @stylelint/core maybe sometimes it seems to me would have been perfect to enter aliases as` eslint`: `off`, `warning`, `error`. It is more readable for human. What do all think?

**Comment by jeddy3** [comment]
Rules in stylelint are turned on by specifying a primary option. I don't those those aliases are applicable here.

**Comment by evilebottnawi** [comment]
@jeddy3 some people often write `false` and think what rule will be disable, but if we use `off`, it would not have introduced confusion

**Comment by jeddy3** [comment]
I see where you're coming from. However, the string `"off"` could be a primary option (which would turn a rule on). That's why `null`, and only `null`, is used to turn rules off. 

Likewise, we have severities as part of the optional secondary options so that users can define their own severities levels e.g. *advice*, *info* etc...

I think adding just an `"off"` alias for `null` would make things inconsistent.

The key thing to remember is that *rules are enabled by specifying a primary option in stylelint* (e.g. string, int, obj, bool or array). This is a different behaviour to eslint.

**Comment by evilebottnawi** [comment]
@jeddy3 okey, let's add `How do I disable a rule?` in FAQ on top.
