### ISSUE TITLE
Use Yarn

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2061]
Does anybody have any objections to using Yarn here? — which would basically just mean committing a Yarn lockfile?

**Comment by ntwb** [comment]
No objections at all, was on my to do list 👍

**Comment by Arcanemagus** [comment]
Be careful that it is generating a `node_modules` that actually works, I have a few projects where `yarn` can't be used due to bugs in their resolution of dependencies (`linter-stylelint` was one during the `table` mess 😛).

**Comment by ntwb** [comment]
Thanks @Arcanemagus, I'll read up a little more on this as I've got a good half to a dozen projects that I'm looking at to add Yarn support to 👍

**Comment by Arcanemagus** [comment]
Specifically the bug that has prevented me from using it in a few places is https://github.com/yarnpkg/yarn/issues/681.

**Comment by ntwb** [comment]
Thanks for that, I've subscribed to that issue, I don't have any cases currently that this would cause an issue, but thats more luck than anything, I'm frequently pinning packages in repos 👍

**Comment by ntwb** [comment]
https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

**Comment by ntwb** [comment]
Adding this here on the issue rather than #2129 as these issues should be addressed separately:

• After merging #2129 we should run "Delete all repository caches" via https://travis-ci.org/stylelint/stylelint/caches so that any _legacy_ cache folders in particular relating to our `master` branch are _flushed_.

• @greenkeeperio / @greenkeeperio-bot currently support Yarn, as such when a new PR is submitted by @greenkeeperio the PR will not include the related `yarn.lock` update, we'd have to manually add that to each PR. This is being discussed in https://github.com/greenkeeperio/greenkeeper/issues/314 and the tl'dr is "not anytime soon".

**Comment by ntwb** [comment]
See also https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.2sbh58tof, I may need to read this article a couple more times to fully grok the ramifications of the issues raised though it looks like if we use packages that _also_ use Yarn there are potential issues with semver conflicts that may occur.

**Comment by davidtheclark** [comment]
@ntwb 🤔 ... yeah, it may be that we're better off *not* using Yarn. Our installation and CI's would better match that of most users. We would avoid having to deal with any bugs. I'm also skeptical of adding another hot-new-thing into the mix, since I seriously regret our usage of Babel and am starting to wonder if I should regret our (partial) migration to Jest ... I'll let you make the call @ntwb: do you think we should switch, or stick with npm?

**Comment by davidtheclark** [comment]
@ntwb FYI, given #2131 and #2133, I am all for *not* using the shiny-and-new if we anticipate *any* troubles with it.

**Comment by ntwb** [comment]
Agreed, lets wait until Yarn is a little older and less shiny...

**Comment by ntwb** [comment]
I'm going to reopen this for consideration as I think Yarn has matured as has the ecosystem surrounding it now. With the launch of NPM 5, NPM will use _lockfiles_ by default, @Greenkeeper has also [added support](https://github.com/greenkeeperio/greenkeeper-lockfile) for lockfiles for both Yarn and NPM.

I'll invest some time over the coming days to dig around and take a closer look at what is required to be added so that we can support both Yarn and NPM 5.

p.s. NPM 5 is due to be released 30th May 2017

**Comment by jeddy3** [comment]
Is this a route we want to go down, or can we close this for now?

**Comment by ntwb** [comment]
Let's close this for now, npm 5 has some great improvements, so lets do that everywhere 😏
