### ISSUE TITLE
Add PR numbers to changelog?

### ISSUE THREAD

**Issue by Arcanemagus** [stylelint/stylelint#2091]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

It would be nice when reviewing the changelog if the PR's implementing each item were linked from the changelog, allowing easy viewing of where it was implemented, and what was changed. Obviously this isn't required but I thought I would suggest it 😉.

<details><summary>The rest of the issue template</summary>
> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

N/A

> How are you running stylelint: CLI, PostCSS plugin, Node API?

N/A

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

PR numbers in the changelog.

> What actually happened (e.g. what warnings or errors you are getting)?

No PR numbers in the changelog.

</details>

**Comment by jeddy3** [comment]
@davidtheclark I don't mind doing this, if you don't. I can see how it'd be helpful for @Arcanemagus and other stylelint tool maintainers. e.g.

- Fixed: false positives related to LESS detached rulesets ([#2089](https://github.com/stylelint/stylelint/pull/2089))

We'll need to use complete markdown URLs, rather than rely on github's autocomplete so that the changelog on the website works.

**Comment by davidtheclark** [comment]
🆗

**Comment by jeddy3** [comment]
I've updated the current item in `Head` in https://github.com/stylelint/stylelint/commit/d96c557805eaf2276250e3ab7e3cc3a0c464b17a
