### ISSUE TITLE
Error: Undefined rule font-family-no-duplicate-names

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#2112]
In `stylefmt` we use `stylelint.getConfigForFile()` to load configuration file. We hope that `rule Undefined` is just a warning, not an error.

https://github.com/morishitter/stylefmt/issues/237

**Comment by gucong3000** [comment]
Or, we can add a option, to ignore this kind of error.

**Comment by davidtheclark** [comment]
This is a design decision that I don't think we should change. It is important for users to know when they have entered a rule that does not exist.

I think that within `stylefmt` you should `catch` this error and deal with it as you wish. There is no need for us to build this option into stylelint because JavaScript provides a way to do it.
