### ISSUE TITLE
`no-unknown-animations` error when animation is defined in an imported file(s)

### ISSUE THREAD

**Issue by kartikm** [stylelint/stylelint#2363]
When animation is defined in less file(s) which is/are imported, stylelint still issues error: Unexpected unknown animation name (ie no-unknown-animations)

> What CSS is needed to reproduce this issue?

e.g.

```css
@import '../../widgets/common/ext.cx.common.less';
.cards.link {
	animation-name: card-show-animation;
```

This is defined in less file (eg: ext.cx.tools.card.less)  which is imported as a part of dependencies.

```css
/* Cards animation */
@keyframes card-show-animation {
	0% {
		opacity: 0;
		position: relative;
		top: 15px;
	}

	100% {
		opacity: 1;
		top: 0;
	}
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
        "extends": "stylelint-config-wikimedia",
        "rules": {
                "no-browser-hacks": null,
                "no-unsupported-browser-features": null
        }
}
```

> Which version of stylelint are you using?

`7.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

grunt stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

No warning.

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
>> modules/tools/styles/ext.cx.tools.instructions.less
>>  4:18  ✖  Unexpected unknown animation name "card-show-animation"   no-unknown-animations
....
.....
```

All code is available at: https://phabricator.wikimedia.org/diffusion/ECTX/browse/master/modules/ (under styles/ subdirs..)

**Comment by hudochenkov** [comment]
Thank you for reporting!

Stylelint doesn't compile preprocessors code. It doesn't import one stylesheet into another. So it doesn't know animation is declared in other file, because it only checks current file and looking for animations in that file.

I believe it's possible to create a [plugin](https://stylelint.io/developer-guide/plugins/), which will do imports by [`postcss-import`](https://github.com/postcss/postcss-import) and then check `no-unknown-animations` using [`stylelint.utils.checkAgainstRule`](https://stylelint.io/developer-guide/plugins/#stylelintutilscheckagainstrule) util.

**Comment by jeddy3** [comment]
@kartikm The [documentation states](https://github.com/stylelint/stylelint/tree/master/lib/rules/no-unknown-animations#no-unknown-animations):

> This rule considers the identifiers of `@keyframes` rules defined _within the same source to be known_.

So this rule is behaving as documented.

As @hudochenkov suggested, feel free to experiment with building on this rule within a plugin. This kind of experimentation is one of the reasons the plugin system was developed. Good luck!

**Comment by kartikm** [comment]
Thanks @hudochenkov and @jeddy3
