### ISSUE TITLE
property-whitelist

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#237]
I've been looking at implementing one of the simpler outstanding rules (thanks @jeddy3 for pointing me in the right direction), and `property-whitelist` looks like a good candidate.

If this has already been discussed then I'd be happy to implement it, however... it seems like a slightly odd rule so I'm wondering if there's a use-case for it?  Perhaps it could be left out until someone requested it?

**Comment by jeddy3** [comment]
> I've been looking at implementing one of the simpler outstanding rules (thanks @jeddy3 for pointing me in the right direction), and property-whitelist looks like a good candidate.

Good stuff :)

> If this has already been discussed then I'd be happy to implement it, however... it seems like a slightly odd rule so I'm wondering if there's a use-case for it?

We've not discussed this particular rule, but we did briefly discuss property-blacklist over here: https://github.com/stylelint/stylelint/pull/200#discussion-diff-32780332

We thought up a couple of, albeit very edge, use-cases. We ended up deciding to keep it in as:

1. It's a super simple rule that maybe some one will make use of it.
3. It compliments something more useful like `property-unit-blacklist` and creates a nice group.

There's probably even harder to think up a use-case for this, more restrictive, whitelist rule. But it might be worth throwing in for the reasons above, and also for symmetry? :)

Otherwise, feel free to tuck into any of the other rules :)
