### ISSUE TITLE
no-unsupported-browser-features plugin

### ISSUE THREAD

**Issue by ismay** [stylelint/stylelint#2428]
So the "no-unsupported-browser-features" rule is deprecated and should be moved to a plugin (see [here](https://github.com/stylelint/stylelint/blob/master/lib/rules/no-unsupported-browser-features/README.md)). I was wondering if there's already someone working on that. If not, I'd like to see if I can tackle it.

Any advice on the approach? I've read the [developer guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md), but feel free to let me know if there's anything else I should be aware of when creating this plugin.

**Comment by davidtheclark** [comment]
@ismay It's all yours! We've tried to write down everything we can think of in the developer guide — so just let us know if you have any additional questions. Also make sure to check the existing plugins as examples.

**Comment by ismay** [comment]
Ok cool, thanks!

**Comment by ismay** [comment]
@davidtheclark I'm considering whether to name the plugin `stylelint-doiuse`, or `stylelint-no-unsupported-browser-features`, what do you think? 

* `stylelint-doiuse` seems more discoverable and it might be easier to understand what it does for new users
* `stylelint-no-unsupported-browser-features` makes it very clear which rule it implements, but maybe when people don't know about that rule it'll require a little more effort to get that it implements doiuse

I'm leaning towards just stylelint-doiuse, but am wondering what you'd suggest.

**Comment by hudochenkov** [comment]
@ismay I don't think someone would think: “Is there any implementation of doiuse for stylelint?”. I suggest you to use `stylelint-no-unsupported-browser-features` because it's more clear what the plugin do. Also you can send PR to doiuse repository with link to your plugin. It will help with discoverability. And it'll help if someone has a question above :)

**Comment by ismay** [comment]
> I don't think someone would think: “Is there any implementation of doiuse for stylelint?”

Well that's the way I found the original rule actually, which is why I thought referring to doiuse directly might be useful you know?

**Comment by jeddy3** [comment]
@ismay It's great that you're porting this rules to a plugin!

> I'm considering whether to name the plugin `stylelint-doiuse`

I can see your reasoning. For context, I can explain the original name for you.

The stylelint's core rules follow [strict naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md). Plugin authors aren't obliged to follow the same conventions, but you can argue that consistency helps with the overall user experience.

For example, [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern) is a plugin that follows these conventions. The rule is _scoped_ to the _selector construct_, and checks the "bem-pattern" of it. The `-pattern` part of the name is aligned with other [`-pattern` rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md).

It could of been called `stylelelint-postcss-bem-linter` after the [PostCSS plugin it wraps](https://github.com/postcss/postcss-bem-linter). However, we decided that consistency with the stylelint naming conventions trumps exposing the name of the underlying library in the name of the plugin. 

The other argument is favour of sticking to this convention is that using a library like `doiuse` or `postcss-bem-linter` _is an implementation detail_. If `stylelint-selector-bem-pattern` was to move to another library then the name will continue to make sense as it describes, like all stylelint rules, _what it does_, rather than _how it does it_.

**Comment by ismay** [comment]
> Plugin authors aren't obliged to follow the same conventions, but you can argue that consistency helps with the overall user experience.

Definitely

> However, we decided that consistency with the stylelint naming conventions trumps exposing the name of the underlying library in the name of the plugin ... The other argument is favour of sticking to this convention is that using a library like doiuse or postcss-bem-linter is an implementation detail. If stylelint-selector-bem-pattern was to move to another library then the name will continue to make sense as it describes, like all stylelint rules, what it does, rather than how it does it.

Ok yeah, that makes a lot of sense. I'll keep the name as is then 👍  Thanks for the feedback!

**Comment by ismay** [comment]
Just released 0.1.0 of `stylelint-no-unsupported-browser-features`.

Repo: https://github.com/ismay/stylelint-no-unsupported-browser-features
Npm: https://www.npmjs.com/package/stylelint-no-unsupported-browser-features

Feedback is very welcome, let me know if there are any mistakes or other things that need to be fixed!

**Comment by jeddy3** [comment]
@ismay Looks great, thanks for that!

I've posted one little query in your repo: https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/6
