### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2518]
I've been using Prettier on several other projects, and loving it.

What do @stylelint/core think about using Prettier here, and removing the stylistic rules from our ESLint config?

If we want to do this, is there anybody who is interested in learning about Prettier and leading the way? (If not, I can do it.)

**Comment by hudochenkov** [comment]
I think nothing about Prettier, because have never used it. But if we agree to use it, we should postpone it until `v8` merged into `master`. For [the very reason](https://github.com/stylelint/eslint-config-stylelint/issues/25) we're postponing the new version of our ESLint config.

So ideally, if we need Prettier, we should merge `v8` into `master`, then tweak ESLint config and Prettier at kind of the same time.

**Comment by jeddy3** [comment]
> I've been using Prettier on several other projects, and loving it.

That's a good enough recommendation for me! :)

There are definitely few bits of the code base that could use a bit of prettifying after the "great babel removal", and consistency going forward is always a plus.

> postpone it until v8 merged into master

SGTM.

**Comment by ntwb** [comment]
Prettier came up in a meeting last night, I'll go have a read and report back 😄

**Comment by jitendravyas** [comment]
Are we talking about removing only those formatting rules from stylelint which can be auto fixed by Prettier?

**Comment by jitendravyas** [comment]
@evilebottnawi ok. By the way just wanted to share that I have actually removed all formatting related rules from my `.stylelintrc` I use at work. I think devs should not waste the time of formatting code manually. I have made my own list of stylelint rules and marked them all rule which I think are purely formatting related and have removed them. For autoformatting, I will be either using **Prettier** or **Scssfmt** and now will also check `stylelint --fix`. I tried **stylefmt** too but it had some problems so not going to use it.

**Comment by evilebottnawi** [comment]
@jitendravyas in near future I will try to implement `stylelint-config-prettier` then `stylelint-plugin-prettier` and your can use `stylelint` as one tool and `prettier` as plugin `stylelint`, it is allow using formatter and linter together.

**Comment by barraponto** [comment]
I don't think this issue should hold 8.0.0 back. Can we move it to 9.x?

**Comment by jeddy3** [comment]
> I don't think this issue should hold 8.0.0 back. 

I agree. I believe it's a small issue that won't take long, though. However, if it does prove to be the final blocking issue then we can consider postponing it.

> Can we move it to 9.x?

It's an internal code change and not related to semver. It's a change that will likely conflict with all the pending PRs. As such, it was added to the `8.0.0` milestone because we anticipate this will be the time when there will be _the least_ number of pending PRs. Getting it in around the `8.0.0` release will save us time in the long run.

**Comment by iki** [comment]
@evilebottnawi it's available: https://github.com/shannonmoeller/stylelint-config-prettier
