### ISSUE TITLE
Feature request: no-trim-semicolon for sass

### ISSUE THREAD

**Issue by mwawrysz** [stylelint/stylelint#2593]
Is there any way to have option like no-trim-semicolon - I can't find that in rules?

**Comment by hudochenkov** [comment]
Could you explain, please, what you want to check?

**Comment by mwawrysz** [comment]
For sass is useful for me to don't use ';' at the end of line

Example:
```
.class-name 
    font-size: 16px
```
It always require semicolon at the end -> I am looking for the rule to disable this.

**Comment by hudochenkov** [comment]
Could you, please, use issue template? We need that information.

Also we doesn't support Sass (indented based syntax).

**Comment by mwawrysz** [comment]
If there is no Sass support I don't know if that will make any sense now :)

But thank you anyway

**Comment by ntwb** [comment]
@mwawrysz, there is a proposal open to add SASS in #2486 and #2503

If there is any way you could help out in those issues that would I'm sure help us help you 😄 

The reason we ask people to use the issue template is because we've a diverse set of contributors from all around the world and whose first language is not necessarily English, as such adding code examples per the issue template is more often than not a great way to get around issue of language.

**Comment by mwawrysz** [comment]
Thank you very much for that info :+1:  

I have to dive deeper in that :)
