### ISSUE TITLE
Newlines on Windows screwy

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#264]
I don't suppose either of @stylelint/owners have Windows machines you work from regularly?

A co-worker of mine reported that all the newline rules were firing like crazy on his Windows machine. I'm assuming it's because of the different newlines Windows can (does always?) produce.

If neither of you have Windows I should be able to go into work early or something and use a Windows machine to troubleshoot.

Or if anybody reads this but *has not been having this trouble on Windows*, please chime in!

**Comment by jeddy3** [comment]
I've solely used a windows machine since the beginning :)

I remember the newline rules were a bit screwy for me about a month ago -- I think when I first ran the linter against the stylelint.io CSS . I can't remember what happened or what I did, but the issue went away for me.

I'll have time to try to replicate the issue on Sunday. I think it had something to do with what line ending option was enabled in my code editor.

Can you co-worker list out which exactly which of the rules (they are using) are misbehaving? It'd be useful to see which, if any, of the newline rules are behaving and which aren't.

**Comment by MoOx** [comment]
That's weird because appveyor run tests on Window...
Maybe that might help https://github.com/stylelint/stylelint/blob/master/.gitattributes

**Comment by davidtheclark** [comment]
Yep, I bet you both nailed it: it depends on the line ending settings in the editor, and git will control them for the repo. I will get more details at work.

**Comment by ntwb** [comment]
You've an [`.editorconfig`](https://github.com/stylelint/stylelint/blob/master/.editorconfig) in the repo, get an [Editor Config](http://editorconfig.org/#download) plugin for your editor.

**Comment by davidtheclark** [comment]
I can confirm that the problem is we didn't write rules or tests to check for `\r\n` in addition to `\n`. Slipped the mind.

I'll spend some time this weekend working on that ... and if anybody wants to help out, go for it.

**Comment by davidtheclark** [comment]
This kind of makes me want to die. Has this problem already been solved elsewhere? Or should we just demand that users fix their line endings? I really don't want to write hundreds more tests and add weird logic to accommodate this ... Do we have no other choice?

**Comment by davidtheclark** [comment]
Would there be any problem with simply normalizing newlines in the source (https://github.com/sindresorhus/normalize-newline), so that the linting rules only have to worry about `\n`?

**Comment by MoOx** [comment]
We cannot normalize newlines because we don't play with string. We should probably handle `\r` if we want to avoid any problem for the users... Bad UX if we ask them to handle that themselves :/
