### ISSUE TITLE
browser hacks rule

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#265]
@ben-eb mentioned on Gitter that we could use https://github.com/ben-eb/stylehacks to create a rule like our no-vendor-prefixes rules that checks for style hacks and warns if you are using any that you shouldn't be.

**Comment by ben-eb** [comment]
Current support is a little limited; would like some more hacks added to the database. But I see this as a win-win for both of our projects. :smiley:

**Comment by jeddy3** [comment]
stylehacks looks great, but I'm wondering whether we should included this is not.

You see, if we're to follow the convention of tying each rule to a specific *thing* (e.g. `declaration-no-leading-underscore-hack`) then we'd need 7 new rules to start with, and more as new ones are added to stylehacks. 

Perhaps, instead, we can see stylelint and stylehack as companion projects and we can add a section to readme accordingly e.g:

---

Stylelint works nicely with the following tools:

* stylehack - Detect browser hacks from CSS files.

---

That way people can just include in their postcss processors list if desired.

Thoughts?

**Comment by ben-eb** [comment]
I'm happy to include a related section if you are. I just thought bundling might be more convenient. :smile:

**Comment by davidtheclark** [comment]
@jeddy3: We could make a rule like `no-browser-hacks` and bend the `no-` convention just barely to allow it to accept a browserlist -- but by default all browser hacks would trigger a warning, so by default you would not have to pass anything.

**Comment by MoOx** [comment]
A note in the README seems good to me.

**Comment by jeddy3** [comment]
> I'm happy to include a related section if you are.

Definitely :)

> We could make a rule like no-browser-hacks and bend the no- convention

My concern is that we won't just be bending this convention, but four:

1. `no-` rules don't take options.
2. rules are tied to a *thing*. The only rules that aren't some whitespace rules (e.g. `no-eof-whitespace` and `indentation`), which a tied to the stylesheet itself.
3. no default values or behaviour.
4. all rules are turned off by default i.e. if a user has the `no-browser-hacks` rule turned on and new internal-rules are added to `stylehacks` those internal-rules will be automatically turned on for the user when we updated our bundled `stylehacks`.

We've been extra careful to establish and keep these conventions because we want using the rules to be as predictable as possible (as well as keeping the documentation concise).

I'm keen to keep this going for as long as possible, but I'm aware at some point we might have to bend the conventions. However, this feels like a odd place to break with four of them when a user can add the plugin to his/her pipeline so easily.

I figured I'd quickly write up this up as a way of an explanation for @ben-eb. I don't want it coming across as an arbitrary stance for something that seems, at first, like a trivial addition :)

**Comment by davidtheclark** [comment]
You won me over :)

Let's put a note in the README.

**Comment by ben-eb** [comment]
Yep, I'm happy with that. I'll update stylehacks when I get in. :smile:

**Comment by ben-eb** [comment]
Done: https://github.com/ben-eb/stylehacks#related

**Comment by jeddy3** [comment]
Thank you :)
