### ISSUE TITLE
[New rule Idea] Rule to remind to add :focus selector to every :hover for keyboard accessibility.

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2650]
For this purpose https://github.com/postcss/postcss-focus

**Comment by jeddy3** [comment]
I think this is a best handled as a plugin as it's a specific and shifting best practise, rather than configurable rule.

@jitendravyas Perhaps you would like to create your own plugin _pack_ called `stylelint-a11y`, which would group together accessibility plugins?

**Comment by jitendravyas** [comment]
I would really like to start developing stylelint plugins and formatter but current docs are not very clear to me and I'm JS noob too.

**Comment by jeddy3** [comment]
I'd recommend looking at some of the existing plugin (packs). [`stylelint-order`](https://github.com/hudochenkov/stylelint-order/) is a good place to start. 

Within stylelint, [`selector-pseudo-class-case`](https://github.com/stylelint/stylelint/blob/master/lib/rules/selector-pseudo-class-case/index.js) is a fairly simple rule that deals with pseudo-classes. You could use that as a foundation for this `:focus` plugin.

Then it'd be great if you could send a PR that improves the documentation in stylelint based on your experiences.

**Comment by jitendravyas** [comment]
Thanks for the direction.

**Comment by jeddy3** [comment]
I still believe a 3rd party `stylelint-a11y` plugin is the appropriate way forward. It's an exciting and worthwhile endeavour for someone!  Our approach has historically been to push the experimentation of rules of unknown complexity to plugins, _with the prospect of promoting them to core if they fulfil the [criteria for inclusion](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#criteria-for-inclusion)_. @mgifford Would you like to champion this? You appear to have a wealth of a11y experience!

There's a nice precedent for an a11y plugin in the ESLint world: [`eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y).

> This is also about best practices. You might choose to not address keyboard only users, but you certainly should anticipate that you have some. This isn't a fringe issue.

Quite a few best practices can be enforced at the configuration level. I believe there's also an opportunity here for someone to publish an accessibility-focus configuration (e.g. `stylelint-config-ally`). 

stylelint also includes [multiple points of extension](https://github.com/stylelint/stylelint/blob/master/VISION.md#extensible) so that as many use cases as possible can be provided for. So, I like to think of the built-in rules as a starting point that the community can build on, rather than a definitive list of what the tool can do.

> I do not think that somebody will support such plugins, maybe it is good implement this in core as `a11y` rules. 

I don't quite understand the reasoning here. If there's no one willing to the support the work, then the rules will go unwritten or unmaintained regardless of where they live, within core or outside of it. It's also easier to promote plugins to core than it is to demote built-in rules to plugins. I believe we've leant that lesson the hard way already.
