### ISSUE TITLE
Add ignoreRules: [] to max-nesting-depth

### ISSUE THREAD

**Issue by nirazul** [stylelint/stylelint#2696]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

**Feature request:** 
Add: `ignoreSelectors: [".my-custom-selector"]` for `max-nesting-depth`
I often find myself using `& {}` as a means to visually encapsulate some rules. As this counts towards the limit of `max-nesting-depth` I sometimes need to disable this rule, which is a bit annoying.
This could also be useful to exclude `::after` and `::before` elements as these need to be nested (except you opt for repeating their parent selector).

> Which rule, if any, is this issue related to?

`max-nesting-depth`

> Which version of stylelint are you using?

`7.12.0`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Not necessarily, although I have in mind to exclusively use it with the SCSS selector `&`

**Comment by jeddy3** [comment]
This seems like a valid use case. It'd be in line with the existing [`ignoreAtRules` option](https://github.com/stylelint/stylelint/tree/master/lib/rules/max-nesting-depth#ignoreatrules-regex-string). 

I believe it'd be the first rule to ignore _rules based on their selector_. So, we don't have a precedent for the name. Choices include:

- `ignoreSelectors: []`
- `ignoreRules: []`
- `ignoreRulesBySelector: []`
- ...

I favour `ignoreRules` for its parallels with `ignoreAtRules`. In `ignoreAtRules` the at-rule itself isn't check, but rather the  _name_ of the at-rule is used to ignore the at-rule. In `ignoreRules` the rule itself isn't check, but rather the selector is used to ignore the rule.

**Comment by Nirazul** [comment]
Personally I favour `ignoreSelectors` as it is the most intuitive, but I have no problem with `ignoreRules` as your reasoning makes totally sense and it's in line with `ignoreAtRules`.

What ran through my head just now: Why make the difference between rules and at-rules? Does it make a difference when writing ignore statements for it? From the user perspective, I'd say no. Probably, when it comes to code logic, there's a difference.

**Comment by jeddy3** [comment]
> Why make the difference between rules and at-rules?

Do you mean why have separate options for at-rules and rules? From a user's perspective, I think it's helpful to have the consistency across rules of explicitly tying `ignore*` options to specific constructs (or type of construct) e.g. `ignoreNamespaces` and `ignoreTypes` in [`selector-no-unknown`](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-type-no-unknown#ignorenamespaces-regex-string).

> Probably, when it comes to code logic, there's a difference.

Yes, that's right. The above aligns with the PostCSS API of being able to [walk through](http://api.postcss.org/Container.html#walkAtRules) each of these constructs.

Let's wait a little while more to see if there any further contributions to the discussion. Otherwise, I'll label this up as ready to go.

**Comment by jeddy3** [comment]
Oops, I forgot about this in all the `8.0.0` action.

I'll label up as "help wanted". Let's go with `ignoreRules: []`.
