### ISSUE TITLE
Add support for disableFix to built-in rules

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2708]
In this update Stylelint enabled experimental `--fix` support for some rule https://github.com/stylelint/stylelint/releases/tag/7.11.0

Will all rule be fixed together?

What if I want to auto fix only `color-hex-case` in my codebase?

**Comment by jeddy3** [comment]
> Will all rule be fixed together?

Yes, if you turn on rules in the config and use the `--fix` option stylelint will try to automatically fix the errors for those rules.

> What if I want to auto fix only color-hex-case in my codebase?

@stylelint/core Should we add [`disableFix`](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin) to the built-in rules?

**Comment by ntwb** [comment]
If you have rules configured to `error` then why would you not want them to be fixed?

For example, if your config has 20 rules configured to `error` and you only want to fix a single rule such as `color-hex-case` then adding `disableFix` to the remaining 19 rules to your config doesn't seem like an ideal workflow 🤔

**Comment by jeddy3** [comment]
> If you have rules configured to error then why would you not want them to be fixed?

Good point. @jitendravyas Can you please tell us more about your use case?

**Comment by evilebottnawi** [comment]
Also we can add /*stylelint-fix-enable [rule] */ and  /*stylelint-fix-disable [rule] */.

**Comment by ondrejs2** [comment]
@jeddy3 Hello, I have same/similar problem -> my **use case**:

I'm using **LESS**. In the **.stylelintrc** config file I extends "**stylelint-config-standard**" and in plugins I have only "**stylelint-order**". Everything works fine, stylelint is linting and via **--fix** feature and thanks to the "**stylelint-order**" plugin it's autofixing the order of properties (which is most important thing for me to autofix).

BUT the only one huge problem which I can't solve so far is that **--fix** _strips semicolons from mixins_ (as it is already reported - https://github.com/stylelint/stylelint/issues/2619). I've tried to use `// stylelint-disable-next-line` and all other stylelint's disabling comments as a work around but unfortunately as you write in the https://stylelint.io/user-guide/cli/ -

> It currently does not respect special comments for disabling stylelint within sources (e. g. /* stylelint-disable /*). Autofixing will be applied regardless of these comments.

So I would be glad if the **--fix** feature _respects stylelint's disabling comments_ or if there would be any other comment that could _turn off/disable --fix feature per line/block_ - e.g. `/* stylelint-fix-disable-next-line */` or something similar.

Do you have any idea how I could solve this problem? Or do you plan to:
- support standard already existing disabling comments in the **--fix** feature?
- add a new disabling comments for the **--fix** feature?
- support standard LESS syntax (including mixins)?

I didn't find any other possible solution to get it works for people using LESS so I would be really happy for any idea or advice how to solve it.

Thank you for your reply ;-)

**Comment by jeddy3** [comment]
> Do you have any idea how I could solve this problem?

@ondrejs2 Thanks for offering to help out.

> support standard already existing disabling comments in the --fix feature (#2643)?

The core contributors are just a handful of people who contribute to stylelint in their spare time.  Also, it seems to be a non-trivial feature, so any help moving that issue forward would be appreciated (ref #2643).

> add a new disabling comments for the --fix feature?

I suggest we only revisit this once the existing disabling comments work, as we might discover that it has become a redundant request.

> support standard LESS syntax (including mixins)?

I don't believe any of the core contributors use Less, therefore having someone else champion Less syntax support would be great (ref #2619). Fixing the mixins might be dependent on updating postcss-less to the latest version, so a prerequisite to this work might be https://github.com/stylelint/stylelint/pull/2702. Helping, if possible, with that issue might be a good place to start.

There's a [Working with rules](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) section within the [Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide.md). The section on [Fixing bugs](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule) should hopefully be enough to get you started with the code base.

It feels like adding a `disableFix` feature to the built-in rules is to work around these shortcomings. As such, I'm going to close this issue so that further discussions can happen in the relevant two individual issues (#2619 & #2643).
