### ISSUE TITLE
Can I fork Stylelint website and customize it to use it within an organization?

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2723]

**Comment by evilebottnawi** [comment]
@stylelint/core our site use `MIT`?

**Comment by jitendravyas** [comment]
Yes I guess https://raw.githubusercontent.com/stylelint/stylelint/master/LICENSE but I don't know what does it mean in simple english

**Comment by evilebottnawi** [comment]
@jitendravyas MIT allow to fork and contribute for own goal. But i don't see license for stylelint site, i think we use everywhere MIT license for all `stylelint` org repos, but need clarify this.

**Comment by jeddy3** [comment]
> i think we use everywhere MIT license for all stylelint org repos,

Yes.

>  But i don't see license for stylelint site,

Added.  

> but I don't know what does it mean in simple english

As @evilebottnawi  said, MIT allow to fork and contribute for own goal _as long as the license remains intact_:

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Having said that, if there are improvements you think could be made to the site, please open issues in the [stylelint.io issue tracker](https://github.com/stylelint/stylelint.io/issues) so those improvements can benefit all stylelint users rather than just those inside your organisation.

**Comment by jitendravyas** [comment]
My aim is not an improvement to the existing site but I just want to use a reference withing organisation. I want to remove everything except the rules list and details, which we use in our `.stylelintrc`

**Comment by ntwb** [comment]
I would have thought linking to the relevant sections of stylelint's existing documentation would be easier, it would also mean there was no maintenance on your behalf either /shrug
