### ISSUE TITLE
New semver policy

### ISSUE THREAD

**Issue by MattDiMu** [stylelint/stylelint#2756]
The new semver policy according to the release notes (recommendation to use ~ instead of ^) is imho confusing: In semantic versioning minor releases should [not break the build](https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers) ( see [semver.org](http://semver.org/) as well).

Package Managers like npm or yarn rely and on this and by default add the dependency using the carrot "^". People should simply run "npm install stylelint --save-dev" or "yarn add stylelint --dev" and have the recommended dependency string in package.json by default, instead of having to adapt it manually afterwards.

Steps to reproduce:

1. npm init (in empty directory)
2. npm install stylelint --save-dev
3. Open package.json, where you will see something like 
```
  "devDependencies": {
    "stylelint": "^8.0.0"
  }

```

**Comment by ntwb** [comment]
The issue here is striking a balance in stylelint being able to release _patch_, _minor_, and _major_ releases in a sane manner that works for both stylelint, the stylelint team and the people and packages that depend upon it.

The stylelint policy is a slight adaptation of the existing ESLint policy [here](https://github.com/eslint/eslint#semantic-versioning-policy), it to has the same recommendation:
> _"According to our policy, any minor update may report more errors than the previous release (ex: from a bug fix). As such, we recommend using the tilde (`~`) in `package.json` e.g. `"eslint": "~3.1.0"` to guarantee the results of your builds."_


As we do here https://github.com/stylelint/stylelint#semantic-versioning-policy:
> _"According to our policy, any minor update may report more errors than the previous release (ex: from a bug fix). As such, we recommend using the tilde (`~`) in `package.json` e.g. `"stylelint": "~7.2.0"` to guarantee the results of your builds."_

If stylelint (or ESLint) were to fix a bug in a rule without the policy above stylelint would be pretty much limited to only ever releasing _major_ versions as per _semantic version_ policy only _major_ releases should break a build. 

To date stylelint has released 111 releases, 8 _major_ releases, ~50 _minor_ releases and the remaining are _patch_ releases.

Being able to release a bug fix without having to wait for a _major_ release or having to be a _major_ release is a trade-off, we try not to break people's builds but being a linter by it's very nature of what a linter does it's extremely difficult to ever ship a fix without breaking _someones_ build.

**Comment by Arcanemagus** [comment]
To think about it another way, this policy is a balance between the strict interpretation of [Semver](http://semver.org/) which _only_ applies to the exposed API, and how people actually use the linter.

The way package managers install packages assumes that you are utilizing the package directly in your code, in which case `^` is the correct range, for tools though you should probably be a bit stricter in your definition of desired versions.

----

If you wanted to get _super_ technical, according to Semver since adding new rules isn't changing [the API](https://stylelint.io/user-guide/node-api/) most of the minor releases in this project _should_ have been patch releases 😆.

**Comment by MattDiMu** [comment]
@ntwb Thx for the rapid response and the explanation! While I understand the reasons for this and eslint's decision, I still feel like this is not a good practice, as it differentiates from the well known and established semver policy.

There is always the possibility of a change to break the build, even a bugfix. To have certainty, that two different environments (developers or CI) create the same result, it's necessary to lock the dependencies anyway (using yarn.lock or package-lock.json). semver is only a rough approximation, whether a dependency upgrade will work "out of the box" or not.

So what are the use cases for upgrading a package and using the version defined in the package.json?
1. It's a devDependency and the developer is eager to upgrade to the latest version available (and willing to spend some time adapting the rules/code)
2. It's a devDependency and he simply wants the few "safe" upgrades he may get without spending much time. In this case he probably doesn't want any breaking changes just by raising the minor version.
3. It's a dependency and the user is building some sort of devtool himself, that uses stylelint. In this case he probably doesn't want different behavior without upgrading the major version.

At least these are the 3 use cases I've had in the past. I've simply never upgraded to a breaking version somewhere in the middle. All three cases may be mitigated by using the ~, but what's the significant benefit, that justifies, that this user has to read stylelints interpretation of semver and adapt package.json manually after installing the dependency?

Btw. established standards have the advantage of users being able to make some predictions about how the products implementing them behave and very often following a subpar standard is better than not following it and giving false impressions.

Having 50+ Versions is not necessarily bad. I don't see any drawbacks. Mozilla Firefox is at v54, while Google Chrome is at v59. A large version number would only show, that stylelint is very actively developed :)

**Comment by ntwb** [comment]
@MattDiMu As @Arcanemagus has mentioned, technically as we're not breaking the API _most_ releases of stylelint should have been _patch_ versions, <sarcasm>oh the joy that would have generated</sarcasm>

I don't see _major_ versions as a sign of an _actively developed_ project, as I stated we've 111 releases thus far that include _major_, _minor_, and _patch_ releases.

_I'm going to close this issue as we'll be keeping our semantic version policy as is for now, happy to continue discussion though_

**Comment by jeremyBanks** [comment]
Your versioning policy makes sense for this product, but calling it semver and saying "We follow semantic versioning", is incorrect and misleading.

Semantic Versioning has a *specific meaning*, as defined in the document you reference. You are explicitly *not* using semantic versioning. You have good reasons, but it would be better if the documentation was precise about this: call it a "versioning policy" not a "semantic versioning policy".
