### ISSUE TITLE
Update to postcss-selector-parser 3

### ISSUE THREAD

**Issue by ben-eb** [stylelint/stylelint#2757]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request (dependency upgrade). I've done a [pre-release of the new 3.x code](https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0) and as it is breaking a few things I wanted to get some feedback before I land 3.0.0 for real. In my use case it performs well if not better than expected, but stylelint uses postcss-selector-parser much more extensively.

Note that we now can accept PostCSS `rule` nodes and will throw a `CssSyntaxError` when the parser chokes on invalid syntaxes. I hope this provides a better end-user experience. 😄 

Your feedback is important to me! Thanks.

> Which rule, if any, is this issue related to?

n/a

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

n/a

> Which version of stylelint are you using?

`8`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

n/a

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

n/a

> What did you expect to happen?

n/a

> What actually happened (e.g. what warnings or errors you are getting)?

n/a

**Comment by jeddy3** [comment]
@ben-eb Firstly, thanks for your continued work on `postcss-selector-parser`. Your selector parser invaluable to stylelint.

An initial test run using the pre-release gives:

```
Test Suites: 5 failed, 261 passed, 266 total
Tests:       226 failed, 12692 passed, 12918 total
Snapshots:   6 passed, 6 total
Time:        135.296s
Ran all test suites.
```

Those failing suites are for:

- `"selector-attribute-brackets-space-inside"`
- `"selector-attribute-operator-blacklist"`
- `"selector-attribute-operator-space-after"`
- `"selector-attribute-operator-space-before"`
- `"selector-attribute-operator-whitelist"`

I suspect this due to the new attribute selector parsing and whitespace handling. I'm hoping it'll be some minor changes at the stylelint end to fix compatibility.

Unfortunately, I personally doubt I'll be able to take a deeper look into this for a couple of weeks as I'm away. @evilebottnawi has labelled has correctly labelled the issue as `help wanted`, so hopefully someone will some free time to pick this up.

**Comment by ben-eb** [comment]
Any joy?

**Comment by hudochenkov** [comment]
@ben-eb Sorry, Ben. It's a vacation/relocation period. I'm afraid no-one had a chance to look at it.

**Comment by ntwb** [comment]
I've just tried looking at this but I can't seem to get `v3.0.0-rc.0` working at all

To test I'm using:
```shell
npm install postcss/postcss-selector-parser#v3.0.0-rc.0
+ postcss-selector-parser@3.0.0-rc.0
added 2 packages, removed 1 package and updated 1 package in 5.428s
```

It appears as if `v3.0.0-rc.0` is installed correctly:
```shell
npm list --depth=0 | grep postcss-selector-parser
├── postcss-selector-parser@3.0.0-rc.0 (github:postcss/postcss-selector-parser#a7efd748c0d5fc79563e5ea6fc13fe5161ddd249)
```

Then running `npm test` results in:
```shell
Error: lib/utils/parseSelector.js:4
  4: const selectorParser = require("postcss-selector-parser");
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^ postcss-selector-parser. Required module not found
```

**Comment by ben-eb** [comment]
@ntwb Strange, we use it in cssnano v4.0.0-rc.2. 😕

**Comment by ntwb** [comment]
So today it decided to work for me /shrug 

Anyways, #2828 is a WIP branch to look at and investigate any issues

**Comment by ai** [comment]
Any updates? I can find person to do it. I just need extaclty plan.

**Comment by jeddy3** [comment]
> Any updates?

No one of the team has found the time to work on this much, I'm afraid.

> I can find person to do it.

That would be fantastic!

> I just need extaclty plan.

There is a minor WIP PR (#2828), but an external contributor can quickly replicate those changes in their own PR. The plan would be to update the version of `postcss-selector-parser` and then work through [the 5 failing test suites](https://github.com/stylelint/stylelint/issues/2757#issuecomment-316075568) and patch up the failing rules.

**Comment by EECOLOR** [comment]
@ben-eb I tracked down 2 issues using the method descibed by @jeddy3 both of them were (to my naive knowledge) problems in the parser.

I suggest you run the tests yourself to check and see if the other problems are also due to parsing. Those problems you can fix yourself. Any remaining problems can be reported here and picked up by a contributor.

**Comment by ai** [comment]
@EECOLOR maybe you can post this issues here? Or step-by-step instructions how reproduce them?
 @ben-eb just changed his job and a little busy right now.

I can ask my friends to fix issues, but they are open source newbies and need step-by-step instructions.

**Comment by EECOLOR** [comment]
@ai The thing is that the ones I found are issues in the `postcss-selector-parser` package. Where @ben-eb seems to be the only contributor.

We seem to be locked into a cyclic dependency here, the `cssnano` projects (also from @ben-eb) is waiting for stylelint to depend on a new version of `post-selector-parser`.

Step by step instructions to find the problems are:
- Create a local clone of stylelint
- Change the version in `package.json` to `^3.0.0-rc.0`
- Run `npm install`
- Run `npm run watch`
- Copy the name of a failing suit
- Press `p` and enter the name
- Find out if the problem is a regression in the parser

**Comment by jeddy3** [comment]
@EECOLOR Thanks for digging into this issue. I was also able to confirm your two issues: https://github.com/postcss/postcss-selector-parser/issues/118 & https://github.com/postcss/postcss-selector-parser/issues/119

Regarding https://github.com/postcss/postcss-selector-parser/issues/118:

> `[title ~= "flower"] {}` result in the operator being parsed as `~=  ` (a space at the end)

I don't know whether the change in the parser behaviour is intentional or not. However, we can address this at the stylelint end by [simply trimming whitespace around the operator](https://github.com/stylelint/stylelint/pull/2828/commits/e583845af2bb3f9540ba4d495c82c58eae83bd64).

Regarding https://github.com/postcss/postcss-selector-parser/issues/119:

> `[class^=#{$variable}] {}` result in the value and `raws.unquoted` being parsed as `#{`

I believe this might be a mistake at the stylelint end as we've assumed postcss-selector-parser can parser non-standard variable interpolation. I don't believe this is a documented feature of postcss-selector-parser. Everywhere else we use one of the `isStandardSyntax*` utils to ignore non-standard syntax before passing along the CSS to `postcss-selector-parser`. We [can bring the `selector-attribute-quotes` rule inline](https://github.com/stylelint/stylelint/pull/2828/commits/5a9af8cbf01d21c0938c632bb5bb768c329a69d2) with the other rules, and ignore non-standard syntax.

@ai If making these changes in stylelint helps facilitates the next release of postcss-selector-parser, then I think we should go with them. We can iron out any kinks later down the line.

**Comment by EECOLOR** [comment]
@jeddy3 Thanks for your reply, I understand where you're coming from. I myself have 0 knowledge about css.

That said, from a naive point of view, a parser that generates a node called `operator` and fills it with something that contains a space is faulty. If we accept this behavior from parsers the world will not be a better place.

About the second issue. If the parser does not accept such constructions, my opinion is that it should report an error instead of returning a partial value as a success.

The fact that the previous version of the parser supported these cases makes me think this is a regression. In any case, I think it would serve the community better to fix the problems in the selector.

**Comment by jeddy3** [comment]
> That said, from a naive point of view, a parser that generates a node called operator and fills it with something that contains a space is faulty.

That's a valid point.

> About the second issue. If the parser does not accept such constructions, my opinion is that it should report an error instead of returning a partial value as a success.

Also a good point. I believe the parser does report an error in other similar scenarios, and so having the behaviour consistent would be ideal.

> In any case, I think it would serve the community better to fix the problems in the selector.

I agree. 

However, as is usually the case, I think it comes down to time and skills. It would be fantastic if there was someone with the free time and skills (or enough free time to learn the skills) to help with postcss-selector-parser. If there isn't, then temporarily working around the issues at the stylelint end might help with the release of cssnano. Which would benefit the community, at the cost of a little debt in this project.

**Comment by EECOLOR** [comment]
@jeddy3 If you look at the [dependents](https://www.npmjs.com/browse/depended/postcss-selector-parser) of the `postcss-selector-parser` you see that shipping a version of it now affects quite a lot of libraries. In fact, a lot of the cssnano plugins depend on it.

So I think the only option is to fix the issues.

@ben-eb I was told you are busy, could you give a status update? Even if we got you help in fixing the issues, would you be able to release a new version of the library?

**Comment by jeddy3** [comment]
>> That said, from a naive point of view, a parser that generates a node called operator and fills it with something that contains a space is faulty.

> That's a valid point.

I dug a little deeper and it [looks like](https://github.com/postcss/postcss-selector-parser/commit/22d8a924e56e52bd5e19528e3b2a735298f7fd74#diff-d20545ea3d900168f006b63ba2e6b4f2L219) this is the intended behaviour. Which if fine in stylelint as we can work with that behaviour.

> So I think the only option is to fix the issues.

I'm not sure we can deal in absolutes on open source projects which rely on people giving up their free time. So, I'm making suggestions what we can do in stylelint to help out. Hopefully, something comes together though :)

**Comment by EECOLOR** [comment]
@jeddy3 yeah, I just noticed the same thing as well:

```
test('spaces in attribute selectors', 'h1[  href  *=  "test"  ]', (t, tree) => {
    t.deepEqual(tree.nodes[0].nodes[1].attribute, '  href  ');
    t.deepEqual(tree.nodes[0].nodes[1].operator, '*=  ');
    t.deepEqual(tree.nodes[0].nodes[1].value, '"test"  ');
    t.truthy(tree.nodes[0].nodes[1].quoted);
    t.deepEqual(tree.nodes[0].nodes[1].raws.unquoted, 'test');
});
```

The behavior is indeed known. It is unclear it was intentional or driven bij de the design of parser which is, in it's current state (I am not judging), incapable of doing what I (naively) expected. So in order to answer this we need @ben-eb.

**Comment by EECOLOR** [comment]
I just checked [the CSS grammar](https://www.w3.org/TR/CSS21/grammar.html), it states the following for attribute:

```
attrib
  : '[' S* IDENT S* [ [ '=' | INCLUDES | DASHMATCH ] S*
    [ IDENT | STRING ] S* ]? ']'
```

This means that spaces should not be part of the attribute, operator or value.

**Comment by jeddy3** [comment]
@EECOLOR Thanks for digging deeper. 

I think we might need to sit on this issue for a while until a way forward becomes clear.

**Comment by EECOLOR** [comment]
For everyone watching this issue. @chriseppstein has made a major change to the post-css-selector parser (https://github.com/postcss/postcss-selector-parser/issues/121) that will fix a few of the issues mentioned in this thread.

Seems the train is moving again 😄

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2984
