### ISSUE TITLE
Can I add an exception for Shopify liquid?

### ISSUE THREAD

**Issue by ConduciveMammal** [stylelint/stylelint#2865]
I just installed your extension and found that it, quite naturally, shows an error message when Shopify liquid is used within styles. Is there a way to disable liquid errors?

`$color-primary: {{ settings.color_primary }};`

**Comment by gucong3000** [comment]
Your description isn't detailed enough, hard to read what you have to say. Use template please.

**Comment by ntwb** [comment]
Thanks for creating this issue @ConduciveMammal but as @gucong3000 has noted we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please **_help us_** to **_help you_** by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
