### ISSUE TITLE
Add at-charset-no-invalid-position

### ISSUE THREAD

**Issue by hugomrdias** [stylelint/stylelint#2896]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?   
new rule

stylelint should also enforce @chartset at the top of the stylesheet (or at least the file been processed)

following this discussion https://github.com/stylelint/stylelint/issues/2895#issuecomment-329484030 

[spec](https://www.w3.org/TR/css-syntax-3/#determine-the-fallback-encoding)

**Comment by jeddy3** [comment]
SGTM. This would be a great first rule for someone.

@stylelint/core Any thoughts on the name? `at-charset` is the thing, `no-invalid` as it _disallows_ spec _invalid_ code, and `position` is the thing being checked.

**Comment by evilebottnawi** [comment]
@jeddy3 maybe `at-rule-charset-no-invalid-position` or `at-rule-charset-no-invalid` (more generic)

**Comment by CAYdenberg** [comment]
Isn't this a syntax issue? Where you put @charset isn't a stylistic choice: if it doesn't appear at the top it isn't valid CSS.

Another issue I see is that @charset has to be at the top of the compiled CSS file - whereas linting is more useful for source files.

**Comment by jeddy3** [comment]
>  maybe at-rule-charset-no-invalid-position

Rules starting with `at-rule` are currently applicable to all at-rules, regardless of type. The convention has been to the start the rule name with the specific type being targeted (see the [list of rules in `stylelint-scss`](https://github.com/kristerkari/stylelint-scss#list-of-rules), e.g. `at-else-*`, `at-extend-*` etc). Unless there's a good reason not too, I think we should stick with this convention in this instance too.

> at-rule-charset-no-invalid (more generic)

Yes, I did wondered about that. In https://github.com/stylelint/stylelint/issues/2788#issuecomment-322339904, there is a proposal for `at-charset-no-invalid-quotes` (which would warn about single quotes). A more generic `at-charset-no-invalid` would incorporate both checks i.e. quotes and position. However, doing so would deviate from our usual approach of building laser-focused rules (with one message) e.g.:

- `at-charset-no-invalid-quotes` - "Unexpected single quotes (at-charset-no-invalid-quotes)"
- `at-charset-no-invalid-position` - "Unexpected `@charset` not at top of source (at-charset-no-invalid-position)"

I think I'm in favour of keeping them separate.

> Isn't this a syntax issue? Where you put `@charset` isn't a stylistic choice: if it doesn't appear at the top it isn't valid CSS.

Yes, it's a syntax issue. In the [VISION.md](https://github.com/stylelint/stylelint/blob/master/VISION.md#possible-errors) we state we will provide rules for invalid code _for simple cases_ as a stop-gap. There are a few `no-invalid` rules in [stylelint already](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors) (also, see https://github.com/stylelint/stylelint/issues/2884#issuecomment-329091783). Whether it's worth adding this rule (as a stop-gap) is definitely up for discussion though!

> Another issue I see is that `@charset` has to be at the top of the compiled CSS file - whereas linting is more useful for source files.

That's a good point. 

Am I right in thinking that it would still be useful for the following, though?:

- Users of HTTP2 where the CSS might not be concatenated.
- Users who author each of their stylesheets as _standalone entities_, and then use tooling to combine them and ensure there is only one `@charset` in (and at the top of) the compiled CSS e.g. by using [postcss-single-charset](https://github.com/hail2u/postcss-single-charset). 

Additionally, even though stylelint is usually used to lint source files, one of the use cases (albeit a minor one) of stylelint is linting compiled CSS. There's a couple of applicable rules e.g. [`function-url-scheme-whitelist`](https://github.com/stylelint/stylelint/blob/master/lib/rules/function-url-scheme-whitelist/README.md) can be used to ensure all assets have been base64 encoded and use the `data` scheme. This new rule would also be useful for this use case.

---

I'm wondering whether we should use this opportunity to revisit what we do about these validation rules going forward. At some point, all the `*-no-invalid-*` are going to become obsolete because of tools like [csstree](https://github.com/csstree/validator) (see https://github.com/stylelint/stylelint/issues/2816 and https://github.com/stylelint/stylelint/issues/2816). Do we anticipate this by pushing all new validation proposals to plugins now? Someone could create a `stylelint-syntax-validation` plugin _pack_ to house these stop-gap plugins. We could even push the existing `*-no-invalid-*` built-in rules out to it in the next major release. Or, do we keep adding them as built-in rules until they all become obsolete and then push them out then?

**Comment by aj1991** [comment]
Would be a great approvement! :)

**Comment by jeddy3** [comment]
Closing as syntax validation issue.
