### ISSUE TITLE
Reduce size of npm package

### ISSUE THREAD

**Issue by avaly** [stylelint/stylelint#2965]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

An improvement to the NPM package file size.

It's not common for devs to read the docs for a package from within `node_modules`.

> Which version of stylelint are you using?

`8.*`

**Comment by jeddy3** [comment]
@avaly Thanks for the suggestion.

See comment in at https://github.com/stylelint/stylelint/pull/2966#issuecomment-336708089 about why the corresponding PR was closed.

I'm going to keep this issue open so we can gauge what priority reducing the npm package should be.

**Comment by ntwb** [comment]
I'm seeing `146,167 bytes (205 KB on disk) for 27 items` for the `/docs` folder via "Get Info" on Mac OS, that compresses down to ~50kb, not an insignificant size IMHO.

It might be worthwhile exploring alternative packaging options for stylelint, I'm thinking [Lerna](https://lernajs.io/) might be an option where we can keep the stylelint repo _as is_ for the most part but publish the docs as a separate npm package. This would allow for little change to the current workflow for the vast majority of contributors including @stylelint/core and a minor workflow change to publishing new releases, instead of one package there would be two published to npm, the second being `stylelint-docs` via new `package.json` file in `/docs`. In my mind this would be a pretty trivial change, happy to explore further and whip up a proof-of-concept pull request.

**Comment by jeddy3** [comment]
> It might be worthwhile exploring alternative packaging options for stylelint

Agreed.

Perhaps another option, for now, is to simply assume the main stylelint repo will be placed alongside the stylelint.io repo on our local machines. We can then build the website from that. We're already assuming that the docs are always going to be in the same place in the package, so why not carry this assumption a little further?. This approach avoids having to add another tool and an additional publishing step. Also, not all the docs are within the `/docs/` folder e.g. all the rule READMEs, which could complicate the publishing step. If we're building from the main repo, then we could exclude all `.md` files from the package... reducing the size further.

It should just be the case of replacing `node_modules` with `..` in [`scripts/copy-stylelint-docs.js`](https://github.com/stylelint/stylelint.io/blob/master/scripts/copy-stylelint-docs.js) to make this work.

> In my mind this would be a pretty trivial change, happy to explore further and whip up a proof-of-concept pull request.

Having said all that, if you feel your approach has advantages then please do whip up a PoC :)

**Comment by ntwb** [comment]
Closing this in favour of #2454
