### ISSUE TITLE
Reduce gatekeeping for (engine) contributions?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3093]
It feels like there is, perhaps, too much friction when contributors wish to make changes to the [stylelint engine](https://github.com/stylelint/stylelint/tree/master/lib).

There's quite a backlog of issues related to it: https://github.com/stylelint/stylelint/issues/3077, https://github.com/stylelint/stylelint/issues/3056, https://github.com/stylelint/stylelint/issues/3050, https://github.com/stylelint/stylelint/issues/3045, https://github.com/stylelint/stylelint/issues/3041, https://github.com/stylelint/stylelint/issues/3003, https://github.com/stylelint/stylelint/issues/2950, https://github.com/stylelint/stylelint/issues/2939, https://github.com/stylelint/stylelint/issues/2833, https://github.com/stylelint/stylelint/issues/2502. Some of these have pending PRs.

I think it's fair to say that David was the most familiar with the finer workings of the engine. I'll freely admit that I'm not nearly as comfortable with the engine as I am with the built-in rules (as I've been closely involved with them [since the very beginning](https://github.com/stylelint/stylelint/issues/1#issuecomment-68251923)). How does everyone else feel about there understanding of the engine? Unfortunately, like us all, I haven't got enough free time to dive more deeply into the inner workings of the engine. Does anyone feel like they already have the knowledge (and/or they have time to learn) to focus on these issues?

@stylelint/core Lately, I've been wondering what we can do about this. Do you all think that adopting the merging process from https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951 (i.e. core team members are given 72 hours to raise concerns with a (tested) PR, otherwise, it is merged) would help?

**Comment by CAYdenberg** [comment]
I also more enjoy working more with the rules than the engine, but I've found as a contributor that I don't get to do that nearly as much. Irrespective of the buildup of issues, I'd say it's a problem for the team if no one understands the core functionality. My OS time is also pretty limited atm.

I'm hesitant to adopt Node's strategy here because new tests aren't always thorough enough, and documentation changes aren't automatically tested. I would say the project is in trouble if documentation gets out of date.  We could perhaps go to one review per PR with that as the focus, trusting that well-tested code can always be refactored later?

Without a whole bunch of time to learn how stylelint works, best I can suggest is try to get issues knocked off one-by-one and hope that each place you dive in increases your knowledge of at least one component. The good news is we have a good suite of tests as is so regressions can probably be caught ...

One other suggestion, what non-core contributors have recent _accepted_ PRs that touch on the engine? Perhaps they could be invited to do more?

**Comment by jeddy3** [comment]
> I'm hesitant to adopt Node's strategy here because new tests aren't always thorough enough, and documentation changes aren't automatically tested.

Fair point.

> We could perhaps go to one review per PR with that as the focus, trusting that well-tested code can always be refactored later?

Sounds like a sensible middle ground.

> One other suggestion, what non-core contributors have recent accepted PRs that touch on the engine? Perhaps they could be invited to do more?

Good idea.  There doesn't appear to be any accepted engine PRs in the last few months, though. However, there are two _pending_ ones: https://github.com/stylelint/stylelint/pull/3063 and https://github.com/stylelint/stylelint/pull/2942. When they are accepted we can ask if their respective authors are up becoming core contributors.

**Comment by hudochenkov** [comment]
> How does everyone else feel about there understanding of the engine?

I don't understand how it works. I tried but failed because I didn't know how Promises works. (https://github.com/stylelint/stylelint/pull/2427 look at the end of the first message)

> We could perhaps go to one review per PR with that as the focus, trusting that well-tested code can always be refactored later?

I would advise not go this way. With one reviewer (and sometimes with two reviewers) problems could slip through reviewer. For example, today we found that https://github.com/stylelint/stylelint/pull/3015 was review by one person, few issues get through, and now we need to fix them https://github.com/stylelint/stylelint/issues/3092.

The second pair of eyes is better for the product quality.

> i.e. core team members are given 72 hours to raise concerns with a (tested) PR, otherwise, it is merged

It might not be good for our project because most of us don't have a lot of time to work on stylelint, so many PRs would be just merged without proper reviews. It will lead to more buggy and less quality tool.

Our development speed is lower recently. Partially it's because maintainers are busy. But mostly it's because stylelint is pretty powerful, feature-rich, and covers majority users needs.

**Comment by jeddy3** [comment]
> With one reviewer (and sometimes with two reviewers) problems could slip through reviewer. For example, today we found that #3015 was review by one person, few issues get through, and now we need to fix them #3092.

Fair point.

> But mostly it's because stylelint is pretty powerful, feature-rich, and covers majority users needs.

I agree. This is partly the reason I knocked out https://github.com/stylelint/stylelint/pull/3088 & https://github.com/stylelint/stylelint/pull/3087... I believe once those are in then the user can apply limits to _every_ feature of the CSS language.

**Comment by ntwb** [comment]
> The second pair of eyes is better for the product quality.

I'm also for two pair of eyes, for now. I think with some changes to our workflow we could drop this to one pair, take for example #3089:

![screen shot 2018-01-02 at 5 42 30 pm](https://user-images.githubusercontent.com/1016458/34476405-9e1f70d2-efe4-11e7-8228-00ae015a2be5.png)

I'm not sure of the specifics of why in this example the PR was approved and then @CAYdenberg asked for another committer to review it. Possibly similar to what I know I've done myself in the past, and that I will surely do again in the future, and that is that I've reviewed a PR and approved it to later find another committer has issues with the PR and has then requested further changes, sometimes we don't see things others see in that initial look that others do. It's not a bad thing, it's our different levels of experience, and sometimes just the wrong time of day 😄 

That Node document has lots of great ideas, the stand out section is the _Contributions_ section:
• https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951#47c3

I think that makes some excellent points, and one of my takeaways from that is to seek _objections_ to PRs rather than _approvals_. For us here at stylelint I'd envisage that we could switch to this type of workflow which would remove the need to require those two sets of eyes if there are no objections after 72 hours on weekends, and 48 hours weekdays, a committer could then merge that PR without requiring a second review. In being the only committer reviewing that PR the committer is taking ownership of that PR and commit which is by way saying "I've reviewed this PR to the best of my abilities and the code passes all tests currently required by stylelint"

It's all just code, and with Git it's pretty hard to mess up a repo, a revert, tweak, adjustment aka _iteration_ can be easily followed up with.

Will think on this some more, but I think we could probably do it, like #3092, hindsight is a beautiful thing, we probably should use `a` rather than `.foo`, we're just iterating on our code base, my current self constantly criticises my past coding, my future self will no doubt have things to say about my current coding abilities too.

**Comment by jeddy3** [comment]
> I think that makes some excellent points, and one of my takeaways from that is to seek objections to PRs rather than approvals. For us here at stylelint I'd envisage that we could switch to this type of workflow which would remove the need to require those two sets of eyes if there are no objections after 72 hours on weekends, and 48 hours weekdays, a committer could then merge that PR without requiring a second review. In being the only committer reviewing that PR the committer is taking ownership of that PR and commit which is by way saying "I've reviewed this PR to the best of my abilities and the code passes all tests currently required by stylelint"

This makes a lot of sense to me.

**Comment by ntwb** [comment]
The #2942 PR is I think a good example of this in action, it's been ~72 hours since a 2nd pair of eyes were asked to review the PR, there have been no objections so I've suggested (by way of a https://github.com/stylelint/stylelint/pull/2942#issuecomment-355451427) that the PR should be merged 😄

**Comment by CAYdenberg** [comment]
> The second pair of eyes is better for the product quality.

The problem is though that we only have 4-5 active maintainers. For myself, I've been trying to learn more about the core and have now helped write PRs addressing it - so who reviews it? Can I review/approve PRs if I helped with them, even if I'm not the original author?

I agree with @ntwb 's suggestion: review, ask for another reviewer, then merge (after some time period) if there **are no objections**.

**Comment by CAYdenberg** [comment]
Sorry for ghosting this discussion for awhile: I had a talk to give at a local meetup and couldn't find any extra personal time. Kind of the overall problem I guess.

**Comment by modosc** [comment]
yeah - i'd like to be helping out more too but it's been a busy time. if i can find time for reviews where's the best place to prioritize my time?

**Comment by CAYdenberg** [comment]
If you understand the "engine" (non-rule) part of stylelint I think the general agreement is that's where we need help.

**Comment by ntwb** [comment]
p.s Just as a reminder, it's just code, we've got lots of tests, if we break something reverting is quick and easy 😄

**Comment by hudochenkov** [comment]
Of course, it's just a code. But it's a tool that user's use and change their code using `--fix`. E. g. PR was approved, but if no one spotted major problems we'd ended up shipping functionality which messes with user's style sheets. https://github.com/stylelint/stylelint/pull/3080#pullrequestreview-87092773 The main goal for two reviews not to keep code clean, but give users quality tool and don't hurt them.

**Comment by CAYdenberg** [comment]
> E. g. PR was approved, but if no one spotted major problems we'd ended up shipping functionality which messes with user's style sheets.

We could keep requiring two PRs for rules, where we don't seem to be lacking in resources.

**Comment by jeddy3** [comment]
Closing for now. Let's move any further discussion to, erm, [Discussion](https://github.com/orgs/stylelint/teams/core).
