### ISSUE TITLE
Latest Stylelint (9.1.3) won't install fresh via NPM (8.4.0 then working up works fine)

### ISSUE THREAD

**Issue by benfrain** [stylelint/stylelint#3246]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Latest Stylelint (9.1.3) won't install fresh via NPM (installing 8.4.0 and then subsequent upgrades works fine)

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

NA

> What stylelint configuration is needed to reproduce this issue?

NA

> Which version of stylelint are you using?

9.1.3

> How are you running stylelint: CLI, PostCSS plugin, Node API?

NA

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

NA
> What did you expect to happen?

Stylelint would install without error. 
> What actually happened (e.g. what warnings or errors you are getting)?

NPM produced the following error: `ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/stylelint/dist/cli.js'` Note, running `npm i -g stylelint@8.4.0` installs without errors. Having done that I could then install later releases with no problem.

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

I can't reproduce this error.

This is strange, we don't have `dist/cli.js` file in our package, we have `lib/cli.js` instead. As a binary npm uses `bin/stylelint.js`, which requires `lib/cli.js`.

**Comment by jeddy3** [comment]
That's odd... there hasn't been a `dist` folder since [we dropped babel](`https://github.com/stylelint/stylelint/pull/2134/) a year and a half ago. I'll put out `9.2` now. Can you see if you get the same problem with it?

If the problem remains can you:

1. also check you don't have a global version of stylelint installed
2. delete your `node_modules_ folder.
3. update to your version of node and/or npm

**Comment by benfrain** [comment]
It’s possible there was remnants of prior installations. I tried re-installing node/npm, and rm -rf’ing the original node folders first. Only thing that worked was installing the older version and then upgrading to the latest. Very odd!

**Comment by benfrain** [comment]
Now wondering if I was doing something fundamentally wrong by running `npm i -g stylelint@` from a sub-folder of `~/Sites` e.g. `/Users/benfrain/Sites/`

That produces a similar error:

`ENOENT: no such file or directory, access '/Users/benfrain/Sites/stylelint/node_modules/balanced-match`

However if I then run `npm i -g stylelint` from my user root and it installed fine.

**Comment by jeddy3** [comment]
> Now wondering if I was doing something fundamentally wrong by running `npm i -g stylelint` from a sub-folder of `~/Sites` e.g. `/Users/benfrain/Sites/`

I was unable to reproduce this. Installing globally from within `/Users/jeddy3/Projects` and `/Users/jeddy3/Projects/stylelint.io` worked fine on node@8.11.1 with npm@5.6.0.

I'm not sure where to turn next? It could be something specific to your machine (and your node/npm configuration) or an odd edge case in stylelint. It feels like the former, rather than the latter. What do you think?

> However if I run `npm i -g stylelint` from my user root 9.2 installed fine.

As this worked, shall we close the issue?

**Comment by jeddy3** [comment]
And, just to double check, this isn't a problem you've run into before when updating to a new major version of stylelint? I believe you first started using it way back (perhaps before `1.0.0`) so you've probably done a few updates in the past?

**Comment by benfrain** [comment]
Ha, yep, before v1.0.0 so probably something from wayback. Solution was to install an older version first and then upgrade from there so hopefully that should be enough to help any future users should they hit this. Thanks for looking at it.
