### ISSUE TITLE
错误地抛出问题

### ISSUE THREAD

**Issue by 1824437** [stylelint/stylelint#3302]
错误地抛出问题
```
@each $ele in top1, bottom1{
    .#{$ele} {
      position: absolute;
      height: 1px;
      width: 100%;
      background: blue;
    }
  }
```

> Unknown word (CssSyntaxError) (2, $)

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances. Also, use English so we can understand.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
