### ISSUE TITLE
Proposed Rule: When CSS Animations are Present Check for prefers-reduced-motion

### ISSUE THREAD

**Issue by mgifford** [stylelint/stylelint#3309]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This isn't well supported in browsers yet, but some folks get sea sick when there is animation on their devices. Fortunately, there's a way to indicate as a user that they prefer reduced motion - prefers-reduced-motion - unfortunately it isn't well supported:
https://caniuse.com/#search=prefers-reduced-motion

I'd like to see a rule to propose adding https://webkit.org/blog-files/prefers-reduced-motion/prm.htm

If there is animation added https://css-tricks.com/introduction-reduced-motion-media-query/

This is great for accessibility. Also amazing for usability too. Who wants to make their users sick?

> Which rule, if any, is this issue related to?

??

> What CSS is needed to reproduce this issue?

`@media screen and (prefers-reduced-motion) { }`

> What stylelint configuration is needed to reproduce this issue?

??

> Which version of stylelint are you using?

??

> How are you running stylelint: CLI, PostCSS plugin, Node API?

cli

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

??

> What did you expect to happen?

Provide a warning

> What actually happened (e.g. what warnings or errors you are getting)?

??

**Comment by evilebottnawi** [comment]
@mgifford please add this all information to original issue and ping me

**Comment by ai** [comment]
Not sure that bureaucracy is a good thing ;)

**Comment by ai** [comment]
Also I liked the rule idea and don’t think that some addition information is really useful here for implementation

**Comment by evilebottnawi** [comment]
@ai it is not bureaucracy, i have around ~50-100 issues today, if all will be provide only link on spec or articles, i can hardly triangle it, I just do not have time for it. But looks all this issue related to a11y, we decline this in past in favor separate package, but i think we should change our position now. Maybe will be one issue with list rules and description. Let's open, but i'm sure that no one will do this.

/cc @stylelint/contributors

**Comment by ntwb** [comment]
Hi all, language is hard, the stylelint team is located all around the world and speaks many languages. 99% percent of the time what is said is meant with the best of intentions and this should always be inferred.

We have the issue template in place so that when a new issue is created we have all the information we require to help triage the issue and in most cases it is also enough information to allow us to reproduce the issue for testing, it allows issue reporters to help us to help them by supplying _technical data_ that the entire team understands regardless of their native language.

@mgifford If you have an issue with anyone on the stylelint team then following the procedures documented in our [Code of Conduct](https://github.com/stylelint/stylelint/blob/master/CODE_OF_CONDUCT.md) is how to proceed further with any complaint, to publicly criticise one of our team as you have on Twitter [here](https://twitter.com/mgifford/status/996093715574816768) is incredibly impolite and completely unacceptable behaviour.

**Comment by ntwb** [comment]
Per the follow-up comment https://github.com/stylelint/stylelint/issues/3307#issuecomment-388916540 by @mgifford making another personal attack on a member of the stylelint team is unacceptable, @mgifford is no longer welcome here.
