### ISSUE TITLE
breakpoint-overlap proposal

### ISSUE THREAD

**Issue by MatthiasKunnen** [stylelint/stylelint#3311]
**Is your feature request related to a problem? Please describe.**
Issues sometimes occur when media queries overlap. This happens when programmers use both `@media all and (min-width: 600px)` and `@media all and (max-width: 600px)`.

**Describe the solution you'd like**
To mitigate this I would like to propose a rule which checks if at any point the same value is used in `max-width` and `min-width`. If this is the case, all offending breakpoints will get an error.

Alternative name: _breakpoint-off-by-one_.

**Comment by evilebottnawi** [comment]
@MatthiasKunnen Please use issue template

**Comment by MatthiasKunnen** [comment]
Is this not conform to the issue template? What can I do to make it so?

First paragraph is describing the problem, second one is the solution I would like to see in order to mitigate aforementioned problem. There are no alternatives I've considered apart from detecting this in PR reviews but I figured I would leave that out of this feature request as it is the way all linting can be done.

I'm willing to learn how to make this rule but I thought it'd be best to mention my proposal in order to get some feedback so that when I create it, it can help other people.

**Comment by jeddy3** [comment]
@MatthiasKunnen Thanks for the request and for using a template.

It's an interesting proposal. I can see the benefit of it, _if you mix `max-width` and `min-width` media queries_. However,  I'm unsure if the proposal meets [the criteria for inclusion](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#criteria-for-inclusion) because I believe the practice of using just `min-width` queries is more idiomatic (aka "mobile-first").

The good news is we built an [extensible plugin system](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) specifically for these kinds of use cases. If you do create this plugin, please send us a PR to add to the [list of plugins](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md) :)

---

@evilebottnawi FYI, this is using the new ["Feature request" issue template](https://github.com/stylelint/stylelint/issues/new/choose).
