### ISSUE TITLE
Add globbyOptions option

### ISSUE THREAD

**Issue by tinymins** [stylelint/stylelint#3338]
**Is your feature request related to a problem? Please describe.**
In project [stylelint-webpack-plugin](https://github.com/webpack-contrib/stylelint-webpack-plugin), `files` cannot use negated pattern, because there is no option in `stylelint` to set `cwd` of files, so that `stylelint-webpack-plugin` has convert all files paths into abs path.
I'v figure out a way to solve this problem, is to detect if a pattern starts with `!` in `stylelint-webpack-plugin` when convert relative paths to abs paths. But that is not a good way. Here is our discussions: 
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/158
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/159

**Describe the solution you'd like**
We want to add `filesCwd` in options, where we can pass `cwd` field to `globby`.

**Describe alternatives you've considered**
Null.

**Additional context**
Null.

**Comment by evilebottnawi** [comment]
@tinymins `files` should be support negative patterns

**Comment by evilebottnawi** [comment]
Should be solve in `stylelint-webpack-plugin`. Thanks!

**Comment by tinymins** [comment]
@evilebottnawi Thanks.
@shellscape So we should add a negative string detect for `files` just like my first pull request?

**Comment by shellscape** [comment]
@tinymins i believe that @evilebottnawi is incorrect in this case, and that the issue was closed prematurely. stylelint uses `globby`, but provides no means to set the [`cwd` option](https://github.com/mrmlnc/fast-glob#cwd which globby passes options through to) of that module when using it. That forces consumers to send only absolute paths, and cripples one of the fast-glob package's largest features (given that `cwd` exists explicitly so you _don't have to provide absolute paths_.)

**Comment by evilebottnawi** [comment]
@tinymins @shellscape hm, okey, params should be `globOptions` not `filesCwd`, where people can setup glob options, not only cwd

**Comment by tinymins** [comment]
@evilebottnawi Thanks, I've changed field name from `fileCwd` to `globbyOptions`.
