### ISSUE TITLE
Bring ruleTester back into the fold?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#334]
It seems eslint stumbled into difficulties by extracting their rule tester into a separate repo:

http://eslint.org/docs/user-guide/migrating-to-1.0.0#deprecating-eslint-tester

They've folded it back in in version `1.0.0`.

Is this something we should consider doing with our rule tester, while it's still early days?

I can't recall the reason we choose to export `utils` via `stylelint.utils`, but putting the rule tester in it's own repo. Was it because of the `tape` dependency?

**Comment by davidtheclark** [comment]
Yeah, the reason was because it added dependencies (not devDependencies) that didn't otherwise need to be there. `tape` and `postcss`, I guess. (Maybe in the future `postcss` will be a dependency, but it isn't currently).

I guess we could pull it back in. But it seems to be working fine as is for now. I don't think we need to jump the gun.

**Comment by jeddy3** [comment]
> I don't think we need to jump the gun.

Agreed :) I'll close this issue for now.
