### ISSUE TITLE
"ignoreFiles" isn't work when something need to format again

### ISSUE THREAD

**Issue by ansenhuang** [stylelint/stylelint#3379]
The ignoreFiles work initially, but when some more css add and need to format, the ignoreFiles will be format, too.

e.g.

```
{
  "ignoreFiles": ['*.min.css'],
  "defaultSeverity": "error",
  "extends": [],
  "rules": {}
}
```

I have ignored ".min.css", but when css need to format, it will not work and ".min.css" will also be formated.

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new?template=Bug_report.md) using the template.
