### ISSUE TITLE
`unit-no-unknown` on semicolon in `less` syntax 

### ISSUE THREAD

**Issue by vilchik-elena** [stylelint/stylelint#3435]
I find FPs on `;` for rule `unit-no-unknown` on `less` files, for example here https://github.com/ant-design/ant-design/blob/master/components/style/color/bezierEasing.less#L4

**Comment by jeddy3** [comment]
@vilchik-elena Thanks for creating this issue but we are closing it as issues need to follow one of our issue templates, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
