### ISSUE TITLE
Command failed with exit code 2 until --fix or disable corresponding rule

### ISSUE THREAD

**Issue by bm2u** [stylelint/stylelint#3535]
> Clearly describe the bug

Lint fails with exit code 2 on rule violation. Postlint scripts do not run and entire build fails.

> Which rule, if any, is the bug related to?

no-missing-end-of-source-newline

> What CSS is needed to reproduce the bug?

```css
a {
  width: 100%;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
"rules": {
    "no-missing-end-of-source-newline": true
}
```

> Which version of stylelint are you using?

9.4.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "./src/**/*.scss"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

Lint results log, but no abort with errors

> What actually happened (e.g. what warnings or errors did you get)?

```shell
test.css
17:1  × Unexpected missing end-of-source newline   no-missing-end-of-source-newline
```

**Enableing fix option (--fix) or or disableing corresponding rule does solve the problem.**

```json
{
"rules": {
    "no-missing-end-of-source-newline": null
}
```

**Comment by jeddy3** [comment]
@bm2u Thanks for the report.

You'll need to [set the rule's severity](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#severities-error--warning) to `warning` if you don't want stylelint to exit with code 2 on lint violations.

There is already an issue, https://github.com/stylelint/stylelint/issues/3077, to not exit with code 2 if all the violations were successfully fixed with `--fix`. That issue is labeled as "help wanted" and is looking for a champion :)

**Comment by bm2u** [comment]
@jeddy3 Thanks for your quick response. Close this issue as solved.
