### ISSUE TITLE
Add autofix to declaration-block-single-line-max-declarations

### ISSUE THREAD

**Issue by ota-meshi** [stylelint/stylelint#3665]
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [declaration-block-single-line-max-declarations](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-single-line-max-declarations)

**Comment by ota-meshi** [comment]
We may need to consider where to put the newline.

**Comment by SharakPL** [comment]
Any chance this will be added?

**Comment by jeddy3** [comment]
> Any chance this will be added?

I don't believe there is anything blocking this. The issue is labelled as "ready to implement".

Please consider [contributing](https://stylelint.io/contributing) if you have time. There are [steps on how to add autofix to a rule](https://stylelint.io/developer-guide/rules#add-autofix) in the Developer guide.

> We may need to consider where to put the newline.

We should put it immediately after the semicolon of the declaration which is `max` (if there are more than `max` declarations in the single-line declaration block).

Other rules should then take care of things, e.g.:

- `block-opening-brace-newline-after": "always-multi-line"`
- `declaration-block-semicolon-newline-after: "always-multi-line"`

**Comment by SharakPL** [comment]
Thanks for the guide. I'll look into it...

**Comment by jeddy3** [comment]
Closing [as stylistic rules are frozen](https://github.com/stylelint/stylelint/issues/5674). The community is welcome to migrate the rule [to a plugin](https://stylelint.io/developer-guide/plugins) and add autofix.
