### ISSUE TITLE
Simplify the extends name of stylelint config

### ISSUE THREAD

**Issue by laozhu** [stylelint/stylelint#3876]
> What is the problem you're trying to solve?

I want to simplify the extends name of stylelint, just like what eslint shared config does.

- [Eslint reference: Using a Shareable Config](https://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config)

When I make an npm package named [@nake/stylelint-config](https://github.com/nakeapp/stylelint-config#wxapp-%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F) which provides several extend entries, I use them in my project like this:

```json
{
  "extends": ["@nake/stylelint-config/wxapp"]
}
```

I think it's not cleaner than below

```json
{
  "extends": ["@nake/wxapp"]
}
```

> What solution would you like to see?

When I published stylelint config as an npm package like this.

- stylelint-config-laozhu
- @pubean/stylelint-config

I want to extend stylelint config in my project from them like this.

```json
{
   "extends": ["laozhu"]
}
```

and

```json
{
   "extends": ["@pubean"]
}
```

**Comment by jeddy3** [comment]
@laozhu Thanks for the suggestion.

I agree that `"extends": ["@nake/wxapp"]` is clearer.

However, I think it might be too late to introduce this feature because `plugins: []` and `processors: []` also accept ["locators" as values](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends), and we didn't establish a convention for plugin names. There are the `stylelint-processor-*` and `stylelint-config-*` conventions, but not a `stylelint-plugin-*` one (see [the plugin list](https://stylelint.io/user-guide/plugins/)).

As such, I think it might become confusing for the user if a "locator" name can be simplied for `extends: []` and `processors: []`, but not `plugins: []`.

We could introduce a `stylelint-plugin-*` convention now, e.g. `stylelint-plugin-order`, but there are already quite a few plugins and I'm not sure if it's worth mudding the water to add some cleanliness to the configuration object.

I'll leave this open for discussion, though. In case anyone else has thoughts on it.

**Comment by jeddy3** [comment]
As no one on the team has voiced their support for this feature, I'm going to close for now.

**Comment by guoyunhe** [comment]
This would be a great feature.
