### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#3895]
> What is the problem you're trying to solve?

Greenkeeper [supports lockfiles](https://greenkeeper.io/docs.html#lockfiles) now, so what about adding `package-lock.json`?

The following pros are quoted from [npm documentation](https://docs.npmjs.com/files/package-lock.json)  about `package-lock.json`:

> This file is intended to be committed into source repositories, and serves various purposes:
>
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> - Provide a facility for users to “time-travel” to previous states of node_modules without having to commit the directory itself.
> - To facilitate greater visibility of tree changes through readable source control diffs.
> - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

The current latest NPM version is [`6.5.0`](https://github.com/npm/cli/releases/tag/v6.5.0) and it's mature enough. I think it's now when we should introduce the lockfile.

Related to #2766

**Comment by jeddy3** [comment]
Thanks for the suggestion.

We adopted the ["Lockfiles for apps, but not for packages" approach](https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514) a while back. This has done us well so far. Has new information come to light that advises we should revisit our choice of approach?

**Comment by ybiquitous** [comment]
Thanks for the quick help!

Surely, I think the opinion "Lockfiles for apps, but not for packages." makes sense, but the following opinion in https://github.com/sindresorhus/ama/issues/479#issuecomment-425722909 seems to be more reasonable to me.

I quotes from the comment:

> While this is correct, the inverse is not necessarily true: it's not because you don't have a lockfile that your local tree would match that of your users. So removing the lockfile doesn't solve the mismatch problem.
> 
> At least the lockfile guarantees that your fellow developers have the same trees.

Unless lockfiles, I'm worried that we may not be able to guarantee the same trees on the local machine of our fellow developers/contributors or on CI environments. 😟 

Now, we have [`npm ci`](https://docs.npmjs.com/cli/ci.html) and [`npm audit`](https://docs.npmjs.com/cli/audit.html) commands, which do many things for us with `package-lock.json`.
For example, in the case of the `event-stream` vulnerability last year, by `npm audit` we could examine whether the unfixed version of the package would have been installed on own local machine.

However, this issues seems to be a trade-off, so eventually I'll follow the policy decided by our community. 👌

**Comment by jeddy3** [comment]
> Unless lockfiles, I'm worried that we may not be able to guarantee the same trees on the local machine of our fellow developers/contributors or on CI environments.

Fair point.

> Now, we have `npm ci` and `npm audit` commands

Both these would be useful. We could run `npm audit` as part of our [pretests on the CI](https://github.com/stylelint/stylelint/blob/e91458e2612d828dbedbaeed9ced2ce07f9a8df6/.travis.yml#L20-L23).

> Greenkeeper supports lockfiles now, so what about adding package-lock.json?

I remember this being tricky the first time we tried this. However, if you want to put the legwork in we can certainly give it another go. Give it a couple of days to see if anyone else wants to chime in on this issue first though.

**Comment by Arcanemagus** [comment]
Greenkeeper (finally!) supports them without all the tricky additional steps that used to be required that were tripping things up last time it was attempted. (I've since started migrating things to [Renovate](https://renovatebot.com/) due to several issues with Greenkeeper, but if it's working here there's no big reason to change.)

**Comment by jeddy3** [comment]
> Greenkeeper (finally!) supports them without all the tricky additional steps that used to be required that were tripping things up last time it was attempted.

Good to know.

I'll label this up as ready to go.

**Comment by ntwb** [comment]
Apart from the ability to run `npm audit` I still don't see any benefit to adding a lock file to be honest...

The current `package.json` file:

> `"postcss-value-parser": "^3.3.0",`

Using `npm ci` with a lock file will install `postcss-value-parser` version `3.3.0`, if `3.3.1` is released the stylelint Travis CI jobs will *not* test that release, it will continue to use `3.3.0` until we bump our dependency to `3.3.1`.

Looking at the current list of dependencies requiring an "update":

```shell
 autoprefixer      ^9.0.0  →   ^9.4.5
 chalk             ^2.4.1  →   ^2.4.2
 debug             ^4.0.0  →   ^4.1.1
 postcss           ^7.0.0  →  ^7.0.13
 postcss-less      ^3.1.0  →   ^3.1.1
 postcss-reporter  ^6.0.0  →   ^6.0.1
 table             ^5.0.0  →   ^5.2.1
 husky             ^1.1.0  →   ^1.3.1
 lint-staged       ^8.0.0  →   ^8.1.0
 remark-cli        ^6.0.0  →   ^6.0.1
```

By adding a lock-file none of the above _minor_ or _patch_ versions would be tested on Travis CI until we update the dependancy, Greenkeeper currently doesn't advise us or send PRs for these because they are covered by the Semantic Versioning ranges we have declared in out `package.json` file.

The ownus on updating all of the above packages once a lock-file is added falls to the stylelint team to update these packages, to do this, we must remove the `^` and `~` SemVar indicators from our dependancies in `package.json`  so that Greenkeeper will send us PRs with these updates, then approve twice, and merge.

Apart from `npm audit` there is no benefit to stylelint, stylelint users, nor the stylelint team IMHO.

Lock-files break semantic versioning, and theres no point having SemVer if you use a lock-file

**Comment by ntwb** [comment]
I believe Renovate and Dependabot support open source software and would give us a _free_ license, but that's not the reason I point this out.

I'm pointing this out because regardless of Greenkeeper, Renovate, or Dependabot the onus is put back on the stylelint team to update each package for **every** minor and patch release of a dependency that we use, each time one of the above tools see we need to bump `3.2.1` to `3.2.2` or `3.3.0` a PR will be created, this has to0 be reviewed and approved by 2 members of the stylelint team and merged.

Now what I left out above, each time we bump a dependancy we will need to publish a new version of stylelint, for example, `postcss-selector-parser`, this dependancy and package has switched maintainers and here at stylelint we had issues testing the version 4.x of the package, there is now a version 5.0.0, and a PR bumping it from `3.1.1` to `5.0.0` in #3861. More than likely stylelint will require a new release to ship the 5.x update of `postcss-selector-parser`.

Now, with what I wrote above and what you wrote above @ybiquitous:
> What I'm concerned about most is, unless lockfiles, installed packages can differ by each CI build in the same PR, that is, by each npm install.
I think this can make us hard to debug why CI builds failed... 🤔

Yes, this can be an issue on the CI, but we can also fix this on the CI by not caching the `node_modules` folder and perform a fresh install each time.

But what we can't do is that if it is determined that `postcss-selector-parser` version `5.0.0` shipped with a minor bug and then once stylelint updates `postcss-selector-parser` to `5.0.1` is inform our users that if they re-run `npm install` (and possibly clear any caches) is that due to semantic versioning stylelint doesn't have to publish a new release of stylelint to include the `5.0.1` bug fix in `postcss-selector-parser` as due to semantic versioning the end users get it for "free" from the same version of stylelint they already have.

So that, to me is the tradeoff, should we the developers of styleint add the extra burden upon ourselves by removing semantic versioning from the project?

By adding the lock-file some minor debug enhancements are added to our CI jobs, but so is a bunch of extra burden added to the stylelint development team, and lastly further burden added to end users to have to upgrade more frequently because there are more frequent releases because stylelint no longer supports SemVer?

**Comment by ybiquitous** [comment]
@ntwb OK, I completely understand your opinion. 🙆‍♂️ 

Surely, the release cost seemts more important here to me.

Thank you very much for your kind instruction! 👍
