### ISSUE TITLE
Not totally obvious that this is a linter for CSS

### ISSUE THREAD

**Issue by guicar** [stylelint/stylelint#3942]
> Clearly describe the documentation issue

This was not totally obvious for me that this is a linter for CSS rather than for JavaScript. Indeed, in the subtitle:
![image](https://user-images.githubusercontent.com/16036647/52281747-08eea400-295f-11e9-89c6-67a6d27dfb04.png)
we could think this is a linter to enforce good style on JavaScript. And I have seen this project posted with just a #javascript tag.

> What solution would you like to see?

I would explicit the supported languages. For example:
> A mighty, modern linter for styles (CSS, SCSS, ...)

Same thing for the README. Instead of:
> A mighty, modern linter that helps you avoid errors and enforce conventions in your styles.

I would write:
> A mighty, modern linter that helps you avoid errors and enforce conventions in your styles (CSS, SCSS, ...).

**Comment by jeddy3** [comment]
> This was not totally obvious for me that this is a linter for CSS rather than for JavaScript

It's tricky because stylelint supports more than just CSS or CSS-like languages like Scss. It can, for example, parse:

```js
// index.js
import React from "React";

const button = () => (
  <a style={{
    unknown: a
  }}>hi</a>
);
```

We tried to avoid pigeonholing stylelint as just a CSS (and CSS-like) linter by using a more generic "style" description. This is to help differentiate it from CSSLint. I can see how this could be confusing, though.

I'm not sure what the best thing to do is. Any ideas?

> I would explicit the supported languages.

We do that, as well as list the containers that stylelint can extract styles from, in the [list of features](https://github.com/stylelint/stylelint#features).
