### ISSUE TITLE
Combination of `esm>=3.2.10` and `stylelint>=9.10.0` cause exit status `3221225725` on Windows

### ISSUE THREAD

**Issue by chalkygames123** [stylelint/stylelint#3980]
> Clearly describe the bug

When running `stylelint>=9.10.0` with combination of `esm>=3.2.10` cause exit status `3221225725` on Windows.

Reproducible repo is here:
https://github.com/chalkygames123/esm-stylelint-issue

There is an `index.js` file that just requires `stylelint` and outputs `"succeeded"` to the console.

Running `$ node .` will succeed but `$ node --require esm .` will terminate the process silently.

These commands also can run with following npm scripts to get error logs:
- `npm run succeeds`
- `npm run fails`

My environment is the following:
- OS: Windows 10 (64-bit)
- RAM: 16 GB
- Node.js: v10.15.3

Unfortunately, I couldn't figure out which of stylelint, esm, or any other is causing the issue. So I'm sorry if this issue is invalid.

> Which rule, if any, is the bug related to?

Nothing

> What CSS is needed to reproduce the bug?

Not necessary

> What stylelint configuration is needed to reproduce the bug?

Not necessary

> Which version of stylelint are you using?

`9.10.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Node.js API but it's likely irrelevant.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

Linting completes normally even if it used with `esm`.

> What actually happened (e.g. what warnings or errors did you get)?

Linting fails with exit code `3221225725`.

**Comment by hudochenkov** [comment]
Thanks for using the template and providing a reproducible repository.

I'm afraid it most likely not a stylelint problem due to [esm](https://github.com/standard-things/esm) nature of being a module loader. I see that you've reached the esm team before https://github.com/standard-things/esm/issues/745.

I'm not sure if we would be able to help you, because most of our team doesn't have Windows machines. And we haven't received stack overflow errors reports before, which might indicate that stylelint works correctly with Node.js module loader.

This issue is not reproducible on macOS.

**Comment by chalkygames123** [comment]
Although the root of the problem is not clear, it seems fixed in esm@3.2.21 anyway.

I'll close this issue now. Thanks!
