### ISSUE TITLE
Update rule tester documentation

### ISSUE THREAD

**Issue by 43081j** [stylelint/stylelint#3982]
So your docs [right here](https://stylelint.io/developer-guide/rule-testers/) claim that you have three testers:

> When developing plugins, you can use the following rule testers or create your own.
>
> stylelint-test-rule-tape
> stylelint-test-rule-mocha
> stylelint-test-rule-ava

Of these three, only the first one seems to exist. Are the other two non-existent? The most you have is a commented out (broken) implementation of each inside the tape tester.

---

Secondly, internally, you don't use any tester at all? Given [this file](https://github.com/stylelint/stylelint/blob/master/jest-setup.js), it seems you are creating a custom test suite implementation for jest.

Is there a reason you're avoiding using what your own docs recommend (`createRuleTester`)?

---

Thirdly, is there a reason you execute a generated rule tester's suites on the [next tick](https://github.com/stylelint/stylelint/blob/f4f0531f9a2eec0b69d2f848b4738e43688be53c/lib/testUtils/createRuleTester.js#L120)? This makes it impossible to use with mocha because the suite has already run by the time your code defines the test cases.

**Comment by jeddy3** [comment]
@43081j Thanks for the questions and sorry about the delay responding. stylelint is maintained by a very small team.

> Are the other two non-existent? 

It looks that way. There appears to be an unmaintained version of [stylelint-test-rule-ava](https://github.com/hudochenkov/stylelint-test-rule-ava) outside the stylelint org. There's also [stylelint-tape](https://github.com/csstools/stylelint-tape), which looks to be a recent 3rd party tape runner.

We need to update the documentation to reflect this.

Context: We started with tape for stylelint's internal tests, and extracted out the tape tester for plugin authors. We've since moved to Jest, but I don't think we ever got around to making the Jest tester available externally.

> Given this file, it seems you are creating a custom test suite implementation for jest. 

That's correct. 

> Is there a reason you're avoiding using what your own docs recommend (createRuleTester)?

Offhand I can't remember the reason for doing this, though. I suspect it's because the old testers predate the autofix feature being added to stylelint and we needed to find a solution that works with it.

> Thirdly, is there a reason you execute a generated rule tester's suites on the next tick?

Unfortunately I don't know. The person who originally wrote a lot of the stylelint engine and related tools is no longer involved. 

---

I'm going to turn this into a documentation issue as we need to update the rules testers section to better reflect the current state of play.

It'd also be great if we find someway of making the Jest script available to plugin authors, perhaps [as a preset](https://jestjs.io/docs/en/configuration#preset-string)?

**Comment by 43081j** [comment]
That's ok, i'm happy to do a PR or two when i understand the path we want to take a little better.

I would suggest we simplify the rule tester a little, or instead of having a 'builder function', move to having a class (which rule testers can inherit). It would make them a little simpler to implement.

Most of what i mentioned here is just documentation related, fortunately, so shouldn't be too difficult to sort but is probably better done by one of your team/maintainers.

Related is #3976 which im happy to try contribute to too. Again, mostly docs rather than bugs or anything.

**Comment by jeddy3** [comment]
> Most of what i mentioned here is just documentation related, fortunately, so shouldn't be too difficult to sort but is probably better done by one of your team/maintainers.

We're a skeleton crew of volunteer maintainers, so any help would be greatly appreciated!

> I would suggest we simplify the rule tester a little, or instead of having a 'builder function', move to having a class (which rule testers can inherit). It would make them a little simpler to implement.

That does sound like an improvement. However, let's first check to see if the rule testers are compatible with the autofix feature. If they aren't then it might be best to deprecate the stylelint org rule testers in favour of supporting an official Jest preset (which stylelint consumes itself). Other tests runners can still exist outside the stylelint org, which looks like the way things are going anyway (see https://www.npmjs.com/package/stylelint-tape)

> Related is #3976 which im happy to try contribute to too.

Replying to #3976 was next on my list :)

**Comment by 43081j** [comment]
afaik the existing rule tester code doesn't have any `fix` related assertions in it.

also IMO we should be providing a base rule tester which isn't specific to jest or anything. this way we can re-use the common logic in whatever test framework we like (and maybe provide a jest one which builds on that, which stylelint its self uses).

**Comment by jeddy3** [comment]
> also IMO we should be providing a base rule tester which isn't specific to jest or anything...  (and maybe provide a jest one which builds on that, which stylelint its self uses).

Housing a base rule tester and a jest one that builds on it in the stylelint org sounds good to me.

Feel free to contribute this in a proof-of-concept PR. We'll likely want to update the documentation in the same PR so everything is aligned, but it's probably worth putting together the PoC bit first as we'll want to be confident that this change improves the developer experience for plugin authors.

**Comment by hudochenkov** [comment]
Closing this one. Because we're deprecated `createRuleTester` API.
