### ISSUE TITLE
Report Needless Disables with Rule Errors and Warnings

### ISSUE THREAD

**Issue by geekox86** [stylelint/stylelint#4076]
> What is the problem you're trying to solve?

Currently, I have to run `stylelint` twice to get all errors and warnings that I need: once with `--report-needless-disables` and another time without it. I should only need to run it once for both.

> What solution would you like to see?

I would like to change the behavior of `--report-needless-disables` so that such needless disables get reported *with* rule errors/warnings in one shot.

**Comment by MaxMilton** [comment]
This one caught me off guard. I expected it to work the same as ESLint's `--report-unused-disable-directives`, where it adds extra errors into the regular output. I'm embarrassed to say, I had a few projects essentially not being linting for a month because of this issue :sweat_smile: 

I wonder how many other projects made the same assumption and haven't realised yet 🤔

**Comment by thibaudcolas** [comment]
I also was expecting this flag to work like ESLint’s equivalent, and was very close to start using it on all of my projects. Here is a PR to address this: #4151
