### ISSUE TITLE
Support yaml in stylelintrc

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#418]
Ref: https://github.com/stylelint/stylelint/pull/417#issuecomment-148276507 & https://github.com/stylelint/stylelint/pull/380#issuecomment-147250935

**Comment by TrySound** [comment]
Yaml is much more readable for me.
https://github.com/TrySound/case/blob/master/.stylelintrc
eslint somehow make this feature. Does it too difficult to make the same?

**Comment by davidtheclark** [comment]
@TrySound : I think it's probably a good feature for us to try to build in; but because of the complexity that it was adding I decided to leave it out of the initial `.stylelintrc` feature. So I think this is the right approach: to open it as a separate issue and take it on when we can.

Here's the problem, and I'm open to solutions: As you can see in https://github.com/stylelint/stylelint/blob/master/src/plugin.js, I'm using the `require.resolve()` algorithm to find `extends` and `plugins`, then `require()` to load them. I glanced at the ESLint codebase and found it to be way more complicated than this, so I wanted to try the simple approach first and see if it works for us. What we would need to enable YAML would be an alternate function to load the files -- alternate to `require()`, or somehow making `require()` understand YAML.

**Comment by makotot** [comment]
@davidtheclark  Replacing [rc](https://github.com/dominictarr/rc) to [rc-loader](https://github.com/MoOx/rc-loader) is not enough to support YAML?

**Comment by davidtheclark** [comment]
No, because rc isn't used to load extends or plugins.

**Comment by makotot** [comment]
Oh, sorry, I misunderstood.

**Comment by davidtheclark** [comment]
Integrated into #490.
