### ISSUE TITLE
Add tests for Markdown

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4240]
Looks like we don't have tests for Markdown. In https://github.com/stylelint/stylelint/pull/4239 markdown parser was removed and tests didn't fail, but they should have. Because we support Markdown out of the box.

**Comment by evilebottnawi** [comment]
:+1:

**Comment by Oluwasetemi** [comment]
Willing to jump on this @hudochenkov Any direction on how to get with it?

**Comment by jeddy3** [comment]
@Oluwasetemi Thanks for offering to help out. The markdown parser [will be removed](https://github.com/stylelint/stylelint/issues/5289#issuecomment-840772900) in the [next major release](https://github.com/stylelint/stylelint/issues/5205). Compatibility will fall on the maintainers of the postcss-markdown syntax, and so it's unlikely we'll be adding tests for it to stylelint itself.

If you use stylelint to lint styles inside of markdown, please consider contributing by [updating postcss-markdown](https://github.com/stylelint/postcss-markdown/issues/12) to PostCSS@8 and the new `Document` node so that it'll be ready for the 14.0.0 release.
