### ISSUE TITLE
Add ignoreSelectors: [] to property-no-unknown

### ISSUE THREAD

**Issue by dprgarner** [stylelint/stylelint#4270]
> What is the problem you're trying to solve?

My team and I use CSS Modules on our project and are trying to use the `property-no-unknown` rule, but every time we declare an exported variable in an `:export` block, we get warnings from this rule. This was raised in the stylelint-config-css-modules repo [here][issue1] and [here][issue2], but I think the workarounds given there miss the point: it doesn't make sense to compare properties in an `:export` block against a whitelist of known CSS properties when the [ICSS][icss] spec allows all properties nested in `:export` to be arbitrary.

[issue1]: https://github.com/pascalduez/stylelint-config-css-modules/issues/3
[issue2]: https://github.com/pascalduez/stylelint-config-css-modules/issues/4
[icss]: https://github.com/css-modules/icss#export

> What solution would you like to see?

I'd be happy with either of the following fixes:

1. Always disable this rule for properties in an `:export` block, without any API changes. This would be my preference: I can't see any problems arising from this, as I don't believe there is a use case for wanting to check properties in an `:export` block against a whitelist with this rule. However, I am aware that the developer guidelines advise against language-extension-specific code changes like this.
2. Add an option to the `property-no-unknown` rule to ignore _all_ properties nested in a declaration block matching a given selector name. For example, if the option was called `ignorePropertiesOf`, then adding `{"ignorePropertiesOf": [":export", "/^:import/"]}` to the config would allow arbitrary properties nested in `:import` and `:export` blocks. This is a more general approach and doesn't include anything tied to ICSS, but I don't know of any other language extensions that would need this.

I've got something working using the second approach, and can submit a PR for this. I've called it `ignorePropertiesOf`, but would be open to other name suggestions. (`ignorePropertiesOfSelector`? `ignoreSelector`? `ignoreBlock`?)

**Comment by hudochenkov** [comment]
I think the best option here would be to contribute to [`stylelint-plugin-css-modules`](https://github.com/alexlafroscia/stylelint-plugin-css-modules) and add modified `property-no-unknown` there specifically for CSS Modules needs. Similarly how `stylelint-scss` has [`at-rule-no-unknown`](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-no-unknown/README.md).

**Comment by jeddy3** [comment]
> Similarly how stylelint-scss has at-rule-no-unknown.

The plugin [makes use](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-rule-no-unknown/index.js#L61) of the [`checkAgainstRule` util](https://stylelint.io/developer-guide/plugins#stylelintutilscheckagainstrule) and the [`property-no-unknown`](https://stylelint.io/user-guide/rules/property-no-unknown) rule's [`ignoreProperties` option](https://stylelint.io/user-guide/rules/property-no-unknown#ignoreproperties-regex-regex-string). This is good because it frees the plugin author from having to duplicate the original rule's logic within their plugin.

For the same thing to happen in this use case we need to add an option to the rule. A `property-no-unknown` plugin can then be added to the  `stylelint-plugin-css-modules` pack that makes use of this new option and configures it to ignore properties within `:export` and `:import`.

So, I'm in favour of @dprgarner second proposal of adding a new option. It should be called `ignoreSelectors` to be in line with [our conventions](https://stylelint.io/developer-guide/rules#secondary).

I'll label up accordingly, but feel free to shout if there are objections.

> I've got something working using the second approach, and can submit a PR for this.

Please do.
