### ISSUE TITLE
Adopt Contributor Covenant?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#432]
I think we should adopt this Code of Conduct: http://contributor-covenant.org/

Any objections?

**Comment by ntwb** [comment]
Nope, great idea :+1:

**Comment by jeddy3** [comment]
This might seem like an odd one to oppose, but we already have an appropriately brief [conduct section in the contributing guide](https://github.com/stylelint/stylelint/blob/master/CONTRIBUTING.md#conduct). One that simply requests that unstructured critique be kept to a minimum and to respect differences of opinion, so that we can collectively problem solve as quickly as possible.

**Comment by davidtheclark** [comment]
I agree that the existing conduct section about unstructured critique is good and don't think we should replace it. But it very specifically addresses the problem of unstructured critique and does not address potential problems related to diversity. That's why I thought supplementing it with the Contributor Covenant would be a good idea. I think it's been made clear that many people in underrepresented do not always feel welcome in open source projects, and that at least some of those people feel more comfortable getting involved in a project when there is a direct, overt statement indicating that project's intention to respect and support them. So I'm in favor of adding Contributor Covenant to what we have.

**Comment by jeddy3** [comment]
>  and does not address potential problems related to diversity

Good point. I agree that's something we can better address. 

I've no doubt that the motivation behind the Contributor Covenant itself is well intentioned, but I have some reservations about the wording of it. For example:

> Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct.

I'm not sure it's a great idea to appoint ourselves adjudicators of what speech is or isn't appropriate, and then censoring what we deem to be the latter.

> Project maintainers who do not follow or enforce the Code of Conduct may be permanently removed from the project team.

Likewise, threatening to ban people if they say or do the wrong thing seems a bit excessive.

Perhaps the middle ground for us is adding our own overt statement to the contributing guide? :)

One than focuses on welcoming everyone, but without the free speech implications.

At the moment we open with the sentence:

"Any help is welcome and appreciated."

Perhaps we can expand on that to something like:

"Any help is appreciated and we'll try to make all contributors feel welcome." 

Or, if you feel it's appropriate, expand it to include a ", regardless of x y z..." bit at the end.

How does that sound?

**Comment by davidtheclark** [comment]
> I'm not sure it's a great idea to appoint ourselves adjudicators of what speech is or isn't appropriate, and then censoring what we deem to be the latter.

I have no problem doing that. There are a lot of assholes out there, and I'm very ok with making them uncomfortable. Whether we want to be or not, we *are* the adjudicators of speech on this project: letting nastiness fly is as much a statement as censoring it.

> Likewise, threatening to ban people if they say or do the wrong thing seems a bit excessive.

I also have no problem doing that, for the same reason. In fact, I *will* ban people if they say or do things that I consider excessive and offensive, whether we adopt the Covenant or not.

But if it makes you uncomfortable to adopt the exact Covenant, ok. I will work on a PR that incorporates what I think are the key pieces.

**Comment by jeddy3** [comment]
> , ok. I will work on a PR that incorporates what I think are the key pieces.

Thank you. :)

This issue touches on subjects that I'm sure we all have strong feeling about. I feel strongly about both inclusion and censorship. They don't often come up in software projects, but when they do I find it is usually best for everyone, if they want to, to air their thoughts.

With that in mind.

> letting nastiness fly is as much a statement as censoring it.

I totally agree. I wasn't suggesting we let it fly :) 

I'm more in favour of tackling it in the open, rather than sweeping the words under the carpet to fester. To let everyone see and allow them to make up their own minds.

> I will ban people if they say or do things that I consider excessive and offensive

I think the issue I have is that if someone says they are offended, then it must be so. It doesn't matter what the intention of the offending person might have been. And the thought of potentially banning speech by the way of something so subjective is what makes me uncomfortable.

I'm also wary of the use of vague terms, in the Covenant doc, like "trolling" and the catch-all statement of "Other unethical or unprofessional conduct" to define such unacceptable behaviour.

But, like I said, I'm 100% on board with the intention of the initiative :) I think we're both on the same page here and want the same thing.

So, if there's some way of capturing, in the PR, the intent of being welcoming and supportive, while not making claims to censor speech if someone violates a vague list of offences, then that would be great :)

**Comment by davidtheclark** [comment]
> I'm also wary of the use of vague terms, in the Covenant doc, like "trolling" and the catch-all statement of "Other unethical or unprofessional conduct" to define such unacceptable behaviour.

I actually interpret those vague terms as allowing for the kind of case-by-case variation that will inevitably arise --- allowing for Maintainer A to interpret the doc and its enforcement a little differently than Maintainer B. 

And that's what it all comes has to come down to --- the case-by-case assessment --- and in each case we just want to figure out a decent way to handle things that neither discourages and offends nor unnecessarily vilifies.

**Comment by jeddy3** [comment]
> And that's what it all comes has to come down to --- the case-by-case assessment --- and in each case we just want to figure out a decent way to handle things that neither discourages and offends nor unnecessarily vilifies.

Yep. I totally agree with that :)
