### ISSUE TITLE
Add check for array of arbitrary values to Options Validator 

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#449]
Ref: https://github.com/stylelint/stylelint/issues/445#issuecomment-150225665

Needed for:

* [x] `function-whitelist`
* [x] `function-blacklist`
* [x] `property-blacklist`
* [x] `property-whitelist`
* [x] `unit-blacklist`

This rules require their options to be an `array`, but currently `strings` aren't flagged up.

[Options validator](https://github.com/stylelint/stylelint/blob/master/src/utils/validateOptions.js)

**Comment by davidtheclark** [comment]
Wait a second ... I made the fix for this but now I'm thinking it shouldn't be necessary. :(

Why couldn't `function-whitelist` accept a single value instead of an array? That would seem fine to me. Same for all the others: I don't think they actually *need* arrays: a single value is just as good as an array with one item. The code for the rule might have to be adjusted to accommodate, that's all.

What do you think?

**Comment by jeddy3** [comment]
> I don't think they actually need arrays: a single value is just as good as an array with one item.

That's a good point.

> What do you think?

I think you're right. Lets adjust the code for the rules so they accept a string or an array.

Is the work you've done in https://github.com/stylelint/stylelint/pull/458 still valid for [`rule-properties-order`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-properties-order/index.js#L21), where we're accepting a known key word ("alphabetical") or an array of arbitrary values?
