### ISSUE TITLE
Create plugins for well-known preprocessors

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#450]
Less, Sass and etc. Generate css and source map and throw error on lines based on sourcemap. What do you think guys? In separate repositories.

**Comment by TrySound** [comment]
@evilebottnawi You are welcome.
https://github.com/davidtheclark/stylelint-statement-max-nesting-depth
If you want it, you can make it :)

**Comment by davidtheclark** [comment]
Yep, we'd be open to any contributions along those lines and definitely add them to the docs.

One thing to point out: the PostCSS folks wrote the scss-parser module, and that's why we can understand SCSS syntax; but I don't think anyone has yet written a Less parser. So if there are parts of the Less syntax that break PostCSS's standard parser, Less users would have to create that parser before this integration would go very smoothly.

**Comment by evilebottnawi** [comment]
@davidtheclark with scss syntax stylint work fine or not?

**Comment by davidtheclark** [comment]
Yep, with a couple setting: set syntax to "scss" in the Node API and CLI; or use the scss-parser module in your PostCSS process if you run stylelint as a PostCSS plugin.

**Comment by evilebottnawi** [comment]
@davidtheclark maybe add docs about this feature?

**Comment by davidtheclark** [comment]
Done in #474.
