### ISSUE TITLE
Add ignore:["delay"] to time-min-milliseconds

### ISSUE THREAD

**Issue by jens-duttke** [stylelint/stylelint#4552]
> What is the problem you're trying to solve?

Animations/Transitions that take less than 150ms should be omitted, since this time is too short to provide a visual improvement.

On the other hand, I'm using a delay of 40ms to defer style changes for hover effects. E.g. if you quickly move the cursor over a input box, scrollbar or button, it should not change its style. Only if you leave the cursor on the element for atleast 40ms. This prevents flickering, while quickly moving the cursor.

> What solution would you like to see?

The "time-min-milliseconds" rule should provide options to specify different values for delay and duration.

**Comment by jeddy3** [comment]
@jens-duttke Thanks for the request and for using the template.

Thank you for clearly explaining your use case. 

> The "time-min-milliseconds" rule should provide options to specify different values for delay and duration.

I've been trying to think of a way to idiomatically achieve this. In hindsight, we should have had `duration-min-milliseconds` and `delay-min-milliseconds` instead of `time-min-milliseconds` from the beginning, but we hadn't thought of this use case. Alas, we didn't. 

I think the best way forward is to add an `ignore: ["delay"]` secondary option. You can then use:

```json
{
  "rules": {
    "time-min-milliseconds": [150, {
      "ignore": ["delay"]
    }]
  }
}
```

Delays are [funny things](https://drafts.csswg.org/css-animations/#animation) that can be negative numbers too. I think an option for ignoring delays will also allow this use case while respecting the original goal of the rule.

The new option will need logic to identify delays in shorthand properties like `animation` ([spec ref](https://drafts.csswg.org/css-animations/#animation)).

Unless anyone has any objections, I'll label this issue up as a new option?

**Comment by jeddy3** [comment]
As there are no objections, I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.
