### ISSUE TITLE
add ignore regex option for selector-id-pattern and selector-class-pattern rules

### ISSUE THREAD

**Issue by stephenliu1944** [stylelint/stylelint#4660]
![image](https://user-images.githubusercontent.com/5137237/77511989-15a8c100-6ead-11ea-8587-dac58b112eaa.png)

> What is the problem you're trying to solve?

I have a old project that want to use stylelint. I set selector-id-pattern and selector-class-pattern rules to make camel case selectors rule but there were too many legacy code that use 'xx-xx-xx' name style to override 3rd party css, like '.ant-form-explain'.

> What solution would you like to see?

I want to use a regex to ignore that class name, like 'ignoreAtRules' option for 'at-rule-no-unknown'.
That avoid to write many /* stylelint-disable */ and /* stylelint-enable */ code.

**Comment by jeddy3** [comment]
@stephenliu1944 Thanks for the request and for using the template.

> That avoid to write many /* stylelint-disable / and / stylelint-enable */ code.

I recommend you use this `/* stylelint-disable */` command comments as they explicitly mark the use of a legacy class name. This explicitness will benefit the whole team.

> I want to use a regex to ignore that class name, like 'ignoreAtRules' option for 'at-rule-no-unknown'.

However, if you do not want to do that you can update your pattern to allow these legacy class names. For example:

```json
{
  "rules": {
    "selector-class-pattern": "^[a-z][a-zA-Z0-9]+$|^ant-|^mz-"
  }
}
```

Will enforce camelCase class names, but also allow class names beginning with either `ant-` or `mz-`. See [this demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIB0YA2BDAzpgBMAvgDoB2KG2AwugLYyp5GnrEAuAtOgyUtQF5sAjLsW4AFLGHT0C3AB4BPWWzAMQAGhCZ5rdLIThs68BGIAzAJYBzfcBI4chEACcArqhiZH8PHfsPNdDBgLBBOyuSYbAAO6CwsME4iCP4AegDa6Gy8ALoZWQCCbABaAAxsAJzZANQAJAA+KczsDXxsjr6M+CD4QA).

The 'at-rule-no-unknown' rule has an 'ignoreAtRules' secondary option because the primary option is a boolean. The `selector-class-pattern` and `selector-id-pattern` rules accept a regex for their primary option, so there is no need to add a secondary regex option.

I'm closing the issue, but feel free to reopen open if neither of these solutions is appropriate.

**Comment by stephenliu1944** [comment]
Thanks, I got that.

**Comment by RemyMachado** [comment]
I'm adding my favorite pattern to the edifice in case it helps someone using BEM naming convention & Material-ui:

`"^[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$|^Mui.*$"`
