### ISSUE TITLE
Document passing arguments to custom formatters

### ISSUE THREAD

**Issue by masi** [stylelint/stylelint#4668]
> What solution would you like to see?

Access to all or parts of the Stylelint configuration data and/or to namespaced CLI arguments.

Proposal one requires a new key "formatter" within the configuration array that may hold options for all custom formatters. The path (without .js) is the key within "formatter" for the actual custom formatter in user.

Proposal two requires the CLI to accept any arguments of the form custom-formatter-x. Where x stands for any string. All options without the prefix custom-formatter- are to be passed on the custom formatter.

Both proposals require the addition of a new argument for the formatter function.

**Comment by jeddy3** [comment]
@masi Thanks for the request and for using the template.

This is the first time we've had a request for this feature. It looks like [ESLint suggests using](https://eslint.org/docs/developer-guide/working-with-custom-formatters#passing-arguments-to-formatters) either:

- environmental variables
- piping the output from the JSON formatter into another program

If neither of these are acceptable, can you tell us more about your use case so that we can decide on the best solution? Otherwise, I'll label this up as a documentation issue.

**Comment by masi** [comment]
Both solutions are acceptable. It didn't occur to me to use environment variables for custom code. Building a wrapper around the JSON output is also a god idea.
Sorry.

**Comment by jeddy3** [comment]
> Both solutions are acceptable. 

It's good to hear.

> Sorry.

It's all good. The solutions aren't documented anywhere in our docs. I'll reopen the issue as "type: documentation". I'll probably have time to rustle up something tomorrow, probably a line or two on the [writing formatters](https://stylelint.io/developer-guide/formatters) page in the developer guide.
