### ISSUE TITLE
Remove function-calc-no-invalid

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4731]
> What is the problem you're trying to solve?

The [generated parser](https://github.com/stylelint/stylelint/tree/master/lib/utils/parseCalcExpression) that sits behind the [`function-calc-no-invalid` rule](https://stylelint.io/user-guide/rules/function-calc-no-invalid#function-calc-no-invalid) weighs 130k.
This is smaller than the very heavy `*-no-vendor-prefix` rules (see (https://github.com/stylelint/stylelint/issues/4730), but 130k is still a significant weight to a browser bundle and is problematic for https://github.com/stylelint/stylelint/issues/3935.

Additionally, @evilebottnawi mentioned in https://github.com/stylelint/stylelint/issues/2454#issuecomment-622462940 that the rule is problematic for other reasons.

> What solution would you like to see?

Move the rule into a plugin.

We should consider using this opportunity to move the other validator rules into a plugin, e.g. `at-rule-no-unknown`. Including the validator rules in core is:

- [a stop gap](https://stylelint.io/about/linting#validators)
- [problematic for users of CSS-like syntaxes](https://github.com/stylelint/stylelint/issues/1612#issuecomment-390501818)

Users can choose whether and how they want to validate their CSS:

- a dedicated and comprehensive validator like csstree if they're writing vanilla CSS
- the `@stylelint/plugin-validate` plugin if they want to use stylelint to validate (as best it can)

Shared configs like `stylelint-scss` could include the plugin and configure it appropriately.

**Comment by evilebottnawi** [comment]
> We should consider using this opportunity to move the other validator rules into a plugin, e.g. at-rule-no-unknown.

We will become not a linter, but the second prettier with options and the ability to install plugins

> https://github.com/stylelint/stylelint/issues/1612#issuecomment-390501818

Other our rules also can be broken, broken AST === broken rule

**Comment by evilebottnawi** [comment]
Thus we lose our main goal. For me personally it is very sad that we sacrifice the main goal because of performance, what for us at the moment is not critical at all. 

We constantly recommend using csstree for validation. Does anyone really use this? It contains many bugs and is still under development. If necessary, I can provide examples. 

I agree `function-calc-no-invalid` has bad implementation and probably we should not have put it in the core in the past. But the rest of the rule is quite simple, logical, comfortable and work fine, excluding problems with parsers.

After we transfer them, who will maintenance these repositories, I think no one. 

Let's look on real world:
- Stylelint is linter, more linter rules is good, removing such rules is the loss of our main goal
- Stylistics rules can be simplified because we have prettier and many developers have been using it for a long time
- We have good performance right now, improving it is not critical 
- Bundle size is not critical, ncc supports chunks, we can move some big modules to chunks and load them lazy
- Almost all developers will install this plugin
- CSStree is not good right now (is still under development) and we should not recommended it as stable solution

These are my thoughts

**Comment by jeddy3** [comment]
All good points.

> I agree function-calc-no-invalid has bad implementation and probably we should not have put it in the core in the past. But the rest of the rule is quite simple, logical, comfortable and work fine, excluding problems with parsers

We could move only `function-calc-no-invalid` to a plugin and keep the other rules in core. That will help us support running stylelint in the browser (https://github.com/stylelint/stylelint/issues/3935).

**Comment by evilebottnawi** [comment]
Agree, let's move `function-calc-no-invalid` out of core, just note - latest CSS have `min`/`max`/`clamp` functions like `calc`, so name is wrong too :+1:
