### ISSUE TITLE
A default configuration file

### ISSUE THREAD

**Issue by Xaviju** [stylelint/stylelint#488]
* [x] Add copy-paste source for creating your own config
* [x] Add line about `stylelint-config-suitcss` to Quick start.

This is a feature request.

A default configuration file example. 
It would be nice to find a default ```.stylelintrc``` with all the rules included so it takes seconds to remove all the features you don't need and create a full linter.
Now, i should go in every rule to see the examples and see how should I declare it.

Something like the example in the rules doc, but with all the rules and options.

**Comment by davidtheclark** [comment]
I agree that it would be nice to have a copy-paste example. The big question is how to determine the settings ... or maybe we just list all the rules but provide no settings ... or we could just say stylelint-suitcss-config is default ... I don't know. @jeddy3 ?

**Comment by jeddy3** [comment]
> The big question is how to determine the settings

Yep, that's the big one. And the reason we implemented shareable configs right from the start.

> or we could just say stylelint-suitcss-config is default

I'd be cool with emphasising the suitcss config, if only because the [corresponding STYLE.md](https://github.com/suitcss/suit/blob/master/doc/STYLE.md#4-css) is so concise.

Perhaps we should reintroduce shareable configs back into the main README.md? Maybe in the [Quick start](https://github.com/stylelint/stylelint#quick-start) section. That would reduce the friction to a "full linter" for new users, with minimal effort on their behalf, and without us needing to maintain our own config.

In the meantime, @Xaviju have a look at the [extends](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) section of the user guide to get going with pre-built config.

**Comment by davidtheclark** [comment]
I agree that extendable configs is the preference for reusing stuff, but I
interpreted this issue as requesting a copy-paste source for creating your
own config. I think maybe just maintaining a JSON file that lists *all* the
rules would be a good way to do this: copy-paste that, then fill in your
options for each one (or delete). What do you think of that?

**Comment by Xaviju** [comment]
@davidtheclark yes, that was my intention. If it helps, I was thinking of something like this to make the UX easier:

```
// Int options
// 0 - turn the rule off.
// 1 - turn the rule on as a warning (does not affect CLI exit code).
// 2 - turn the rule on as an error (CLI exit code is 1 when triggered).

{
  "rules": {
    "string-quotes": [int, "single" | "double"],
    "number-leading-zero": [int, "always" | "never"],
    "number-no-trailing-zeros": int,
    "number-zero-length-no-unit": int,
    "color-no-invalid-hex": int,
    "declaration-colon-space-after": [int, "never" | "always"],
    "indentation": [int, int | "tab"]
    ...
  }
}
```

@jeddy3 thanks for the **extends** :cool:

**Comment by davidtheclark** [comment]
I think this is a good thing. @jeddy3 if you agree let's assign it to 3.0 milestone?

**Comment by jeddy3** [comment]
Sgtm. 

Lets open it out to a Pull Request too.

**Comment by zebapy** [comment]
Why was the rules.json deleted in master now? I just had to heavily format the rules.md file to turn it into JS to get it again..

**Comment by jeddy3** [comment]
> Why was the rules.json deleted in master now?

It was migrated [to the docs](https://stylelint.io/user-guide/example-config) a few years go as an example config.

That example config is signed posted to in the ["Getting started" guide](https://stylelint.io/#craft-your-own-config).
