### ISSUE TITLE
Add color-hex-alpha

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#4880]
> What is the problem you're trying to solve?

Some of the browsers not supported #rgba and #rrggbbaa kind of hex codes for colors.
refer https://caniuse.com/#feat=css-rrggbbaa

> What solution would you like to see?

So it would be great if we have an option in color-hex-length to prevent 4 & 8 digit hex colors.

**Comment by malsf21** [comment]
Hi @ssivanatarajan,

Thank you for the suggestion! I personally think that this is a reasonable feature to add, especially given that Internet Explorer seems to not support 4-character/8-character hex codes. However, I'll leave it to @stylelint/core to make a final judgement, especially on how to name the new option. Some options include `allow-four-character`, `allow-4-character`, or `allow-transparency-character`, though I'm not sure what's the best naming scheme.

I've labelled this issue as needs discussion, so we can decide on a consistent naming scheme. That being said, you can probably get started now; if you have the time, it would be great if you could add the option yourself! [The stylelint documentation has more information on how to add a rule](https://stylelint.io/developer-guide/rules#add-options).

**Comment by jeddy3** [comment]
@ssivanatarajan Thanks for the request and for using the template.

Let's add a new rule. The `color-hex-length` rule is for enforcing the use of [what the spec calls](https://drafts.csswg.org/css-color/#hex-notation) "shorter variants". We shouldn't overload this rule to enforce whether the alpha channel is required or not.

- Name: `color-hex-alpha`
- Primary option: `"always"|"never"`
- Secondary options: None
- Autofixable: No
- Messages:
   - `"always"` -> `Expected alpha channel in "${hex}"`
   - `"never"` -> `Unexpected alpha channel in "${hex}"`
- Description: "Require or disallow alpha channel for hex colors"
- Section: "Limit language features" -> "Color"

Examples...

With `"color-hex-alpha": "always"`:

```
a { color: #aaa }
```

```console
1:8 Error Expected alpha channel in "#aaa" (color-hex-alpha)
```

With `"color-hex-alpha": "never"`:

```
a { background: linear-gradient(to left, #333a, red 100%}
```

```console
1:20 Error Unexpected alpha channel in "#333a" (color-hex-alpha)
```

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new rule](https://stylelint.io/developer-guide/rules#add-a-rule) in the Developer guide.

I suggest you use a rule like [`hue-degree-notation`](https://github.com/stylelint/stylelint/tree/master/lib/rules/hue-degree-notation) as a blueprint because you'll want to use [postcss-value-parser](https://www.npmjs.com/package/postcss-value-parser) to find all the hex colours within a value (rather than use older `style-search`, which `color-hex-length` uses).
