### ISSUE TITLE
Per-rule ignoreFiles

### ISSUE THREAD

**Issue by nex3** [stylelint/stylelint#4890]
> What is the problem you're trying to solve?

Within Google, we have some high-enforcement lints that will break builds if they aren't complied with. However, there are occasionally files that (often for legacy reasons) can't be made compliant with these lints. We want a way to designate certain subsets of files to ignore for a given lint, while still enforcing it everywhere else.

Note that using `stylelint-disable` here is not sufficient, because we want centralized control over who's opted out of the lints in question. We don't want any old author to violate the lint and add a `stylelint-disable` to silence it.

> What solution would you like to see?

I'd like to see an `ignoreFiles` option as a per-rule configuration that controls which files that rule in particular applies to.

Note: this is basically equivalent to #4875, but for `ignoreFiles` instead of `ignoreDisables`.

**Comment by evilebottnawi** [comment]
You need this https://github.com/stylelint/stylelint/issues/3128, so you can setup rules for each file

**Comment by jeddy3** [comment]
@nex3 Thanks for the request.

As @evilebottnawi said, I believe the [proposed `overrides` configuration object property](https://github.com/stylelint/stylelint/issues/3128) would encompass this use case (as well as others like specifying the syntax and reconfiguring rules, rather than just turning them off).

> Note: this is basically equivalent to #4875, but for ignoreFiles instead of ignoreDisables.

I've [proposed an alternative solution](https://github.com/stylelint/stylelint/issues/4875#issuecomment-671064957) for this, which is more in line with the other `report*` options that deal with `stylelint-disable` comments.

**Comment by jeddy3** [comment]
Closing in favour of #3128.
