### ISSUE TITLE
[coc.nvim] stylelint: Undefined rule function-calc-no-invalid

### ISSUE THREAD

**Issue by fesnavarro** [stylelint/stylelint#4908]
>It's probable not a bug, but lets go
my config based on https://github.com/react-boilerplate/react-boilerplate-cra-template
    "stylelint": "13.6.1",
    "stylelint-config-recommended": "3.0.0",
    "stylelint-config-styled-components": "0.1.1",
    "stylelint-processor-styled-components": "1.10.0",

I'm using neovim with coc-styledlint which send me the message:
[coc.nvim] stylelint: Undefined rule function-calc-no-invalid

Even trying to add a rule as false or true it does not make effect. Is the extensions maybe causing this behavior ?

**Comment by jeddy3** [comment]
It looks like coc-styledlint uses [stylelint-vscode](https://www.npmjs.com/package/stylelint-vscode) which is a couple of years old. There's [working going on to update it](https://github.com/stylelint/vscode-stylelint/pull/141).

In the meantime, you can turn off `function-calc-no-invalid` with `null` i.e. `function-calc-no-invalid: null`, or just use stylelint on the CLI.

As this issue is not related to stylelint itself, I'll close.
