### ISSUE TITLE
stylelint-config-email

### ISSUE THREAD

**Issue by IanEdington** [stylelint/stylelint#4930]
> What is the problem you're trying to solve?

Emails are hard to write because as web-developers we're used to using styles that can't/shouldn't be used in email.

> What solution would you like to see?

A `stylelint-config-email` preset that has the most common rules for email

Asking here because google isn't finding anything for me. We'll most likely make our own and contribute it back to the community if there isn't already one

**Comment by jeddy3** [comment]
> Asking here because google isn't finding anything for me.

I don't believe there's one. There's not one [listed in awesome-stylelinte](https://github.com/stylelint/awesome-stylelint#configs) either.

> We'll most likely make our own and contribute it back to the community if there isn't already one

That would be fantastic. It's an interesting use case, as I know email clients struggle with some CSS features.

I can imagine stylelint support for:

- [`<style>` tags and `style=""` attributes in HTML files](https://stylelint.io/about/syntaxes)
- [limiting language features](https://stylelint.io/user-guide/rules/list#limit-language-features)

Would prove useful here.

Once you've published your config, please send a PR to [awesome stylelint](https://github.com/stylelint/awesome-stylelint) so that others can find it.

**Comment by IanEdington** [comment]
Thanks for the guidance

**Comment by jitendravyas** [comment]
Was anything created for email?
