### ISSUE TITLE
"value-keyword-case" has not been disabled   CssSyntaxError

### ISSUE THREAD

**Issue by medeepaksaini** [stylelint/stylelint#4932]
When i'm trying to compile files from `scss` to `css` gettings error in `_bootstrap-variables.scss`

### Errro
```
public_html/src/scss/_bootstrap-variables.scss
263:1  ×  "value-keyword-case" has not been disabled   CssSyntaxError
```

*263:1 code :*
```
$embed-responsive-aspect-ratios: join(
  (
    (21 9),
    (16 9),
    (4 3),
    (1 1),
  ),
  $embed-responsive-aspect-ratios
);
```

**Comment by jeddy3** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.

Also, please create a [reproducable example using the demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIAkMC2AjGUC0AnGAzgA4QB2BAlgG4zYCGxMYALnncxRAfAAQBWECqQAUAHVI8eYiZKkAmAIw8AnAEoANONlSFANhUats4QBYeAZkMzJwpQquSHPFBix5CJctVoMiTVrjsnATiqgDcIOogBACepMx0AB4I0WAEBJHgZABmFADmKcBGoiC4AK4ANoQlvEXWPCXseJW0pBDYZaQA1m0A7qQ1PMzlMJr1JegVEGBd2G3YaETMMYPDZaNGkiWQU7hz7UJUdBUUOAAWMImrI2Pa2xCoqDDx+wuoSysIQzebDSCwYAqdECHDI2Em01m8ygZSIJzA7FoRFwED8uA41S+AG1fpI1ht6pI6to7iB8m18IMcYSSfdyEwyhwaNgYXCKAjmIRsL0KMwziyKNlsjB8C8jhV1iEQLjZABdGUAX1+stushKAKBIM4pHBUxmrwIZwg6LOdFIOGRqJFy2wEBouFwp0xvHxqq2IGyZFY2ToqAoFRir1Z8MRc19zu+6zdf09Lx9foDrz96SEeWweWeIvZ2Hj-sDXRgMV6xqg1yjvxK2U6LG12ARFTAr0Ox1OZYJpKrpBrYPrjfmnWIdDAbitIONbejleroJ1J1IMGB6cCUAoz1Y8za5AS5uBOBX+G7Ay+rorIALMWygSeLKYmqCYPmFHexu3zAnp6eK7oOYXzDK+DDa9+26PojxdH5xhAaFCGHc1U2wRgwEFdleU+cDy0g6FYRDTl6FYJ8SHRZoqildD2zVKD2mDdlQwIGAqhYY1SMjcj3XmRYbQICB-2Hd9MPaS5hm-Oi-R2MhmJPfjsGbE4924yZaAIIFDTrB4nniCSINJS00RtYCeggfo+NJOiGOYY1sCIOiyigdpAQYAhXk6AyjOPLSKNM-wLKsmAbIEqp1PXdpnNA4yPPory9mWPwnJAwywJYydomGeCNxgXo5xgML3U6XlYpchLJNJJpyiqN4PmwTLwRgT1KWxGVGgqXo6BiKVoyJGV3UuYclipTqKIhGYSMcuhsk5PYCHDQDaEGrphpKdraQ9ChcAIddCE5UtpRpSQVX6kpyWNLL6p2ijRvG1THjXEp+vlGklXqPbIJKlpprrBhjt4Eopl6EUFtPF6ytIKbB2Hegxr+r5Gua1qENTMrMv+56AlekT2QgKYdXnDKhB8CHcEGaGWra09ZrrKZKFINN0ECMGOMDKrMFqz6-nne0kdJMnAS4eCaaHVp0qq87Ia+kBjhhknIK5inedpgWcfnarmcJsWmuJ7BUEqDhKtxjmBr1WZucp6m5YQoh+aVo6VfF9XjYR3XIlJg3bT8UhZYt7Ghfx621dhzWKm1xHHal52rTdqnwVN0G8fGn2Jbhqn7fnPX3TJsP3bB6PLbq0WbdalO-jEvYLkSd66JVn7IaSovsBLyrnjyPkVcNF8C-uK6XnpnXFaZq2TpJP488lgfiQHv5upgXr+7H91clW9a1qwG7TqemeDryCkWepGf3TWmIqjnVhIEeM0oClW7FWVau1LXbkzl5DwLaEShYDj4m2-AMo1oeSyUV0wMu6Mxqn3Xg28lpDwLh1U6JQJ5T1Af1d0ws9hgC-uZVAv9RzLEgUtOea05gbSXttGeq8x7r03n1U6iD8aXUCtg0kz8nQJzyEnGaBtl7EMvo9JKGpgT3h1OgM0aYs5IJVmzKup4eFajBAIiOWde450Hr7YeFFJF8N1JCBCaB0aY3wQrGOItFHx39oHB23Dby8JnOo-UaMxI6mEd7KGqt4521oEHMx9kpH8OdjYjGYI5HAIUSUMRBNg6klUZYsmLju60FQEkG8Hi+HMQUO4u8ETnZCX9PBHxmM3751CSo8xnjVI6M9rjcGsdHFDw1lrCg0SP7hNrLYs2FsRGVKUUwlh9TClqKaf45WjjgldISZYwBZT5Fbwak49++TtCjwHjAxIPU3zTzXmLahDSyB0Iorghem12FjxIfMskG8QE8DAaspBNDrozNIWSLwsAOmuLGWwohBzOHaEOTGacjS1LflKYrVpud2nGNqW408nZDw0OEubMGgLDG23hk85ONypxdkscfWJzSwbjNETAdmKKPTfLBLE0uoz5zMQAAxJQhZY4G14ETl0cZXEJ1KiU6nNqKPkhAuT-NoAw1+bSjE1LqQSmltYOVrguHRRyWd+UsyCXikUjyRWsrRbWXo99OT2IqUCiWH8hCwHiHwwYcgkpVCpnybAAAvEU7RgK8myn8El5UbSZSSUlT8FBvzCnYP+WgvSYX6JCbq6ZHqsBep-L6gCAaLY4oGYqllH5w3et-H6t6DL5UgGZR-T1Kao1ImBJK7lMrA3SXuZmwZBLc2Rr-ABQIVNaCjnYBZbVBiiZ5LDV+Gtab60ZhdiKZtE1S1xpDR2pNXaACO6xcAMwoHgjFfzBZlLhe2xyIKVXjojVOkUs752-KxUG3JMrEUbsgtW7dM6dZ7pPge7OFaE0f3YhjO+D9o6OqCe0ZMxsFjmltNkBC3FcBg15e+qCZRXB7CqHQFcEcbUoiPY+8DmA9jzAyXONMcGuCgZ0taQMGaK6GXEZBUqtAyUzQCRMmkq7qkB1BaYmUcylqwOWfAyhMYVp4PJXs15A9Pn0JOQo85tzLkYuuRfe6V9TyeUYnsdgKV0CMhmrTAszAS1P3Lbi-FSVpPmVk8weTin+1jiHS0hxotK3aYijJvCBncJNt07ekdrMH0Ep0xZY+6AhCDtvSuqZY7IJueQQ8TzwMHN9NOauj+gWbwEFglAM0R9gteYcxuPxgbQPRZONezFvLyltr88o3eVmHNZcSze8LgSoIucs2ZCyzqyOUpq5FSy1lbLkwcmXTN2bXPFe8q1uyylHISviFKrksqNPxq01J3rewfJ+QWAFW++GmWEcTQFmbLXfJtYioFYpD4IAJBnCrWyZQFJRY29Ff1H0CO-TW6SXKR9rsrdux-cU6xsDnmLLgHAy3RbdaSm9p52XF16Ly8G+FfthVgsgoDq9ZXMWtvB9RqJ0PSSw9K1CxzFHNNEbR8cd7GP6vvFdbjSlRgHoKhAAqIAA).
