### ISSUE TITLE
Change exit code for CLI flag error

### ISSUE THREAD

**Issue by averms** [stylelint/stylelint#4989]
> What is the problem you're trying to solve?

According to the user guide, an exit code of 2 means that either there was at least one rule violation or a CLI flag error. I'm trying to integrate stylelint into a text editor and it would be a lot easier if those two things had different exit codes.

> What solution would you like to see?

Maybe a CLI flag error could have an exit code of 3 or something. There's no agreed upon standard (there is sysexits.h but it is rarely followed).

**Comment by ybiquitous** [comment]
It seems to me this issue is historical.

The `meow` package, which is used internally for CLI, exits with `2` when specified flags are invalid:
https://github.com/sindresorhus/meow/blob/dc7dae4820bfc7397193a92833487d47f82c7411/index.js#L184

**Comment by ybiquitous** [comment]
Ref:

https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/docs/user-guide/cli.md?plain=1#L219-L223

**Comment by ybiquitous** [comment]
Meow and we use `2` for flag errors. For example:

https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/lib/cli.js#L386

https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/lib/cli.js#L438

So changing the code for rule problems seems easier, e,.g. `2` -> `3`.

And I agree with including this change in 16.0.0 (the next major).

Any thoughts?

**Comment by Mouvedia** [comment]
> Any thoughts?

It's very likely that ppl have scripts that care about "rule problem" and not so much about invalid flags—because it would be fixed immediately in the latter.
Changing the exit code of the former would be way worse because it would break way more scripts.
IMHO we should keep `2` for the main usage.

---

Maybe we could create a new constant alongside
https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/lib/cli.js#L19-L20
so that the `process.exit` that we do have control over
https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/lib/cli.js#L386
https://github.com/stylelint/stylelint/blob/1d145f9fbf140f9ffc1317f10bb6130ab8e13210/lib/cli.js#L438
could be changed.

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for the feedback.

> IMHO we should keep `2` for the main usage.

Make sense. 👍🏼 

Besides, it may be better to convert `2` thrown by Meow to `3`, but it seems unnecessary.

---

> `3` means _No such process_.
> `22` would be better because it means _Invalid argument_ which matches our usage—invalid option.

Is this a common practice? Do you have some resources?

**Comment by Mouvedia** [comment]
> Is this a common practice?

> it is not a	good practice to call `exit(3)` with arbitrary values to indicate
> a failure condition when ending a program.
> Instead, the pre-defined exit codes from sysexits should be used, so the
> caller of the process can get a rough estimation about the failure class
> without looking up	the source code.

> Do you have some resources?

https://android.googlesource.com/kernel/lk/+/dima/for-travis/include/errno.h#55
https://github.com/search?q=%22process.exit%2822%29%22+language%3AJavaScript+argument&type=code

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for sharing the info.

I found another resource that defines `78` as a *configuration error* like us:
https://sources.debian.org/src/libc/5.4.38-1.1/include/sysexits.h/

What do you think about this definition?

**Comment by Mouvedia** [comment]
> What do you think about this definition?

One checks whether it's parseable as JSON and is an object, the other at l382 seems to redo what `meow` already does in a more refined way.
_configuration error_ is better than _no such process_; whether it's better than _invalid argument_ is up for debate, but that would be bikeshedding at this point. What I am interested in, is whether
- we go the route of _partially_ accomplishing what was requested by the OP by adding a new constant on our side and be done with it
- or if we wait for #5042 to be unblocked and send a PR to `meow` so that this exit code can set in [its options](https://github.com/sindresorhus/meow#options)

Most scripts would be forgiving in nature and just checks whether it's falsy or not so the number shouldn't matter that much.
What I know is that it will  have to be done eventually—i.e. the granularity matters—but someone else will have to set #4989 priority.
Sharing the same exit code for the flag error case with `meow` would be ideal.

**Comment by ybiquitous** [comment]
Thanks for the explanation. I agree with the idea that "the number shouldn't matter that much". We just want to distinguish rule problems and other errors.

Sending a PR to Meow may be good, but it's unsure whether Meow's maintainers accept such a request. Considering our other issues, this issue's priority is low, unfortunately.

**Comment by ybiquitous** [comment]
It's time to release this issue's change with the next major version, 16.0.0. I'll make a PR.

**Comment by ybiquitous** [comment]
Closed by #7134
