### ISSUE TITLE
New line between siblings?

### ISSUE THREAD

**Issue by kuoruan** [stylelint/stylelint#5068]
> What is the problem you're trying to solve?

```scss
.parent {
    a {
    }
    b {
    }
}
```

I want to find some rule to add new line between siblings.

> What solution would you like to see?

```scss
.parent {
    a {
    }
    /** Add new line here <- */
    b {
    }
}
```

**Comment by jeddy3** [comment]
@kuoruan Thanks for the request and for using the template.

You can use the [`rule-empty-line-before` rule](https://stylelint.io/user-guide/rules/rule-empty-line-before).

This is how [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) is [configured](https://github.com/stylelint/stylelint-config-standard/blob/6e87f2c5ea85de2b9c7aebef94fd654119cd4847/index.js#L6-L12):

```js
  {
    "at-rule-empty-line-before": [
      "always",
      {
        except: ["blockless-after-same-name-blockless", "first-nested"],
        ignore: ["after-comment"],
      },
    ]
  }
```

**Comment by kuoruan** [comment]
@jeddy3 
Thank you for the reply.
Currently I'm using `stylelint-config-standard`.
I tried this rule. but it only add new line between "at rules"

Before:

```scss
.parent {
    a {}
    b{}
    @media screen {}
  }
```

After:

```scss
.parent {
    a {}
    b{} /** I want also add a new line before "b" ↑ */
    /** Add new line here */
    @media screen {}
  }
```

**Comment by jeddy3** [comment]
My bad, I copied the configuration of `at-rule-*` and not `rule-*`.

This is how stylelint-config-standard is configured for `rule-empty-line-before`:

```js
  {
    "rule-empty-line-before": [
      "always-multi-line",
      {
        except: ["first-nested"],
        ignore: ["after-comment"],
      },
    ]
  }
```

See [this demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIB0AHAhgJxgOwC4AJgAdbffNQksgXyvwCNLT9bmABAWxigEsKBnMFhyFWrEABoQ-AJ540ADwTh+-SeAjYAZjwDmy4syIgMAVwA2MfsfhMyZY2lwBaM5efYIz09gDWngHdsG3xcMxgJOgcNcwgMDy8ebAA3NHMeKGcACxgFELDTCKj8Y0gOLjwE5xgOFFwZfPDI5mjYMHNMJx5NZ3pYsF8qqFMUdLAnGGcUDAgUGAxcHisQgG1isgKilvtDez2SkD1PLFX1-dLNfhgwU0XkyeHRnnHcK2cAnlws514tLXmcC5UuZCtYQGcyABdM6sPaQ5p7YxtDoYLo9PoQAZVfhZOJfNDYTLTWbzerOCD3DAYDLLBChJrFYxaTQuLRoDg8cwyIYjMYTDzs2m2TYI+xMlnONkcrlVDmqJK6Zy6HDzZ6S9mc7m+GAyAJxKCNQqi6JaHxgRY9cbmMBVJLAjKGraIkCm7Dm7rYZxWm2ebzYfjoMDcclzVG4OKO40HV3unrpbAwTBK1G8QFVTz+3AEqCYTK8LCx4J0kWMkDamRaVFcH7XFFoz2+ni1PEE3CR0tcXhoSWJ3CmLAC6u+nz+CBBdvbYy+2CCHC8bCKgPXHg6MCfBrFhmTkDT3nPflOZxNlB41wWIX0o2l3dPF6TK6Wc1xMHCrfO301Orc-gQftBifvl4uRhN2VwcpAsT+gBYo7okKRpBkPy-n094dDiXoQOUgIvpeTowcSoZksOfiBEWr5XtuD7XOG8QoFcphQF47RoKoVQjqR0HRFRT60fRjHVJYFQuMRo7jpuFHOtxNHOPUcxsSRY5kbhUbGPwYQKumMABPGMCcQcPifPJolKSW26Hm4kyfmSOm9DAzInHSazbNEaQBGgMhglGZC7Ps0S5EGdSnM55wgBiAyWKxaBaK88T8IKg6TGFvgRZ5EIwToGBqR4VivAa4LBVCXkwUccS6Y5aUudF8wYVheDGGl0LBbC9jwqW5nnglXosWVtjGLEATzMYKkgO17jYPFAZoEGzhRTFISOOYbkec4-AKu4OlDW1LgWStNTPBAkHZdpSSTLNg10gtS2pduSVerEq0Lr0qLTVZ3I2fQdmlfNO4wJSm03f0gztBAD2KvQz2TAmx0JjNVUYN9rnuddzq3cDoNPVNkNae9n0Ob1I2LUjzgcBYizOBtkilqj90aeDmMrYGiW4z1ByI8toPrSd-0o4DIY4LTENHTZZ3wxdBNXcTpM8OTXOUwDmKDCS2AC-Tk3TSLCOE+za2TBTw23UrKvTWrTP2Szl1I9zMEQXE2S5F1Vzff153DTb8Q5Ao5M4LoXzfTieJW9EZRCdUtTWSdtlm0FvkWx5gc7Glxj+TAgXlQV6U8Jlwk5dw9Xp616fGCVeP4E5vmSfUljxi4wfZmCDUwsUBfOsHaYBFknxWIzR7+jSmtXfHpSmGpmFTDMhHcq9Mswx9UdpzH4uW3Lvk+Qvyep7YZfl5VMVesP4YcGPJILBuRXOhlWUJmpuf5dvzfl0XujHCzW-b44cM1UJ8cL0kq2wCtOtp6JUBnnO+jdtj31aLWToFpPT0AJIubuGsxYJj+svGCyIYEel6Aghm9NZ5fTFmzZGGDoFhmwbdMC+1DpQ2FnDfuRMSbmDJnrUsmDyHol5lQm2noTawzmkQrW-AAELk5gmQeIB2H1l6FwvaPC8HTQISXKcv0XZsLIdIyhgCbIcEUDWZiHCoJ0gAIzDSkbAmRCsZKok5BpbhB1NAMLjugqBBjpHyNoRHZB+NiGS2YdLVh25zHYPkXw7xrMhEiN0GIsqZiNEWNCd3JR5sfpoLiW4ixU8cZz03mcWOJC9irxCuvNs89t6sw-sExxLiH4ukzpfHOeUGpnwOMXF+FUKm71bnVGpP9e7-w5rrCOSVQHl0ar5ZqhVSwxgSZhXRQsvH0MERLJhLDZbDRmSEuZoEkFLJ8ZEwZQCJGbMtNshRptCH41QWo7cJzPS6M9lkk6OEAAMGyzQWPGtWcYjsxbO1Fu8t0Fj0BYDwDkK4wjPEw1-n3ZZjCpZHJqUyD52CQWAnBW8PhMLYDfWubFbR6zpkop6O3TuYS9kRIHkiw4hJAT1hCAAJmGpYBcXxnAAC95heGIp8PSxgHmhy-EAnCpiOzcD4D2Jw-ZJiJPpuE-JEjOwSv+FKgcsrFHM1xaogFYquySr7AOL5MrupOzHDc50SruwqoNZMNFYKrCYu7tilJeLFXiqtb2aVrgEGTGPk4W25KBH7KpcNS1+qvWogXL60M-rYpJM1XC5xob3XOAAI6FAwG9HgWVa4LJhvKxey1VkBMJduMN6b5hZpzWcwN51g1E0OYEi1KaK2ZpltW8oOz8EJqudqiRH4DrvA7q8E2fLYLE2zejOc5ItArV-BgaaUKWamXfKYDgH14iWDQPORUnKZhOIKQcbAa6N1VBArYx6e6QZjoIqSbkPyUn-IkTtJ5M8e2lzyYW4RxbEVFSKc6Ep0dylMnqdna+TT84tMfs-IDb8Rof26aUhuTUm7DSkrbJw6l6C3ESs9bUuBhFYv6S6vt1L0PxEw9SbDrw+ZhgDbsoNR7SNoZgI+aSlGeDUejfMWN5zI6XKY2k0s5Gar0CSLx2tot61JuE6x6itsyhifGtJPhySD0SJEzOIMhJWyifE9JX0GZzljpE+kDt8yl38LrZSpeLG2O2zMzXGt8acmCfNTBETArX0XjebJ+zvEYAMSYmhYRD7TUDR1ZROTPEph8WCyxYRdqvgOsI064jWqhNRf87FwL-E5MhzC38s1kXJLReknRXLQFBJpg8RALMsDvqMVMChDTZXbayWNb8-GT7qUGRriaorEWJHAkKM4cseoMCZEK914rw20ijcc5-bslmC2+J-U2mCI2hnma7erCl+SokxLmyCbbTnO18bUyg5jpYtvtpcF5sOWar4hBeXQMQIBqBAA) for how `config-standard` produces two violations:

```console
    6:3 error Expected empty line before at-rule (at-rule-empty-line-before)
    4:3 error Expected empty line before rule (rule-empty-line-before)
```

For:

```css
.parent {
  a {
  }
  b {
  }
  @media screen {}
}
```

> I tried this rule. but it only add new line between "at rules"

That's because the rule-sets in the example below are single-line:

```css
.parent {
    a {}
    b{}
    @media screen {}
  }
```

If you want empty lines between your single-line rules, then you need to change the primary option from `always-multi-line` to `always`, like so:

```js
  {
    "rule-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["after-comment"],
      },
    ]
  }
```
