### ISSUE TITLE
Add declaration-block-no-duplicate-custom-properties

### ISSUE THREAD

**Issue by voskresla** [stylelint/stylelint#5124]
> What is the problem you're trying to solve?

I think it would be better if this rule supports the ability to check CSS custom properties. For example we have color palette from designers with long complex naming. In this case, it is easy to make the mistake.

```css
:root {
  --companyBrandPaleRed: red;
  --companyBrandPaleRed: blue; // <- just wrong copy-paste
}
```

> What solution would you like to see?

I suggest a small optional addition to the existing rule options without breaking changes. 
```
'declaration-block-no-duplicate-properties': [true, {
	'lookAtCustomProperties': true,
}],
```

example PR: https://github.com/stylelint/stylelint/compare/master...voskresla:no-duplicate-properties-add-custom-properties

**Comment by jeddy3** [comment]
@voskresla Thanks for the request, for using the template and for rustling up an example PR!

We've so far split custom properties from normal properties in [our rules](https://stylelint.io/user-guide/rules/list) as they tend to have different behaviours.

I suggest we create a new rule rather than overload the [`declaration-block-no-duplicate-properties` rule](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties) with a new option.

We can use the [`declaration-block-no-duplicate-properties` rule](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties) as a blueprint, but we'll stripped it down as none of the [secondary options](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties#optional-secondary-options) are applicable to custom properties. For example, you may want to allow consecutive fallback properties, but this doesn't make sense for custom properties which have a different fallback mechanism:

```css
a {
  font-size: 16px;
  font-size: 1rem;
  color: var(--accent, red);
}
```

- Name: `declaration-block-no-duplicate-custom-properties`
- Primary option: `true`
- Secondary options: None
- Autofixable: No
- Message: `Unexpected duplicate "${custom-property}"`
- Description: "Disallow duplicate custom properties within declaration blocks."
- Section: "Possible errors" -> "Custom property"

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new rule](https://stylelint.io/developer-guide/rules#add-a-rule) in the Developer guide.
