### ISSUE TITLE
Add no-irregular-whitespace

### ISSUE THREAD

**Issue by jchiem** [stylelint/stylelint#5201]
### What is the problem you're trying to solve?
I've noticed that I sometimes end up typing a bit too fast when adding white spaces in my code when I've recently used alt or option key + space in Mac in VS Code (for example when adding a $ for a variable), this results in non-breaking spaces (&nbsp) being added to the code which look identical to regular white spaces, but when parsed through sass this causes issues since the output CSS still ends up getting a non-breaking whitespace and also an additional white space added from the parsing. 

I've also added a feature request for this in https://github.com/sass/dart-sass/issues/1265 but I think it makes sense to empower developers to be able to avoid writing irregular whitespace characters in the first place through a stylelint rule.

### What solution would you like to see?
A new rule for checking the code for irregular whitespace characters, similar to https://eslint.org/docs/rules/no-irregular-whitespace, this rule should probably not be applicable for `content: " ";` (where the space in content in this example is a non-breaking space.)

### Example:
https://codepen.io/jchiem/pen/dyOBpKW

**Comment by jeddy3** [comment]
@jchiem Thanks for the request, using the template and outlining your use case clearly.

> but when parsed through sass this causes issues since the output CSS still ends up getting a non-breaking whitespace and also an additional white space added from the parsing.

It probably causes issues with some stylelint rules too because [non-breaking spaces are parsed differently by PostCSS](https://astexplorer.net/#/gist/9c1e0cad4b7f63596b4d4d3be0497a93/6cef247429b6d6e856057828f323c3545655a8b0).

> A new rule for checking the code for irregular whitespace characters, similar to https://eslint.org/docs/rules/no-irregular-whitespace, 

A new rule sounds good to me, and the `no-irregular-whitespace` name aligns with [our conventions too](https://stylelint.io/user-guide/rules/about#names). Incidentally, I had no idea there is [so many irregular whitespace](https://eslint.org/docs/rules/no-irregular-whitespace#rule-details)!

> this rule should probably not be applicable for content: " "; (where the space in content in this example is a non-breaking space.)

Let's disallow irregular whitespace everywhere to begin with. The rule can be [made more permissive with options](https://stylelint.io/developer-guide/rules#write-the-rule) at a later date [if some requests it](https://stylelint.io/developer-guide/rules#add-options).

Blueprint:

- Name: `no-irregular-whitespace`
- Primary option: `true`
- Secondary options: None
- Autofixable: No 
- Message: "Unexpected irregular whitespace"
- Description: "Disallow irregular whitespace."
- Section: "Possible errors" -> "General / Sheet"

The rule is a candidate for the recommended config.

We'll want to check `atRule`, `decl` and comment nodes, including their `raws`.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new rule](https://stylelint.io/developer-guide/rules#add-a-rule) in the Developer guide.
