### ISSUE TITLE
Release 2.3.3 is not babelified

### ISSUE THREAD

**Issue by borodean** [stylelint/stylelint#525]
It has imports, arrow functions and stuff like that under the `dist` folder.

![image](https://cloud.githubusercontent.com/assets/1530865/11326319/67cf7f2a-916f-11e5-8f20-8cc36358627e.png)

**Comment by davidtheclark** [comment]
Dear god what happened ...

**Comment by davidtheclark** [comment]
Thanks for the report! Please give 2.3.4 a try, and if it works close the issue.

I believe that what happened was that I had Babel 6 installed locally because of working on the `v3` branch; then I published without re-installing Babel 5. For 2.3.4 I double-checked that my local `dist/` dir has es5.

**Comment by borodean** [comment]
@davidtheclark yeah, it's fine now. Thank you!
