### ISSUE TITLE
upgrade dependencies in order to avoid vulnerabilities

### ISSUE THREAD

**Issue by mykola-shkut** [stylelint/stylelint#5298]
after yarn audit I have 7 notification regarding vulnerabilities from postcss
![image](https://user-images.githubusercontent.com/50704732/118052514-906fbc80-b38b-11eb-95d9-bb59b7b264a2.png)
![image](https://user-images.githubusercontent.com/50704732/118052559-a2515f80-b38b-11eb-870b-05ecc3edb5d0.png)

could you fix it?

**Comment by hudochenkov** [comment]
It will be fixed once we migrate to PostCSS 8 https://github.com/stylelint/stylelint/issues/4942

**Comment by MaxKoldun** [comment]
> It will be fixed once we migrate to PostCSS 8 #4942

Hi, when are you going to migrate? I have the same problem.

**Comment by hudochenkov** [comment]
It's unknown. Because it's a lot of work. We need to migrate 200+ PostCSS plugins (every rule is PostCSS plugin). Help is always welcome.

**Comment by mykola-shkut** [comment]
fixed by this modufications
![image](https://user-images.githubusercontent.com/50704732/118127431-5d1c4480-b402-11eb-95cc-08387d38e2da.png)
I'm not sure that this is right 
but works for me )

**Comment by MaxKoldun** [comment]
It does not work with npm v7.10.0

**Comment by RopoMen** [comment]
Hi,

> It's unknown. Because it's a lot of work. We need to migrate 200+ PostCSS plugins (every rule is PostCSS plugin). Help is always welcome.

Could you define the "core" plugins that needs to be migrated to postcss8. And then make new release from stylelint. And after that migrate "not so core" plugins to support postcss8?

**Comment by jeddy3** [comment]
> And then make new release from stylelint. And after that migrate "not so core" plugins to support postcss8?

That's the plan.

It can be confusing because both Stylelint's [built-in rules](https://stylelint.io/user-guide/configure#rules) and [plugins](https://stylelint.io/user-guide/configure#plugins) are PostCSS plugins behind the scenes.

We can release once [all the 200+ built-in rules](https://github.com/stylelint/stylelint/tree/v14/lib/rules) are migrated to PostCSS 8. The community members can then migrate their plugins. As @hudochenkov said, https://github.com/stylelint/stylelint/issues/4942 is the issue for this migration. It is currently blocked by https://github.com/stylelint/stylelint/pull/5297 (see the discussion in https://github.com/stylelint/stylelint/issues/5289), but will be unblocked soon. 

Please consider contributing to any of the issues in the `14.0.0` tracking issues (https://github.com/stylelint/stylelint/issues/5205#issue-837034702). This is everything we need to do before releasing `14.0.0`.
