### ISSUE TITLE
how do i fix an error about deprecated rule?

### ISSUE THREAD

**Issue by charmjeh** [stylelint/stylelint#5478]
Hello,

How do i fix this error?
'**declaration-property-value-blacklist' has been deprecated. Instead use 'declaration-property-value-disallowed-list**'

I didn't intentionally set up this option but error message shows up when i run `yarn lint` commend

my stylelint version is `v13.13.1`

stylelint.config.js 
```
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-airbnb',
    'stylelint-config-prettier',
  ],
  plugins: ['stylelint-scss', 'stylelint-order'],
  // add your custom config here
  // https://stylelint.io/user-guide/configuration
  rules: {},
};
```

Thank you!

**Comment by jeddy3** [comment]
One of the sharable configs that you are extending is using the deprecated `declaration-property-value-blacklist` rule. I suspect it's `stylelint-config-airbnb`. There may be a more up to date version of that sharable config that you can install, otherwise you should remove it from your `extends` array.
