### ISSUE TITLE
Make engine code more straightforward

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#5529]
The stylelint code base has grown over time, especially around the engine. How can we untangle that part of the code to make it easier to add features, like `overrides`, in the future?

Is it something we can do iteratively through refactors or are more substantial changes needed? For example, if providing stylelint as a PostCSS plugin is a cause, then we could drop that in favour of just the Node API and CLI.

(Caveat: the engine is the part of stylelint that I know the least about. I focused on the rules, even from the very beginning.)

I believe @m-allanson's [pull request for the browser entry point](https://github.com/stylelint/stylelint/pull/4796#issue-421326478) (and the refactoring that came out of it) is the only work we've done to map out and refactor the internals before, so feel free to share which areas are problematic and any ideas you may have for untangling the code.

Ref: https://github.com/stylelint/stylelint/pull/5521#issue-732131887

**Comment by m-allanson** [comment]
Here's a couple of thoughts on this. From memory, so maybe inaccurate.

1. standalone.js is a good candidate for refactoring. The deep nested promises make it difficult to follow the logic. The module is essentially two different paths to:

```js
stylelint._lintsource().then(() => {
  return stylelint._createStylelintResult();
});
```
But it's quite tricky to follow the logic through.

A while ago I tried switching the promises over to use `await` instead. I made some progress before noticing intermittent failures in the cache tests. Some more debugging is needed on that (maybe this is fixed by https://github.com/stylelint/stylelint/pull/5533).

2. Processors. If it were possible to remove processors some of stylelint's internal logic could be simplified. Processors can modify code on the way in, and results on the way out.

I'm not up to date on processors, but maybe the following statements are true... Syntaxes replace processors? But the CSS-in-JS syntax lacks some features available in the styled-components processor? And the recent addition of `Document` nodes (in postcss) means it's now possible to create syntaxes to replace the styled components processor?

**Comment by jeddy3** [comment]
> A while ago I tried switching the promises over to use `await` instead.

Nice. That'd make it easier to grok what's going on in the file.

> And the recent addition of Document nodes (in postcss) means it's now possible to create syntaxes to replace the styled components processor?

Yes, we may be able to remove the deprecated processor functionality in favour of only using syntaxes in `14.0.0`.

**Comment by jeddy3** [comment]
As `standalone.js` and others were refactored in https://github.com/stylelint/stylelint/pull/5542, I'll convert this issue to removing support for processors. The goal is to have a single point of extension (custom-syntaxes) for dealing with non-CSS files.

**Comment by jeddy3** [comment]
Closing as we have an issue for that already: https://github.com/stylelint/stylelint/issues/3408
