### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by ASOS-DaliaBanerjee** [stylelint/stylelint#5740]
After upgrading stylelint from version `13.13.1` to `14.0.0`, when I run `stylelint '<path-to-css>' --fix`, I get this error -

```
TypeError: callback is not a function
    at success (<path>/node_modules/write-file-atomic/index.js:162:5)
error Command failed with exit code 1.
```

The version `13.13.1` runs without any trouble. Running on `Node 16.5.0`

My `.stylelintrc` looks like this -

```
{
  "extends": [
    "stylelint-config-standard"
  ],
  "rules": {
      "indentation": 2,
      "string-quotes": "double"
  }
}
```

And `package.json` looks like this -

```
    "stylelint": "14.0.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-standard": "^22.0.0"
```

**Comment by ybiquitous** [comment]
@ASOS-DaliaBanerjee Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
