### ISSUE TITLE
Stylelint error to lint vue files in 14.1.0

### ISSUE THREAD

**Issue by theolavaux** [stylelint/stylelint#5746]
I have a NuxtJS project using the SCSS syntax and recently migrated to use Stylelint 14.x because it was required by the VSCode extension.
I followed the [migration guide](https://stylelint.io/migration-guide/to-14/) but I still have a blocking error in my `.vue` file.

**Recap of my changes**

 - Installed the following packages

```
 "stylelint": "^14.1.0",
 "stylelint-config-recommended-vue": "^1.0.0",
 "stylelint-config-standard-scss": "^3.0.0",
 "postcss-html": "^1.3.0",
```
- Added the two new packages to the `stylelint.config.js`
```
 extends: [
    'stylelint-config-standard',
    'stylelint-config-prettier',
    'stylelint-config-recommended-vue', // NEW
    'stylelint-config-standard-scss', // NEW
    'stylelint-config-sass-guidelines',
    'stylelint-config-property-sort-order-smacss',
  ]
```
 
Lastly, I added these settings to my `settings.json` in VSCode

```
  "stylelint.snippet": ["css", "less", "postcss", "scss", "vue"],
  "stylelint.validate": ["css", "less", "postcss", "scss", "vue"],
```

Now, I have the following error

```
Unknown word (CssSyntaxError)
```

near this tag in a Vue template

`<span>{{ myVariable }}</span>`

If I remove .vue from the `stylelint.validate` array, the styling errors don't show in the .vue file anymore.

How could I solve this ?

Thanks for help ✌️

**Comment by jeddy3** [comment]
Can you try the following configs _in this specific order_, e.g.:

```
 extends: [
   'stylelint-config-standard-scss',
    'stylelint-config-recommended-vue',   
    'stylelint-config-property-sort-order-smacss',
    'stylelint-config-prettier', 
  ]
```
    
I believe the `CssSyntaxError` is because `stylelint-config-standard-scss` appears below `stylelint-config-recommended-vue` in your config, and it sets the `customSyntax` option to "postcss-scss", which can't parse vue files. 

Additionally:
- `stylelint-config-standard` isn't needed as it's included in `stylelint-config-standard-scss`
- `stylelint-config-prettier` should go last as it turns off any incompatible rules turned on in the previous configs
- `stylelint-config-sass-guidelines` may not be needed as `stylelint-config-standard-scss` contains many stylistic rules

**Comment by theolavaux** [comment]
Thanks for the quick reply! It works now!

**Comment by CodeLittlePrince** [comment]
It's my solution：
```js
// stylelint.config.js
module.exports = {
  'ignoreFiles': [
    '**/*.js',
    '**/*.md'
  ],
  'overrides': [
    {
      'files': ['**/*.(scss|css|html|vue)'],
      'customSyntax': 'postcss-scss'
    },
    {
      'files': ['**/*.(html|vue)'],
      'customSyntax': 'postcss-html'
    }
  ],
  'extends': 'stylelint-config-standard-scss',
}
```

It works good with the stylelint v1.2.1 plugin of vscode.
