### ISSUE TITLE
Add ignoreAfterCombinators: [] to ignore to selector-max-universal

### ISSUE THREAD

**Issue by ilyub** [stylelint/stylelint#5792]
### What is the problem you're trying to solve?

I guess that selector-max-universal is performance related rule.
I.e. it is supposed to forbid patterns that hit perfomance.

Consider the following patterns (with selector-max-universal = 1):
1. "*" involves O(N) search. So, it is Good.
2. "* *" involves O(N^2) search. So, it is Bad.
3. "* + *" involves O(N) search ("+ *" = next element = it does not require additional search). So, it is also Good and should not be reported.

### What solution would you like to see?

Add option Not to count "+ *"
because it does not require additional search and thus does not hit performance.

**Comment by jeddy3** [comment]
Thanks for the request and for using the template.

We can add a new `ignoreAfterCombinators: []` option that'll cover your use case. It'd also work for selectors like `.component > * {}` with `selector-max-universal: [0, { "ignoreAfterCombinators": [">"] }]`.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

> I guess that selector-max-universal is performance related rule.

Most of the [limiting rules](https://stylelint.io/user-guide/rules/list#limit-language-features) exist so that users can target constructs and apply limits for whatever reason they want. There usually isn't a specific reason behind them.

**Comment by jeddy3** [comment]
> I am not familiar with stylelint project internals to work on it myself

[These are steps on how to get started](https://stylelint.io/contributing). There's a [similar option](https://stylelint.io/user-guide/rules/list/selector-max-id/#ignorecontextfunctionalpseudoclasses-regex-regex-non-regex) for the [selector-max-id rule](https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-id/index.js) that you can use as a blueprint. The API for the selector parser [is available here](https://github.com/postcss/postcss-selector-parser/blob/HEAD/API.md).

**Comment by shuta13** [comment]
@jeddy3 cc @ilyub 

Can I work on this issue?

**Comment by jeddy3** [comment]
@shuta13 Yes, please go ahead. If an issue is labelled "status: ready to implement" and doesn't have an open pull request against it, anyone can pick it up.
