### ISSUE TITLE
Stylelint working with Rupture variables (+above, +below)

### ISSUE THREAD

**Issue by mymrtt** [stylelint/stylelint#5989]
### What is the problem you're trying to solve?

Today, what happens is, when I add a [Rupture](https://jescalan.github.io/rupture/) variable (+above, +below), it doesn't know this variable. And so far, so good.

The problem is, when Stylelint does the autofix, it adds space after the variables, breaking them.

How it is:
```
+above (sm) {
  ....
}
```

### What solution would you like to see?

How it should be:
```
+above(sm) {
 ...
}
```

What I need is that it doesn't add space after these variables

**Comment by jeddy3** [comment]
@mymrtt Thank you for opening the issue.

Can you create a new issue using the [bug report template](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REPORT_A_BUG.yml) instead, please? So that we capture more details, e.g. your config, stylelint version etc. It'd be great if you could reduce your config down as far as possible so that we can narrow in on which rule is causing the problem.
