### ISSUE TITLE
Rules not working with CSS in JS syntax

### ISSUE THREAD

**Issue by Alecell** [stylelint/stylelint#5990]
### What steps are needed to reproduce the bug?

I'm trying to use stylelint longside with EmotionJS, but almost no rules work, the only error I manage to get was `Unknown word CssSyntaxError`, but after I add the fix for that, no error throw as all.

1. Install nextjs project with `npx create-next-app@latest --ts`
2. Install EmotionJS with `yarn add @emotion/react`
3. Create `.babelrc` file
4. Add emotion config to make the emotion `css prop` work on JSX
```json
{
  "presets": [
    [
      "@babel/preset-react",
      { "runtime": "automatic", "importSource": "@emotion/react" }
    ]
  ],
  "plugins": ["@emotion/babel-plugin"]
}
```
5. Install stylelint as [docs](https://stylelint.io/user-guide/get-started) suggest, I use `yarn` so I go with `yarn add stylelint stylelint-config-standard -D`
6. Create `.stylelintrc.json` file as docs suggest
7. Create a style file called `test.styles.ts`
8. Add emotionjs code with syntax errors inside the styles file
```ts
import { css } from '@emotion/react';

export const container = (color: string) => css`
  background-color: #000;
  padding: 32px;
  border-radius: 4px;
  font-size: 24tz;
  batata: sim;
  content: 'sssm';

  .umaCOi0-sim {
    color: red;
  }

  &:holver {
    color: ${color};
  }
`;
```
9. Run `npx stylelint "**/*.styles.ts"` and notice the `Unknown word  CssSyntaxError` error
10. Install the _CSS in JS_ custom syntax with `yarn add postcss-syntax @stylelint/postcss-css-in-js -D`
12. Add `"customSyntax": "@stylelint/postcss-css-in-js"` on `.stylelintrc` 
13. Run the command `npx stylelint "**/*.styles.ts"` and notice that the `Unknown word  CssSyntaxError` error don't show anymore, but nothing returns from the command
14. Add a pretty simple rule `"rules": { "string-quotes": "double" }`
15. Run the command again and notice that it still don't throw any errors

### What Stylelint configuration is needed to reproduce the bug?
```json
{
  "extends": "stylelint-config-standard",
  "customSyntax": "@stylelint/postcss-css-in-js",
  "rules": {
    "string-quotes": "double"
  }
}
```

### How did you run Stylelint?

`npx stylelint "**/*.styles.ts"`

### Which version of Stylelint are you using?

`^14.6.1`

### What did you expect to happen?

The extended standards and the added rule should work and throw errors when the command is fired as we have a file with a lot of errors.

### What actually happened?

Nothing happens, after run the command there's no response from the console, I believe it acts like the code is linted

### Does the bug relate to non-standard syntax?

Yes, its related to a CSS in JS syntax

**Comment by jeddy3** [comment]
@Alecell Thanks for the detailed report and for using the template.

This is likely an issue with the custom syntax rather than Stylelint itself. Custom syntaxes are written by the broader community to transform CSS-like languages (like SCSS and Less etc) and CSS containers (like HTML, CSS-in-JS template literals etc) into something Stylelint understands. 

The `@stylelint/postcss-css-in-js` package isn't maintained anymore and [will be deprecated](https://github.com/stylelint/postcss-css-in-js/issues/225). The recommended path forward is to take the more modern (i.e. based on PostCSS's 8 `Document` node) [postcss-lit](https://github.com/43081j/postcss-lit) package, tailor it for Emotion JS, release postcss-emotion and then use that with Stylelint.

If you do release postcss-emotion, please let us know so that we can add it to the list of compatible custom syntaxes in the [getting started guide](https://stylelint.io/user-guide/get-started).
