### ISSUE TITLE
Configured rules that are no longer available to be removed or to be updated.

### ISSUE THREAD

**Issue by amarg26** [stylelint/stylelint#6138]
### What is the problem you're trying to solve?

Removing or updating the below rules which are no longer available.

1. at-each-key-value-single-line
2. at-function-named-arguments
3. at-import-partial-extension-blacklist
4. media-feature-value-dollar-variable
5. no-duplicate-dollar-variables
6. partial-no-import
7. selector-nest-combinators
8. selector-no-redundant-nesting-selector
9. selector-no-union-class-name
10. double-slash-comment-inline
11. map-keys-quotes
12. at-mixin-named-arguments
13. comment-no-loud
14. dimension-no-non-numeric-values
15. function-color-relative

I have Identified this by using the below commands

```
        "stylelint-check": "stylelint-config-prettier-check",
        "stylelint-find-rules": "stylelint-find-new-rules -c"
```

### What solution would you like to see?

Would like to see either update all the rules else remove those rules.

**Comment by ybiquitous** [comment]
@amarg26 Thanks for using the template.

I'm not sure about `stylelint-config-prettier-check` and `stylelint-find-new-rules`, but it seems they report for `stylelint-scss` rules instead of `stylelint` ones.

For example, `at-each-key-value-single-line` is a rule of `stylelint-scss`, not one of `stylelint`:
https://github.com/stylelint-scss/stylelint-scss/blob/1c65d3c0ce016a66b0c656ce153aa1636253484b/src/rules/at-each-key-value-single-line/README.md

**Comment by amarg26** [comment]
@ybiquitous  Yes, It is related to `stylelint-scss` . Will divert this same to them. Thanks for this. 😄

**Comment by ybiquitous** [comment]
@amarg26 OK. Then, could you please file an issue on the [stylelint-scss/stylelint-scss](https://github.com/stylelint-scss/stylelint-scss) repository?

In addition, I think `stylelint-scss` maintainers would feel helpful if you could provide a small reproduction repository for that issue.

**Comment by amarg26** [comment]
@ybiquitous I have filed the same issue to them referencing the same discussion. 
[https://github.com/stylelint-scss/stylelint-scss/issues/611](url)

If I get time, I will create a reproduction repository for the issues.
