### ISSUE TITLE
Add option "comments only" to max-line-length rule

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#617]
Currently the [max-line-length](https://github.com/stylelint/stylelint/tree/master/src/rules/max-line-length) rule applies to both code and comments, adding an option to allow the rule for only comments would be helpful.

The scenario I'm looking at is: _"Long comments should manually break the line length at 80 characters."_

**Comment by jeddy3** [comment]
FYI, there [was a discussion](https://github.com/stylelint/stylelint/issues/409) around how flexible we make this rule. Adding an option for only comments might, arguably, be the most useful of the suggestions in that original discussion—I'd certainly add it to `stylelint-config-suitcss` as it's explicitly mentioned in the [coding style](https://github.com/suitcss/suit/blob/master/doc/STYLE.md#41-comments)?

@davidtheclark Am I right in thinking that, because `max-line-length` uses `styleSearch()`, comments can be easily _excluded_? But there's no current param to search _only within comments_?

**Comment by ntwb** [comment]
I forgot to include the link originally but my source for this was the WordPress [CSS coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#commenting).

I was going to originally suggest a new rule `comment-max-line-length` but thought the option within `max-line-length` may make more sense, after reading that previous discussion I'm still not sure, pros and cons for each.

**Comment by davidtheclark** [comment]
Yes, I think this would be a good addition.

So far I don't use this rule myself because the length of my lines is really determined by where I'm requiring newlines. But with this change I would start using the rule, because limiting comment line length is what I'd really want.

@jeddy3 I *think* that there's not already an easy way to do this but it shouldn't be a huge pain to write.

**Comment by davidtheclark** [comment]
I'll do this one this weekend and get it into v4.

**Comment by jeddy3** [comment]
Thanks! I'll be adding it to `config-suitcss`.

**Comment by jeddy3** [comment]
@ntwb FYI, released in `4.0.0`. So you'll need to do a `npm i stylelint@latest`.

**Comment by ntwb** [comment]
:+1: Thanks @jeddy3 and @davidtheclark :smiley:
