### ISSUE TITLE
Formatting issue with maps

### ISSUE THREAD

**Issue by stevancorre** [stylelint/stylelint#6172]
### What steps are needed to reproduce the bug?

This is simple, when you have a comment before a map declaration inside another map, the formatter get crazy
```scss
$map-1: (
    submap-1: (
        property: value
    ),

    // comment
    submap-2: (
        property: value
    ),
)
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
    "extends": [
        "stylelint-config-standard-scss",
        "stylelint-prettier/recommended"
    ],
    "rules": {
        "no-empty-source": null,
        "indentation": [
            4,
            {
                "baseIndentLevel": 1
            }
        ],
        "declaration-empty-line-before": [
            "never",
            {
                "ignore": [
                    "after-comment",
                    "after-declaration"
                ]
            }
        ]
    }
}
```

### How did you run Stylelint?

CLI with `stylelint src --fix`

### Which version of Stylelint are you using?

`14.9.0`

### What did you expect to happen?

```scss
$map-1: (
    submap-1: (
        property: value,
    ),
    
    // comment
    submap-2: (
        property: value,
    ),
)
```

### What actually happened?

```scss
$map-1: (
    submap-1: (
        property: value,
    ),
    
    submap-2:
        (
                lue,
        ),
)    
```

### Does the bug relate to non-standard syntax?

related to scss nested properties

**Comment by jeddy3** [comment]
@stevancorre Thanks for the report and for using the template.

The stylistic rules are now frozen so that Stylelint is focused on helping you avoid errors and enforce non-stylistic conventions in your code, such as limiting what units can be used. [We now recommend](https://stylelint.io/user-guide/rules/list#stylistic-issues) using a pretty printer alongside Stylelint. Alternatively, if you wish to continue using the Stylelint to enforce things like whitespace conventions, you can migrate the code [to a plugin](https://stylelint.io/developer-guide/plugins) and fix the bug there. See also https://github.com/stylelint/stylelint-config-standard/issues/244#issuecomment-1161977445.
