### ISSUE TITLE
Formatting and wrapping of inline styles

### ISSUE THREAD

**Issue by dumplingbao** [stylelint/stylelint#6214]
### What is the problem you're trying to solve?

How to ignore inline styles when formatting inline styles and automatically wrapping lines frequently

<img width="400" alt="iShot2022-07-22 16 58 55" src="https://user-images.githubusercontent.com/32701202/180403862-38ad01b5-bfdc-4dfe-b47b-e42a2afaa772.png">

### What solution would you like to see?

Ignore or other methods.

**Comment by jeddy3** [comment]
@dumplingbao Thanks for the request and for using the template.

This is related to [custom syntaxes](https://stylelint.io/user-guide/usage/options#customsyntax) (in particular,  [postcss-html](https://github.com/ota-meshi/postcss-html)), rather than Stylelint itself. 

I suggest opening an issue in the [postcss-html tracker](https://github.com/ota-meshi/postcss-html) to see if they can support different rules for inline styles. 

You're welcome to reopen this issue if the syntax authors need us to make changes to Stylelint itself to facilitate the feature. 

---

The request follows on from https://github.com/stylelint/stylelint/issues/3128. As an aside, it feels less pressing now as [we no longer recommend using stylistic rules](https://stylelint.io/user-guide/rules/list#stylistic-issues) which users may want to configure differently for inline styles.
