### ISSUE TITLE
Rule conflict for `grid-template-areas`

### ISSUE THREAD

**Issue by ConduciveMammal** [stylelint/stylelint#6254]
### What steps are needed to reproduce the bug?

Create a multi-line `grid-template-areas` rule.

```css
grid-template-areas:
  "content"
  "action";
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": ["@shopify/stylelint-plugin"],
  "plugins": ["stylelint-prettier", "stylelint-selector-bem-pattern"],
  "rules": {
    "indentation": 2,
    "string-quotes": "double",
    "no-duplicate-selectors": true,
    "color-no-hex": null,
    "color-hex-case": "lower",
    "color-named": "never",
    "color-hex-length": null,
    "selector-combinator-space-after": "always",
    "selector-attribute-quotes": "always",
    "selector-attribute-operator-space-before": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-brackets-space-inside": "never",
    "declaration-block-trailing-semicolon": "always",
    "declaration-colon-space-before": "never",
    "declaration-colon-space-after": "always",
    "number-leading-zero": "always",
    "function-url-quotes": "always",
    "font-weight-notation": "numeric",
    "font-family-name-quotes": "always-where-recommended",
    "comment-whitespace-inside": "always",
    "comment-empty-line-before": "always",
    "at-rule-no-vendor-prefix": true,
    "at-rule-disallowed-list": null,
    "rule-empty-line-before": "always",
    "selector-pseudo-element-colon-notation": "double",
    "selector-pseudo-class-parentheses-space-inside": "never",
    "media-feature-range-operator-space-before": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-parentheses-space-inside": "never",
    "media-feature-colon-space-before": "never",
    "media-feature-colon-space-after": "always",
    "selector-no-qualifying-type": null,
    "scss/dollar-variable-pattern": "^[a-z]+([a-z0-9-]+[a-z0-9]+)?$",
    "order/properties-alphabetical-order": null,
    "selector-class-pattern": null,
    "selector-max-class": 3,
    "selector-max-id": 1,
    "selector-type-no-unknown": [
      true,
      {
        "ignore": ["custom-elements"]
      }
    ],
    "max-nesting-depth": [3, {
      "ignore": ["pseudo-classes"]
    }],
    "plugin/selector-bem-pattern": {
      "preset": "bem",
      "componentName": "[A-Z]+",
      "componentSelectors": {
        "initial": "^\\.{componentName}(?:-[a-z]+)?$",
        "combined": "^\\.combined-{componentName}-[a-z]+$"
      },
      "utilitySelectors": "^\\.util-[a-z]+$"
    }
  }
}
```

Sorry about the full block, I'm a little unsure about any of them having an effect in this instance.

### How did you run Stylelint?

VSCode plugin and Node

### Which version of Stylelint are you using?

14.10.0

### What did you expect to happen?

For it to finalise to a valid entry.

### What actually happened?

Stylelint warns about a space being needed after the `:`, after adding that space, it continues to tell you to add the space and also adds a new warning _Expected newline after ":" with a multi-line declaration (declaration-colon-newline-after)_. After adding that new line it continues to provide those warnings.

<img width="648" alt="CleanShot 2022-08-11 at 12 49 53@2x" src="https://user-images.githubusercontent.com/18140157/184127043-0ef1ed74-b059-4fc4-a69a-766b52425f37.png">

### Does the bug relate to non-standard syntax?

SCSS, CSS Grid

**Comment by ybiquitous** [comment]
@ConduciveMammal Thanks for using the template.

I'm not sure which shared configs set [`declaration-colon-newline-after](https://stylelint.io/user-guide/rules/list/declaration-colon-newline-after)` and https://stylelint.io/user-guide/rules/list/declaration-colon-space-after, but [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilBzATgJZQC0ALjALYAOANkhSUvjEgM7wpY47rgSYKgvtx58kYMoQF8A3FgC+IADQg2AT0FIAHgnBs2K-pgBmhXHozYuIfAFdaMNn05WeN2GHr4G0zCUhaARJMGAB3WkJQphMKfBcbJFowpHU2EkoHKRJI0L5lUV4QT29fYMDgtmoJGBi4hPFk1OcQUQVFEAUgA) may reproduce it:

```css
a {
  grid-template-areas: 
    "content"
    "action";
}
```

```json
{
  "rules": {
    "declaration-colon-newline-after": "always-multi-line",
    "declaration-colon-space-after": "always"
  }
}
```

To avoid conflict, the following setting seems correct:

```diff
{
  "rules": {
    "declaration-colon-newline-after": "always-multi-line",
-   "declaration-colon-space-after": "always"
+   "declaration-colon-space-after": "always-single-line"
  }
}
```

Could you please confirm it? If there are no problems, please close this issue.

---

FYI, these rules are *stylistic* and we've recommended using a pretty printer like [Prettier](https://prettier.io/) instead of such Stylelint rules, because we may not support such rules in the future. See the ["Stylistic issues"](https://stylelint.io/user-guide/rules/list#stylistic-issues) section in our documentation.

**Comment by ConduciveMammal** [comment]
Hey @ybiquitous! Thanks very much for that, that seemed to do the trick
