### ISSUE TITLE
Translation / article on creating new stylelint rules

### ISSUE THREAD

**Issue by fpetrakov** [stylelint/stylelint#6293]
Hi there, what do you think about me writing an article / translation of your [guide for developing rules](https://stylelint.io/developer-guide/rules/) in russian? Will it be okay if then I publish it on my website? I think It will also include some details of how stylelint works internally, what is AST and etc. This way I can encourage more developers to contribute to stylelint and open source in general

**Comment by jeddy3** [comment]
You're more than welcome to write an article about developing Stylelint rules/plugins in Russian (or whatever language you like), and publish it on your website. It may be helpful to date your article so that people can work out how up-to-date the information in your article is. (A few years ago, someone translated many of the articles in [the guides](https://stylelint.io/#guides) into Chinese, but they quickly became out-of-date.)

Once you've published your article you can send a pull request to the [tutorials sections](https://github.com/stylelint/awesome-stylelint#tutorials) so that other people can quickly discover it.
