### ISSUE TITLE
Stylelint: typeError: [configExtends].flat is not a function in the IDE (while stylelint works fine on the CLI)

### ISSUE THREAD

**Issue by openmindculture** [stylelint/stylelint#6300]
### What steps are needed to reproduce the bug?

Create a project in WebStorm / PHPStorm,
install Stylelint, stylelint-config-recommended,
add rules as described in the configuration plugin documentation,
open a .css file in the IDE.

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": "stylelint-config-recommended",
  "rules": {
    "alpha-value-notation": null,
    "color-function-notation": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "keyframes-name-pattern": null,
    "media-feature-name-no-vendor-prefix": null,
    "property-no-vendor-prefix": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-not-notation": null,
    "shorthand-property-no-redundant-values": null,
    "string-quotes": null,
    "value-list-comma-space-after": null,
    "value-no-vendor-prefix": null
  }
}

### How did you run Stylelint?

automatical default integration of PhpStorm 2022.2.1

### Which version of Stylelint are you using?

14.11.0

### What did you expect to happen?

No error message in the CLI.

### What actually happened?

Error message in the CLI in a red line above my css file: "Stylelint: typeError: [configExtends].flat is not a function"

### Does the bug relate to non-standard syntax?

no

### Proposal to fix the bug

Either add backward compatibility or document how to migrate project / editor configurations to use the latest stylelint as installed by npm when not specifying any version number.

As a workaround, I consider switching back to an older Stylelint release.

I want to thank everyone for doing valuable open source work!
I do not want to complain, but I wanted to open this issue as there is currently no helpful documentation on the internet when searching for the error message (neither on Google, nor Ecosia / Bing).

**Comment by ybiquitous** [comment]
@openmindculture Thanks for using the template and providing the details.

It seems older Node.js runtimes like v10 cause the error because [`Array.prototype.flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) has been added on Node.js v11.
(FYI, [Stylelint v14.0.0](https://github.com/stylelint/stylelint/releases/tag/14.0.0) has dropped the support of Node.js v10)

Also, it seems hard to revert the code compatible with older Node.js versions because the new API has been used already in many places (other APIs would be similar):

```console
$ git grep -w 'flat()' lib/ | wc -l
      19
```

I'm unfamiliar with PHPStorm IDE, so could you please provide more information about Node.js runtime in your environment?

**Comment by openmindculture** [comment]
Thanks for your reply! My node version is 16.10.0, both in my regular console, and in the terminal integrated in PHPStorm.
I should file a but at JetBrains YouTrack as it seems to be a PHPStorm problem then.

**Comment by jeddy3** [comment]
> I should file a but at JetBrains YouTrack as it seems to be a PHPStorm problem then.

Yes, if the issue isn't reproducible with the CLI it's likely a problem with the integration.

**Comment by openmindculture** [comment]
Follow-up issue at JetBrains YouTrack: https://youtrack.jetbrains.com/issue/WI-68577/Stylelint-typeError-configExtendsflat-is-not-a-function
