### ISSUE TITLE
Indentation rule add spaces to the URL

### ISSUE THREAD

**Issue by Gudleiv** [stylelint/stylelint#6378]
### What steps are needed to reproduce the bug?

1. Use stylelint with indentation rule
2. Make CSS at-rule font-face with multiple urls separated by commas
3. Add comment after each url (to label it, e.g)
4. Run stylelint to fix

Repo for reproducing the bug - [https://github.com/Gudleiv/stylelint-indentation](https://github.com/Gudleiv/stylelint-indentation)

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  rules: {
    indentation: 2,
  },
};

```

### How did you run Stylelint?

npx stylelint --fix "**/*"

### Which version of Stylelint are you using?

14.13.0

### What did you expect to happen?

I was expecting the correct indentation of the line after autofix

### What actually happened?

The url was broken and the comment was deleted

**Comment by jeddy3** [comment]
@Gudleiv Thanks for the report, using the template and for creating a reproducible repo.

We've [frozen the stylistic rules](https://stylelint.io/user-guide/rules/list#stylistic-issues). We [now recommend](https://stylelint.io/#how-itll-help-you) using a [pretty printer alongside Stylelint, such as Prettier](https://stylelint.io/user-guide/get-started). Alternatively, if you wish to continue using Stylelint for enforcing stylistic conventions (rather than for only [avoiding errors](https://stylelint.io/user-guide/rules/list#avoid-errors) and [enforcing non-stylistic conventions](https://stylelint.io/user-guide/rules/list#enforce-conventions)) you can [port the rule to a plugin](https://stylelint.io/developer-guide/plugins) and fix the bug there.
