### ISSUE TITLE
Discussion about declaration-block-semicolon-space-before and new lines

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#648]
```css
body {
  background:
    linear-gradient(
      120deg,
      color(#bfd8ee a(.95)) 20%,
      color(#cbc3f7 a(.95))
    ) fixed,
    url("https://farm7.staticflickr.com/6017/5963681346_0d620eff9a_z.jpg")
    50% 50% / cover no-repeat fixed
  ;
}
```

My css is weird, I know. But I like short lines, and when I have such a thing, I like to break the line in pieces, and to "end this", I use the semicolon on a new line, indented with the property name.
Should "declaration-block-semicolon-space-before" handle this kind of case? (like ignoring if there is a new line in the "space" ?

**Comment by davidtheclark** [comment]
Can you get this enforced with a combination of declaration-block-semicolon-space-before and declaration-block-semicolon-newline-before, using the single- and multi-line keywords?

**Comment by davidtheclark** [comment]
@jeddy3 : Looking back on this rule group I'm a little confused. Do you have any recollection of why it's `declaration-block-semicolon-`, where single/multi-line distinction is determined by the whole block, instead of `declaration-semicolon-*`, where the distinction is determined by the declaration itself?

I think I'd prefer to have it the other way (scoped to the declaration, not the block); and I think that would also enable @MoOx to do his weird thing. Whereas if the rule is scoped to the whole block, you're not allowed to do semicolons differently from decl to decl.

**Comment by jeddy3** [comment]
> Do you have any recollection of why it's declaration-block-semicolon-*, where single/multi-line distinction is determined by the whole block

Aww man. This is going to require a little trip down memory lane and bit of head scratching. 

I think the rule was originally written with the following use in mind:

```css
a { top: 1px; bottom: 5px; }
b { top: 5px; bottom: 2px; }
c { top: 2px; bottom: 2px; }

d {
  margin: 0;
  color: red;
}
```

In this instance the following config would enforce, when it's a single line declaration block, a single space after each semi and no space before each one. And enforce, when it's a multi-line declaration block, a newline after and no space before:

```json
{
  "declaration-block-semicolon-space-after": "always-single-line",
  "declaration-block-semicolon-space-before": "never",
  "declaration-block-semicolon-newline-after": "always-multi-line"
}
```

> I think I'd prefer to have it the other way (scoped to the declaration, not the block); and I think that would also enable @MoOx to do his weird thing

We could change it and no longer support the above use case. Another option is having two sets of `semicolon-*` rules; one for declarations and another for declaration blocks. The two rules would conflict of course, and so it'll be down to the user to decide which use case they wished to check for. We'll need to be careful in the documentation to explain the distinction between and the use case of each set.

P.S. taking this trip down memory lane has reminded me that we might want to revisit the grouping of the `rule-*`, `block-*` and `declaration-block-*` rules for `v5`. I'll have a think about that and start a separate issue.

**Comment by davidtheclark** [comment]
The name `declaration-block-semicolon-space` kind of bothers me, because the semicolon is not actually a quality of the declaration block, right? Or is it? 

Well either way that sparked another idea: create a `declaration-semicolon-space-*` rule set and add give it a couple of special keywords. `"always-single-line"` would mean a single-line declaration; but `"always-single-line-block"` would mean a single-line block.

Just another possibility.

**Comment by davidtheclark** [comment]
Or it could just be `semicolon-space-*` right? Because the semicolon is actually its own thing, separating declarations?

**Comment by jeddy3** [comment]
This is quite the head scratcher...

> because the semicolon is not actually a quality of the declaration block, right? Or is it?

FYI, when I originally named the rule I looked to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#CSS_declarations_blocks), which says that it is... :frowning: 

That's no so important though as I think we've transitioned to naming things based on their _scope_, rather than the thing they are _attached to_ (although quite often these are one and the same). This transition makes sense to me, as I think that easily knowing the scope is more useful to the user because it brings a obvious and consistent meaning to the `*-single-line` and `*-multi-line` keywords. Which brings me to...

> Well either way that sparked another idea: ... Or it could just be `semicolon-space-*` right?

I'm not sure about `semicolon-space-*` as I think the issue here is that we would lose that consistency. Perhaps `declaration-semicolon-*` will work though as the scope is right for `always/never-single-line`, and then we have obvious special keywords (`always/never-single-line-block` etc...) when we break with the convention.

And finally, the obligatory question about whether this is worth the effort for an edge case? The only rule Maxime needs to turn off currently is `declaration-block-semicolon-space-before` as `declaration-block-semicolon-newline-after`still works in this edge-case.

Decisions decisions... :)

**Comment by jeddy3** [comment]
Or, just thought of this based on your original idea...

`declaration-block-semicolon-space: always/never-single-line | always/never-multi-line | always/never-single-line-declaration | always/never-multi-line-declaration`

Pros:

1. Consistent with scope naming conventions.
2. Clearly named additional special keywords.
3. No breaking change.
4. (Although, like I said above, no so important) Attaches to the thing in the spec.

?

**Comment by davidtheclark** [comment]
I like the suggestion in this last comment. I say we close this issue and
open another one for adding always/never-single-line-declaration, etc.,
primary options to the existing rules.

**Comment by jeddy3** [comment]
Thinking and working aloud... 

This style:

```css
a {
  background:
    linear-gradient(
      120deg,
      color(#bfd8ee a(.95)) 20%,
      color(#cbc3f7 a(.95))
    ) fixed,
    url("https://farm7.staticflickr.com/6017/5963681346_0d620eff9a_z.jpg")
    50% 50% / cover no-repeat fixed
  ;
  color: red;
}

b { top: 0; right: 0; }
```

Can be enforced with:

```json
{
  "declaration-block-semicolon-newline-after": "always-multi-line",
  "declaration-block-semicolon-newline-before": "always-multi-line-declaration",
  "declaration-block-semicolon-space-after": "always-single-line", 
  "declaration-block-semicolon-space-before": "never-single-line-declaration"
}
```

@davidtheclark Does that look right to you? As it looks good to me. If so, I'll go ahead and create that new issue and close this one.

As an aside; it's kind of a testament to flexibility of the naming conventions and approach that such a style can be supported with the addition of a couple of options huh? :)

**Comment by davidtheclark** [comment]
@jeddy3: Yes, that looks good to me.
