### ISSUE TITLE
Better warning if non-object is passed as secondary option

### ISSUE THREAD

**Issue by TrySound** [stylelint/stylelint#650]
https://github.com/stylelint/stylelint-config-cssrecipes/issues/8

**Comment by davidtheclark** [comment]
What is the request here?

**Comment by TrySound** [comment]
@davidtheclark We should inform about using unexpected configuration
```
indentation: [2, 2]
```
throws that error.
Need to validate both array elements more carefully.

**Comment by davidtheclark** [comment]
We dropped support for numbered severities on purpose, providing deprecation notices in v3 and now dropping it in v4. I don't think we'd want to build in exceptions for that syntax. But we could try to modify the option validator so that if secondary options are passed and are not an object, you get an error that tells you "Secondary options should be an object", or something.

**Comment by TrySound** [comment]
@davidtheclark Yes, we should. in cssrecipes it was skipped and made problems.
