### ISSUE TITLE
Setting spaces around the slash separator of shorthand property values

### ISSUE THREAD

**Issue by firefoxic** [stylelint/stylelint#6530]
### What is the problem you're trying to solve?

Lack of uniformity in writing shorthand values ​​with a slash separator.

Сould not find how to do this with the existing rules.

### What solution would you like to see?

Error indication and autofix:

```diff
.class::before {
-	grid-area: 1/2/2/3;
+	grid-area: 1 / 2 / 2 / 3;
-	background: url("icon.svg") no-repeat center/contain;
+	background: url("icon.svg") no-repeat center / contain;
}

It might make sense to have a separate setting for spaces before and after the slash separator.

**Comment by ybiquitous** [comment]
@firefoxic Thanks for the suggestion. Indeed, there is no rule about spaces around a slash separator, but we are [not focused on stylistic conventions](https://stylelint.io/user-guide/rules#enforce-stylistic-conventions). So I believe such a rule should be [implemented as a plugin](https://stylelint.io/developer-guide/plugins) instead of the core.

Any thoughts?

**Comment by firefoxic** [comment]
Well, after all, for example, spaces after colons are also stylistic conventions, the code works without a space. Is not it so?

**Comment by jeddy3** [comment]
> but we are [not focused on stylistic conventions](https://stylelint.io/user-guide/rules#enforce-stylistic-conventions). So I believe such a rule should be [implemented as a plugin](https://stylelint.io/developer-guide/plugins) instead of the core.

This is correct. 

@firefoxic We'll be [deprecating most of our stylistic rules](https://github.com/stylelint/stylelint/blob/v15/docs/migration-guide/to-15.md) in the next major release. You can either write a plugin for Prettier or Stylelint to enforce space around slashes. Stylelint's built-in rules will focus on helping you [avoid errors](https://stylelint.io/user-guide/rules#avoid-errors) and [enforce (non-stylistic) conventions](https://stylelint.io/user-guide/rules#enforce-non-stylistic-conventions) going forward.

**Comment by firefoxic** [comment]
> We'll be [deprecating most of our stylistic rules](https://github.com/stylelint/stylelint/blob/v15/docs/migration-guide/to-15.md?rgh-link-date=2022-12-23T16%3A07%3A57Z) in the next major release.

Oh... I can only hope that before this impending ditching of such rules, someone will write plugins that will replace the existing stylistic convention rules. Otherwise, it will be a very difficult transition. Personally, I'm not sure that I have the resources to write plug-ins for all those stylistic conventions that are already in the form of rules and that I need as a students mentor.

**Comment by jeddy3** [comment]
> someone will write plugins that will replace the existing stylistic convention rules

We won't remove the rules until the next major release. We'll only be deprecating them in the upcoming one. Hopefully, by the next major release members of the community will have ported the rules they need to plugins.

However, this may not happen as we are recommending people use a pretty-printer like Prettier alongside Stylelint rather than use Stylelint for enforcing stylistic convention as its better to pretty-print an AST (based on the line length) than try to fix formatting issues using standalone lint rules. The latter approach tends to introduce further lint problems.

Stylelint will focus on helping you and your students avoid errors and enforce non-stylistic conventions in your code. We already have over 100 built-in rules that do this (most of which are unique to Stylelint) and there are many more to write.
