### ISSUE TITLE
Add ignore: ["descendants", "compounded"] options to selector-no-type

### ISSUE THREAD

**Issue by kangax** [stylelint/stylelint#662]
`selector-no-type` is great for disallowing type selectors but I wish it could be made a little more flexible. For example, `li` alone is bad, but occasional `.my-module__component__sub-component li` is not so bad. `selector-no-type` currently flags the latter one as well. I'm not yet entirely sure what the extra option should be. Perhaps, `{ "selector-no-type": "except-descendent" }` in which case `div` would fail but `.foo div` would work. Not sure about `div .foo` but I'm inclined to think that it should fail as well. In other words, a type selector is too generic on its own but not when it's scoped. Perhaps the option should then be "except-scoped". However, scoping with another type selector is still no good — `ul li` :) 

So... I thought about specificity as one of the possible ways to solve this whole thing. Anything less than 10 means that it's too generic — `div` (1), `div a` (2), `ul li span` (3) and so on. Anything "scoped" is >10 and so should pass — `.foo div` (11), `div .foo` (11), `div.bar`.

I might end up doing a custom plugin for this but wanted to put it out there as one of the possible additions.

**Comment by jeddy3** [comment]
Another interesting one.

FYI, I think the `selector-no-*` rules were designed for the simplest use cases. A little later down the line two `selector-*-pattern` rules ([`selector-id-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-id-pattern/README.md) & [`selector-class-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-class-pattern/README.md)) were added. Perhaps something like `selector-complex-pattern`, as in a _complex selector_, would cover off your use case while also providing a bit of flexibility. I haven't really thought it through though... just throwing the suggestion out there :)

> I might end up doing a custom plugin for this but wanted to put it out there as one of the possible additions.

If, on further investigation, something generic like `selector-complex-pattern` doesn't meet you needs and you end up doing a plugin, I'll point you in the direction of @davidtheclark's [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern) plugin as you might some some useful stuff in there :)

**Comment by davidtheclark** [comment]
@kangax: I agree with @jeddy3 that you could try `selector-complex-pattern`. However, I also think that the option you suggest might be feasible. If we just had the option `ignore: ['descendents']`, I think that we'd get what you're aiming at, right? Even `ul li` would fail because it would fail on the `ul` (though the `li` would be ignored). 

If you wanted `div.bar` to pass, there could be another `ignore` option: `compounded`.

@jeddy3 what do you think? I know we've talked about this before, but have we ever actually added secondary options to a `-no-` rule?

**Comment by jeddy3** [comment]
> @jeddy3 what do you think? I know we've talked about this before, but have we ever actually added secondary options to a -no- rule?

Yep, I don't think we ever did. Not exactly sure why though, other than perhaps we always eventually found a way to not introduce that break in conventions. This sounds like a good candidate, if `selector-complex-pattern` isn't viable, to try it on though...

> `ignore: ["descendants", "compounded"]`... 

Having said that, and because I'm not super familiar with the API of `postcss-selector-parser`, I had a couple of questions about this approach. How do the `selector-no-*` rules work at the moment? Are they checking just the _simple_ selectors, including when they are used within _compound_ and _complex_ selectors? Does `postcss-selector-parser` provide an API to check _compound_ and _complex_ selectors too, so that we can easily support these options? Or is adding these options a bit more involved than that?

**Comment by davidtheclark** [comment]
`selector-complex-pattern` is viable it's just not the simplest approach for users: they have to write their own regexes, which can be a big pain and bug-prone.

We are just checking all (simple) selectors and warning about types. I believe that there is nothing built in to `postcss-selector-parser` to determine whether a simple selector is part of a compound/complex one. But I think we could do it pretty easily by getting the type node's parent and looking at what it contains.

**Comment by jeddy3** [comment]
> selector-complex-pattern is viable it's just not the simplest approach for users

Good point.

> But I think we could do it pretty easily by getting the type node's parent and looking at what it contains.

Perfect. That's what I was wondering.

So, it sounds like new options for `selector-no-type` is the way to go?

**Comment by davidtheclark** [comment]
I think it sounds like a worthy experiment.

**Comment by kangax** [comment]
Sounds good to me too.
