### ISSUE TITLE
Add `disablesPrefix` configuration property

### ISSUE THREAD

**Issue by ifitzpatrick** [stylelint/stylelint#6628]
### What is the problem you're trying to solve?

This might seem like an odd use case, but at larger companies there may be a company wide stylelint running against every team's codebase where the config file needs to meet the needs of the whole company. In order to enforce additional rules it can be convenient in that situation to run a separate instance of stylelint with additional rules. In this case it would be convenient to be able to disable each instance of stylelint with different stylelint commands by making the prefix configurable e.g. `stylelint-disable` -> `stylelint-special-rules-disable`.

### What solution would you like to see?

I have a pull request with a solution that appears to work. I am happy to take any suggestions to make it more ergonomic or address any edge cases I might have missed.

**Comment by jeddy3** [comment]
@ifitzpatrick Thanks for the request and writing up your use case.

We've previously added configuration properties to help people use Stylelint at scale, e.g. [`report*`](https://stylelint.io/user-guide/configure#report). This request feels similar.

We generally refer to these as "disables" in our public API and docs. As such, let's go with `disablesPrefix` as the configuration property name. It'll then match related properties:

```json
{
  "disablesPrefix": "stylelint-special-rules-disable",
  "descriptionlessDisables": true,
  "rules": {
    "unit-allowed-list": [["rem"], { "reportDisables": true }]
  }
}
```

I'll update the issue title accordingly.

**Comment by Mouvedia** [comment]
[This page](https://stylelint.io/user-guide/configure) will have to be updated.

**Comment by ifitzpatrick** [comment]
Thanks for the feedback!

**Comment by ybiquitous** [comment]
Honestly, I’m still unsure how adding `disablesPrefix` could solve your problem. Also, it seems to make the codebase more complex to add a feature for such an edge case.

We might find a better solution if you would provide more information about your case.

**Comment by ifitzpatrick** [comment]
The use case is that there is a company-wide instance of stylelint that is not under my team's control, which has "needlessDisables" turned on. We would like to be able to run a second instance of stylelint to enforce some additional rules, specifically enforcing the use of rems. There are sometimes exceptions where people may want to disable this rule. We would like to be able to disable the second linter independently of the first one. Without the ability to disable rules independently it is difficult for us to try out new policies and we can only apply stylelint rules that work for the entire company. It is not really an option for us to change the behavior of the primary linter.

**Comment by ybiquitous** [comment]
@ifitzpatrick Please let me clarify your problem. I guess you may solve your problem like this. For example:

Assume you have a company-wide config below:

```json
{
  "extends": ["stylelint-config-companywide"]
}
```

Your team has a config including "some additional rules":

```json
{
  "extends": ["stylelint-config-companywide"],
  "rules": {
    "unit-allowed-list": ["rem"]
  }
}
```

Your team sometimes wants to disable the additional rules:

```css
a {
  /* stylelint-disable-next-line unit-allowed-list -- Reason not to use `rem` is ... */
  font-size: 16px;
}
```

Am I missing something?

**Comment by ifitzpatrick** [comment]
Yes, we can't just extend the company wide config. It's running on an automated pipeline against all of the css/scss in the entire company. We do not have the ability to opt out of this instance of stylelint running against our code, so extending the config does not really help us because the original config is going to run against our code anyway.

**Comment by ybiquitous** [comment]
Could you please provide the current code snippet where you have problems and a code snippet you expect so that we can imagine your pain more easily?

**Comment by jeddy3** [comment]
@ybiquitous Here's an example for how I understand the use case.

A company runs an instance of Stylelint across all their products as part of an automated pipeline that is controlled by a central authority.

That instance turns on a limited set of rules that can be safely applied to all products:

```json
{
  "reportNeedlessDisables": true,
  "rules": {
    "color-function-notation": "modern",
    "unit-no-unknown": true
  }
}
```

There are Product Teams within the company that want to independently try out new policies on their codebases. For example, Product Team A wants to try enforcing `rem` units. They can't change the company-wide config as that would impact other product teams. So they set up another instance of Stylelint to run against just their codebase with:

```css
{
  "rules": {
    "unit-allowed-list": ["rem"]
  }
}
```

This works well until one of Product Team A's developers uses a `/* stylelint-disable */` comment to turn the rule off for part of a file:

```css
/* stylelint-disable unit-allowed-list */
a {
  top: 16px;
}
```

The product team instance of Stylelint is happy, but the company-wide instance thinks the comment is a needless disable because the `unit-allowed-list` rule isn't turned on in its config:

```console
test.css
 1:1  ✖  Needless disable for "unit-allowed-list"  --report-needless-disables

1 problem (1 error, 0 warnings)
```

@ifitzpatrick Am I right in assuming this is for Google? The [`report*`](https://stylelint.io/user-guide/configure#report) configuration properties (including `reportNeedlessDisables`) were added by one of your colleagues to help Google use Stylelint at scale. It'd be good to find a solution that allows you to continue using the `report*` properties and try out policies within product teams.

One option is your proposal, which I'll illustrate by modifying the example above.

The company-wide instance is unchanged:

```json
{
  "reportNeedlessDisables": true,
  "rules": {
    "color-function-notation": "modern",
    "unit-no-unknown": true
  }
}
```

The product team's instance becomes:

```json
{
  "disablesPrefix": "stylelint-disable-product-a"
  "rules": {
    "unit-allowed-list": ["rem"]
  }
}
```

Product Team A's developer can then use:

```css
/* stylelint-disable-product-a unit-allowed-list */
a {
  top: 16px;
}
```

Both the company-wide and the product team instances of Stylelint are happy and won't flag any needless disable.

Perhaps we can think of another way to solve the problem. I think @ifitzpatrick's proposal is a good fit, though. As @ybiquitous said, it'd be good to minimise the complexity it adds to our codebase. For example, rules typically don't [access configuration properties directly](https://github.com/stylelint/stylelint/pull/6629/files#diff-af2d45501da0cf90166b0a293ef0001069e494e6bb8c25053dd8dc80ee44a65b). Perhaps we can avoid that by using `context` or removing the need for the rules to know the configuration value?

**Comment by ybiquitous** [comment]
@jeddy3 Thanks a lot for the explanation with the code snippets. I now understand @ifitzpatrick's pain well.

Indeed, `disablesPrefix` seems a better solution in this case. I cannot find another way.

> Perhaps we can avoid that by using `context` or removing the need for the rules to know the configuration value?

Yeah, I agree with adding the `context` parameter of a rule function to access `disablesPrefix`. 👍🏼

**Comment by ifitzpatrick** [comment]
@jeddy3 thank you for laying out such a thorough example, this is exactly my issue. Yes I work at Google on a product team (Google Meet).

@ybiquitous @jeddy3 I updated https://github.com/stylelint/stylelint/pull/6629/ to use context instead of accessing the config directly. That's just for the rules right, or should `lib/assignDisabledRanges.js` also be using context somehow?

**Comment by ybiquitous** [comment]
@ifitzpatrick Thanks for continuing work on #6629!

> should `lib/assignDisabledRanges.js` also be using context somehow?

I don't think `lib/assignDisabledRanges.js` needs some context.

**Comment by ifitzpatrick** [comment]
Thanks for all of the feedback and support on this @jeddy3 @ybiquitous!
