### ISSUE TITLE
Request: return at least indentation

### ISSUE THREAD

**Issue by daniluk4000** [stylelint/stylelint#6657]
### What is the problem you're trying to solve?

Our case was to use Stylelint for formatting initially.

Prettier is too small on rules, so our solution was to use eslint for HTML+TS formattion and then set eslint-based formatting which worked pretty good for two IDEs. 

Sadly, eslint doesn't support style rules, for that we used Stylelint. Now we have to use Prettier only for style formatting, and drop our current formatting for HTML + TS (which we won't do). We'll sure stay with Stylelint but we won't have any formatting in scss anymore. 

If you have any workaround but to change our whole formattier to Prettier I would like to hear it. For me, it seems that you dropped users like us who doesn't want Prettier with it's 10 rules to take control and overwrite all recommended Vue/TS/e.t.c rules

### What solution would you like to see?

I don't require to support whole bunch of 76 rules, but having at least indentation for users like us would be so nice.

This repo doens't have Discussions, so I opened an issue for this and other folks who I'm sure will be looking for one.

**Comment by jeddy3** [comment]
@daniluk4000 Thanks for the request.

You're welcome to continue using Stylelint for whitespace formatting by porting the `indentation` rule (and any other rules you need) to [a plugin pack](https://stylelint.io/developer-guide/plugins). We mention this in the [migration guide](https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules). If you publish the plugin onto npm, other people can also use it. 

By removing these old and problematic whitespace rules from core, we can focus on modernising the Stylelint codebase (so that we can update our dependencies and keep Stylelint secure for you) and adding rules that [avoid errors](https://stylelint.io/user-guide/rules#avoid-errors) and [enforce (non-stylistic) consistency](https://stylelint.io/user-guide/rules#enforce-conventions). The latter two are arguably more important than whitespace formatting in helping people write maintainable CSS. You can read more about these rules in our new [customising guide](https://stylelint.io/user-guide/customize).

Using Stylelint to format whitespace is no longer our recommended approach, but we wrote our plugin system [to empower users](https://stylelint.io/about/vision#extensible) like you to do what they like.

**Comment by nolimitdev** [comment]
@daniluk4000 the same here. Deprecating 76 rules is too big breaking change for us. Prettier with its in about 5 config items of course is not alternative. VSCode does not show deprecation warnings (just `stylelint` command). Big problem will be Stylelint v16 when deprecated rules will be removed :(

**Comment by lubomirblazekcz** [comment]
Same here :/ I understand these changes, but you should carefully reconsider on some of these rules.

Some of these can't be used in prettier, eg. `indentation`, `string-quotes`, see here - https://github.com/prettier/prettier/issues/5378

I don't know Prettier much, but I think you can't configure most of these rules there. :/

**Comment by lubomirblazekcz** [comment]
Disregard my comment about prettier, I misunderstood it. It's possible via config https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option

If all the removed rules have an alternative in prettier then I guess it's ok 👍

**Comment by nolimitdev** [comment]
@lubomirblazekcz Im sure that most of 76 deprecated Stylelint's rules will not have Prettier alternative. Why? Prettier have only a few options https://prettier.io/docs/en/options.html and its less that Stylelint's 76 deprecated. So as jeddy said only some future plugins by 3rd parties could solve this deprecating storm.

**Comment by atjn** [comment]
I am also sad to see these changes. I have tried to use Prettier, but it does not work well with my programming style. That is not to mention the massive amount of work that it would be to integrate yet another tool into the build pipelines of 100+ separate projects.

For now, I am staying on Stylelint 14 and hoping that someone will make a plugin that covers the most basic stylistic issues. I don't need and don't want advanced (Prettier) styling, I just need obvious issues to be disallowed, such as wrong indentation.

**Comment by jeddy3** [comment]
> hoping that someone will make a plugin

It looks like a few of you who want to continue using Stylelint to enforce stylistic issues. That's great. We built the plugin system for exactly this type of thing. You can work on making a plugin together. It shouldn't be more than:

1. Copying the files you need to a repo
2. Tweaking the imports
3. Using find and replace to:
       - prefix relevant functions with [`stylelint.utils`](https://stylelint.io/developer-guide/plugins#stylelintutils) 
       - prefix the rule names with whatever you call the plugin, e.g. `stylistic/indentation`.
4. Publishing the package to npm

It'd be great if you added a link to the repo here and in Awesome Stylelint when you're done, as I said in https://github.com/stylelint/stylelint/issues/6657#issuecomment-1427969428.

If you create a plugin, it'll be a win-win for everyone. We'll be able to:

- modernise the Stylelint codebase to keep it secure for everyone
- focus on (error avoiding and non-stylistic convention enforcing) rules that benefit everyone

And we'll be able to do this with the limited resources we have as open-source volunteers. 

And you'll be able to continue using Stylelint to enforce stylistic conventions.

**Comment by atjn** [comment]
@jeddy3 I am speaking up about this because the way you wrote the migration guide makes it seem like these rules should not be part of Stylelint, as if it is a bad thing that Stylelint can do these things:

> When we created these rules, pretty printers (like [Prettier](https://prettier.io/)) didn't exist. They now offer a better way to consistently format code, especially whitespace. Linters and pretty printers are complementary tools that work together to help you write consistent and error-free code.

I disagree with that assessment. I think it is a very useful part of the linter to enforce some basic code styles, especially when the alternative you are mentioning doesn't offer what we are looking for.

> You can work on making a plugin together. It shouldn't be more than[...]

I understand that I can write my own plugin for it. I can also write my own CSS linter, but I am here because I think there are many benefits to using a community linter instead of writing my own.

>If you create a plugin, it'll be a win-win for everyone. We'll be able to:
>-  modernise the Stylelint codebase to keep it secure for everyone
>- focus on (error avoiding and non-stylistic convention enforcing) rules that benefit everyone

Once again, I don't really understand what you're trying to say here. It is also possible to modernize the code base with the old rules, and I am not sure why you deem the other rules as "benefiting everyone", but deem basic indentation control as something that doesn't benefit everyone.

If this decision is taken solely because you are a small team that doesn't have the resources to keep stylistic rules alive, then I completely understand, and I can only say thank you for the work you have done.
But the way you are communicating the changes right now makes it seem like you could keep these rules, but have chosen not to, and in that case I just don't understand the argumentation.

**Comment by mistic100** [comment]
eslint made the same changes (though the rules are not deprecated, just disabled by default) and it makes me really sad. Being an opinionated tool, Prettier will never be able to replace the stylistic rules that are in place for years in a project. And even if I am willing to migrate, Prettier is IMHO not a good tool, especially the auto wrapping/unwrapping which makes code sometimes unreadable.

It is a shame linters are dropping the style rules but there is actually no good replacement (like atjn I have other things to do than writing my own plugin or my own linter).

**Comment by atjn** [comment]
@taras-turchenko-moc might already be working on this as of https://github.com/stylelint/stylelint/issues/6693#issue-1607110443

> If you don't want to keep it in the stylelint library we can move it to a new library

**Comment by EvHaus** [comment]
Also, just to note, VS Code doesn't support multiple formatters at the moment and even after [my multiple attempts](https://github.com/microsoft/vscode/issues/142904) seems like they never will. Which means it's not going to be possible (or at least not easy) to run both `prettier` and `stylelint` against the same file in the most popular editor. So users are going to have to choose between auto-formatting either only stylistic rules via `prettier` or all other CSS rules via `stylelint`. 😢 

If any Stylelint maintainers have any recommendations here, would it be possible to add it to the docs?

**Comment by jeddy3** [comment]
@EvHaus Do you mean fixing with Stylelint and then formatting with Prettier?:

```json
{
  "css.validate": false
  "editor.codeActionsOnSave": {
    "source.fixAll.stylelint": true
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true
}
```

 If so, we can add that to our docs as some users may not know code actions.

**Comment by nolimitdev** [comment]
> @EvHaus Do you mean fixing with Stylelint and then formatting with Prettier?:
> 
> ```json
> {
>   "css.validate": false
>   "editor.codeActionsOnSave": {
>     "source.fixAll.stylelint": true
>   },
>   "editor.defaultFormatter": "esbenp.prettier-vscode",
>   "editor.formatOnSave": true
> }
> ```
> 
> If so, we can add that to our docs as some users may not know code actions.

But double formatting is not possible in VScode using right click and "Format document" (or keyboard shorcut).

**Comment by jeddy3** [comment]
> StyleLint is now great fantastic tool but after removing stylistic rules it it will be very poor tool.

We strive to make Stylelint [extensible](https://stylelint.io/about/vision#extensible) so everyone can build on it, and plugins are a key part of that vision.

There are steps in the [migration guide](https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules) to port the deprecated rules to a plugin.

Once someone has done that:

- people can continue using them indefinitely
- they'll be maintained by someone using the rules

I suggest they also publish a shared config, e.g. `stylelint-config-stylistic`, (with the [previous standard settings](https://github.com/stylelint/stylelint-config-standard/commit/e1d2e98c31cad2320674a0cd058869aa75bd8b14#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346)) to make it easier for people to migrate:

```diff json
{
  "extends": [
    "stylelint-config-standard",
+   "stylelint-config-stylistic"
  ]
}
```

We can add a link to the plugin in the migration guide once someone publishes the plugin so that its easier to find. It sounds like @Anoesj may have time to get the ball rolling with the plugin and hopefully others can contribute too.

**Comment by XhmikosR** [comment]
I gave a go trying to migrate our `twbs/stylelint-config-twbs-bootstrap` to prettier, see https://github.com/twbs/stylelint-config-twbs-bootstrap/issues/188#issuecomment-1493248181

I still can't get the same behavior for some rules, namely:

* `'number-leading-zero': 'never'`
* `'max-empty-lines': 2`
* allowing single line statements

Is there any way to achieve the same result somehow? Otherwise I really hope some the stylistic rules can be brought back if there's no alternative way to achieve the same result. :)

**Comment by ybiquitous** [comment]
If Prettier doesn't provide any [options](https://prettier.io/docs/en/options.html), unfortunately, you may need to write a plugin instead of using Prettier.

We won't change the decision here as @jeddy3 has answered.

**Comment by ybiquitous** [comment]
FYI. a community member has created a plugin for deprecated stylistic rules: [stylelint-stylistic](https://www.npmjs.com/package/stylelint-stylistic).
See also #6753.

**Comment by XhmikosR** [comment]
Thanks, I saw #6753 and already made a PR which switches to this package :)

https://github.com/twbs/stylelint-config-twbs-bootstrap/pull/195
