### ISSUE TITLE
Add support for stylus

### ISSUE THREAD

**Issue by hrjason** [stylelint/stylelint#674]
Hey guys 

I've been trying to figure out how to utilize `stylus` with the `postcss` engine provided via CLI.  Any one can point me in the right direction?

Thanks!

**Comment by davidtheclark** [comment]
Because nobody has yet made a PostCSS stylus parser (https://github.com/postcss/postcss/issues/602), I don't think you'll be able to run your stylus stylesheets directly through stylelint. They'll have to be compiled by stylus first. Something like https://www.npmjs.com/package/poststylus makes this easier for you. That's not CLI, but it's a very simple Node script (or gulp task).

Because the CLI should accept stdin as input, you could also try using the stylus CLI and piping the output into stylelint. Something like: `stylus myFile.css | stylelint`. I'm not exactly sure how the sourcemaps will work --- but I'm hoping that if stylus creates inline sourcemaps, PostCSS will detect and use them.  

These are just ideas --- I myself haven't yet done any of the above. Please give them a shot and let us know how it goes!

**Comment by EvNaverniouk** [comment]
If anyone comes across this issue and figures out a way to get `stylus` to work with `stylelint`, can you please post your solution? I wasn't having much luck with either `poststylus` or the CLI approach.

**Comment by evilebottnawi** [comment]
@EvNaverniouk need `postcss-stylus` parser (as `postcss-scss` and `postcss-less`).

**Comment by ntwb** [comment]
@EvNaverniouk Maybe create a new issue https://github.com/seaneking/poststylus, there is an existing closed issue but I don't think that was actually resolved https://github.com/seaneking/poststylus/issues/13

**Comment by doxiaodong** [comment]
How about this?

**Comment by Rouberg** [comment]
@davidtheclark  well, I'm confused that if I use stylus, stylelint with stylus-loader of webpack, and I wish lint stylus stylesheets, should I make a PostCSS stylus parser ? 

link this:
webpack.config.js
```javascript
  module: {
   rules: [{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            stylus: [
              'vue-style-loader',
              { loader: 'css-loader', options: { sourceMap: true, importLoaders: 2 } },
              { loader: 'postcss-loader', options: { sourceMap: true } },
              { loader: 'stylus-loader', options: { sourceMap: true } }
            ]
          }
        }
   }]
 }
```

**Comment by ntwb** [comment]
A PostCSS parser for Stylus is required 

It looks like @sotayamashita started on this in https://www.npmjs.com/package/postcss-stylus though the repo linked no longer exists or is private

**Comment by Grawl** [comment]
just found this https://github.com/Avol-V/postcss-stylus-parser

and this https://www.npmjs.com/package/poststylus

**Comment by ryuran** [comment]
Hi @Grawl, did you try it?
It’s working well?
Wich one is better ?

**Comment by Grawl** [comment]
no I just found these ones, did not tried to use them

**Comment by Grawl** [comment]
looks like Poststylus is not a Stylus parser but PostCSS plugin for Stylus

**Comment by staghouse** [comment]
Any movement on this?

**Comment by evilebottnawi** [comment]
@staghouse no, it is open source

**Comment by sotayamashita** [comment]
I created a repository and registered module to NPM then I made it private and try to remove module from NPM. :cry:

**Comment by ota-meshi** [comment]
I’m working on support for Stylus.
https://www.npmjs.com/package/postcss-styl

**Comment by jeddy3** [comment]
Closing [as available](https://github.com/stylelint/stylelint/issues/674#issuecomment-523026556) as a [`customSyntax`](https://github.com/stylelint/stylelint/blob/main/docs/user-guide/usage/options.md#customsyntax).
