### ISSUE TITLE
Intelligent support for configs in node_modules

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#679]
Can you do `stylelint foo/*.css --config standard > myTestReport.txt`? If not, could this double as a feature request?

**Comment by corysimmons** [comment]
In fact, it might be better to make `--config` search `node_modules` for any package prefixed with `stylelint-config-` and use that.

This way people could create their own `stylelint-config-crazyrules`, publish them on npm, and usage would be `stylelint foo/*.css --config crazyrules > out.txt`

**Comment by davidtheclark** [comment]
Have you tried this? It should work already. Except the part about automatically appending `stylelint-config-` to the beginning. Please give it a shot, and file bugs if something doesn't work as documented, or feature requests if you'd like something new.

**Comment by davidtheclark** [comment]
I take that back. Maybe this doesn't work already. Sorry :\

**Comment by davidtheclark** [comment]
@corysimmons: I deleted a couple of premature comments. Sorry for what might be confusing emails.

This seems to me like a reasonable feature request. @jeddy3, do you agree and are you cool with the `stylelint-config-` expectation?

**Comment by corysimmons** [comment]
@davidtheclark np, I've got all my GitHub email turned off so I never saw it. :)

**Comment by jeddy3** [comment]
>  @jeddy3, do you agree and are you cool with the stylelint-config- expectation?

Are we sure this kind of magic isn't going to be more confusing than helpful? For example, I recently added an absolute path example to the [usage section](https://github.com/stylelint/stylelint-config-standard#usage) of `stylelint-config-standard` because of https://github.com/stylelint/stylelint-config-standard/issues/4. With this proposal will I then need to explain that using the magic `--config standard` works fine most of the time, but you'll need to do something different when using absolute paths?

I think I prefer the explicitness of using the whole module name... unless I'm missing the point here? :)

**Comment by davidtheclark** [comment]
There are two parts to this idea:

- Part 1: Have the `--config` argument look in `node_modules`, instead of *only* looking for paths. In this sense, the `--config` argument would be like how `plugins` and `extends` already work. Because of that precedent, I think this is a good idea. So a person could do `--config stylelint-config-standard` or `--config ./node_modules/stylelint-config-standard/index.js` or `--config /absolute/path/to/stylelint-config-standard/index.js`.
- Part 2: The magic naming, where *if you're asking for a config in node_modules* (not using a path), you can leave a `stylelint-config-` prefix off the beginning. I'm more or less indifferent to this, in fact more opposed then in favor — because I'm not super interested in save-then-keystrokes features, and think they're all probably more trouble than they're worth — but wanted to see what others thought.

**Comment by davidtheclark** [comment]
@jeddy3 : So it sounds like you also prefer explicitness and then would not be in favor of Part 2? What about Part 1?

**Comment by jeddy3** [comment]
Thanks for the clarification.

Yep, we're in agreedment. Part 1 stgm, but I'm not in favour of Part 2.

I original thought, like you seem to too, that Part 1 was already the behaviour of `-- config` :)

**Comment by corysimmons** [comment]
Isn't the standard to prefix config files with `stylelint-config-`?

This is similar to PostCSS prefixing almost every plugin with `postcss-`.

I see what you're saying, but in the PostCSS CLI we're adding that feature and it seems handy. I suppose it might be more of a PITA in PostCSS thought because you could chain several plugins together.

`stylelint --config standard -w in.css -o out.css --fix` looks better to me than `stylelint --config stylelint-config-standard -w in.css -o out.css --fix` which just looks very repetitive.

Either way though, I'm not gonna get all torn up if you guys favor explicitness as I do too 99% of the time. No biggie. =)

**Comment by jeddy3** [comment]
Lets just do Part 1.

**Comment by corysimmons** [comment]
:+1: :100:
