### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#7]
a logo needs to be done

**Comment by jeddy3** [comment]
I had a couple of hours to kill on a train yesterday and so I figured I'd try to knock something up for `0.1.0`. The designers I know would laugh/cry if they knew I was even attempting this :)

"stylelint" is a funny word to look at with its "yl" and two "l"s. There aren't many fonts that work with it, as most make the word look quite odd. There was one or two that didn't. The best of the bunch, I think, was Niconne. Both the the "ty" and "lin" flow nicely. Even though the linter is a developer tool, it is in support of CSS --- a presentation language --- so I don't think a font with a bit of flair is out of place here.

It's black and white because, erm, I don't know colour theory, but I think it looks ok as the font is lively enough without colour :)

I've kept it as simple as possible. I did experiment with adding icons and the like, but it didn't really work.

Niconne is also available under an Open Font License.

Logo:

![logo](https://cloud.githubusercontent.com/assets/808227/7665395/813bc314-fbac-11e4-8f52-4c5ad4bcc8a4.png)

Social icon for github organisation and twitter feed:

![social](https://cloud.githubusercontent.com/assets/808227/7665402/b6e83b0a-fbac-11e4-9342-6266b3b75989.png)


What do you both think?

**Comment by davidtheclark** [comment]
Thanks for starting this! I'm afraid, though, that I'm not going to offer any input on the logo --- I'm just more indifferent than opinionated so I'm happy to let other choose :)

**Comment by jeddy3** [comment]
> I'm just more indifferent than opinionated so I'm happy to let other choose :)

Ha, I don't normally hear that. It's a refreshing change :)

@MoOx If you're happy with the logo, shall we go with it for now? Feel free to change the [s] github/twitter avatar to your liking, it was a last minute addition and I'm sure there are better alternatives :)

**Comment by MoOx** [comment]
I will work on the website like now so I will create an svg from the font and will try to make a sweet avatar icon :)

**Comment by MoOx** [comment]
I just started to work an original icon. I was thinking about something based on a bow tie. Any objections?

**Comment by MoOx** [comment]
Here is a first sketch 
![screen shot 2015-07-09 at 09 12 34](https://cloud.githubusercontent.com/assets/157534/8589824/a7ce95e0-261a-11e5-8d39-9e61fcebbbce.png)

Tell me if you like the idea or not :)

**Comment by jeddy3** [comment]
Ha, that's brilliant! Go ahead and use it :)

**Comment by davidtheclark** [comment]
Yeah, great!

**Comment by jeddy3** [comment]
@MoOx Once you've added it to the github org and the twitter account, do you want to close this issue?

**Comment by MoOx** [comment]
I will close that issue when:
- the logo will be versioned here (I want to make a second pass on it tomorrow morning).
- set to twitter & github org

Would you like to be open to get something similar to this https://github.com/cssnext/cssnext/tree/master/logo ?

**Comment by jeddy3** [comment]
SGTM :)

**Comment by jeddy3** [comment]
Shall I close this now that those two things are done?

**Comment by MoOx** [comment]
I don't think so. I should push a vectorised version at least...

**Comment by jeddy3** [comment]
It'd be great!
