### ISSUE TITLE
Update `package-lock.json` to lock file version `3`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7077]
see : https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion

Users of node 20 / npm 9 or later will always modify the `package-lock.json` file as those versions automatically convert it to version `3`.

As far as I know all supported versions in Stylelint of node/npm support version `3` of the lock file, so changing this should be fine.

Thoughts?

**Comment by ybiquitous** [comment]
@romainmenke I have no objections at all! Let's update it. 👍🏼

**Comment by Mouvedia** [comment]
> As far as I know all supported versions in Stylelint of node/npm support version 3 of the lock file…

We have a small range which is not covered: 14.13.1 to 14.16.1.
see
 - https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#%E2%9A%A0%EF%B8%8F-notable-breaking-changes
 - https://github.com/stylelint/stylelint/blob/c1aefb4d5c3c15d035a658a8e6f53be2fd5de283/package.json#L222

Hence we should wait for the next major.

**Comment by ybiquitous** [comment]
This doesn't require the next major because `package-lock.json` only relates to the Stylelint development. Users are never affected by the `package-lock.json` change.

Also, we've recommended using the latest `npm` on contributing, and our CI has used the latest `npm`. I think we can update `package-lock.json` without special concerns.

https://github.com/stylelint/stylelint/blob/c1aefb4d5c3c15d035a658a8e6f53be2fd5de283/CONTRIBUTING.md?plain=1#L18-L21
