### ISSUE TITLE
Using SCSS parser and // comments, error positions are off

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#712]
![image](https://cloud.githubusercontent.com/assets/224636/12895335/ef19f640-ce69-11e5-8e51-98c2de3ca98d.png)

I'm assuming "gradient" is a keyword. Totally valid for a selector name though.

**Comment by corysimmons** [comment]
Looks like strings ending with `value` get caught as well?

![image](https://cloud.githubusercontent.com/assets/224636/12898785/675bfe66-ce7c-11e5-96d7-b7898b07fa82.png)

**Comment by davidtheclark** [comment]
Can you reproduce this outside of Atom?

**Comment by corysimmons** [comment]
Hang on, I'm trying to get sublime text's linter working... Atom's plugin stuff is so much nicer. It sucks that Atom is so slow... =[

**Comment by davidtheclark** [comment]
Could you try with the CLI?

**Comment by corysimmons** [comment]
yeah, fails on CLI too

![image](https://cloud.githubusercontent.com/assets/224636/12903466/c83e9dba-ce95-11e5-8ffd-681c5beccf1b.png)

**Comment by davidtheclark** [comment]
I am unable to reproduce either of these errors. Can you please provide a simplified and reproducible test case?

**Comment by corysimmons** [comment]
Oh it's weird. The linter (stylelint-config-wordpress) is configured for double quotes, but it's not picking up these single quotes and ends up throwing an error:

![image](https://cloud.githubusercontent.com/assets/224636/12904764/93ec9116-ce9f-11e5-94e7-fa6b1c956efc.png)

When I use double quotes it fixes itself:

![image](https://cloud.githubusercontent.com/assets/224636/12904776/b26330b4-ce9f-11e5-9a03-7932abdc2cc0.png)

Is there any chance of creating/maintaining functional linters for Sublime Text and Atom? All these bugs are making stylelint unusable.

**Comment by davidtheclark** [comment]
I notice that all these files are SCSS files. Is there any way with the atom-linter plugin to even parse SCSS? I don't know if that's been built in or not. It's possible that your weird bugs are caused by this.

I disagree that the linter plugins are unusable. I myself have been using them successfully. And no, I am not going to start maintaining those myself, because I have enough on my hands already.

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12904867/471a74ec-cea0-11e5-8bf3-cb52b2bc7f5c.png)

was the result of

```
"scripts": {
  "stylelint": "stylelint ./css/**/*.scss --syntax scss"
},
"stylelint": {
  "extends": "stylelint-config-wordpress"
}
```

So either the CLI is broken, string-quotes are broken, --syntax scss is broken, stylelint-config-wordpress (which was just transferred from the official org) is broken, linter-stylelint is broken, or docs are broken.

I've been trying to track down where to file issues for days.

Steps to reproduce:

1. `npm i --save-dev stylelint any-stylelint-config`
2. package.json:

```
{
  "scripts": {
    "stylelint": "stylelint ./css/**/*.scss --syntax scss"
  },
  "stylelint": {
    "extends": "stylelint-config-wordpress"
  },
  "devDependencies": {
    "stylelint": "^4.2.0",
    "stylelint-config-wordpress": "^1.1.1"
  }
}
```

\3. `npm run stylelint`

Or just try to use Atom Linter.

> I myself have been using them successfully.

I'm not making things up am I? I'm taking screenshots of all this stuff and trying my best to replicate problems. There have been a couple issues out of the dozens I've filed that were me overlooking some documentation.

Every day that I've used stylelint I've spent **hours** tracking down bugs, filing issues, etc. so that stylelint can turn into a usable project by the masses.

Maybe it's usable for you in whatever specific way you've built it to be used, but I'm trying to use it in a very practical way (e.g. install Atom Linter stylelint, begin linting SCSS) and I've ran into problem after problem.

**Comment by davidtheclark** [comment]
@corysimmons: This isn't very helpful. I am using all of these things successfully, as are others. We have ~10,000 unit tests verifying that stylelint is working as documented! The problem is not that all this stuff just doesn't work or is unusable: something specific is going wrong and we can't address it without narrowing things down.

I have created a reduced test case based on the information you've given and still cannot reproduce the problem. 

**test.scss**

```scss
.series-promo-gradient {
	display: none;
}

// Maybe something is going on with value
$rem-base: 16px;

.real-problem::before {
	content: '';
}
```

**.stylelintrc**

```json
{
  "rules": {
    "string-quotes": "double"
  }
}
```

Run `stylelint test.scss --syntax scss`.

And the output is just what I would expect. The only error is line 9 (`content: '';`). The same thing (the expected thing) happens using the Atom linter.

If you want to get to the bottom of this please tell me what needs to change about this setup to reproduce the problems you're seeing.

**Comment by corysimmons** [comment]
Apparently it's caused by comments.

```scss
// 1
// 2
// 3
// 4
// 5
// 6
// 7
// 8
// 9
// 10
// 11
// 12
// 13
// 14
// 15
// 16
// 17
// 18

.qux {

	@media (max-width: 900px) {

		.baz {
			display: none;
		}
	}
}

.foo {

	.bar {

		&:after {
			content: '';
		}
	}
}
```

![image](https://cloud.githubusercontent.com/assets/224636/12906403/dd46541a-cead-11e5-98d6-c4e912f3815d.png)

The more comments you add, the higher up the error starts moving.

**Comment by davidtheclark** [comment]
Excellent find! With that I'm able to reproduce the bug in a test. Will figure out a fix for it soon.

**Comment by corysimmons** [comment]
Alright thanks, sorry for spazzing.

**Comment by davidtheclark** [comment]
I understand, tooling can get frustrating.
