### ISSUE TITLE
Adding an "exclusive properties" rule

### ISSUE THREAD

**Issue by emmacharp** [stylelint/stylelint#7130]
### What is the problem you're trying to solve?

There are CSS properties that should not be used together and (at least) junior devs need help to identify them.

### What solution would you like to see?

An "exclusive properties" rule could go a long way in mitigating these kind of clashes.

**Comment by emmacharp** [comment]
@jeddy3 Absolutely! And thanks for the quick follow-up.

It would be hard to provide a definitive and exhaustive list of all these properties since there is a lot of them and CSS keeps evolving... I guess it'd be better to write these in the config file. Nevertheless, here is a couple of these off the top of my head:

display: block; & vertical-align
display: block & flex-*
display: inline & padding-*
width & flex-basis
float & flex-*

As you can see, I should have formulated my feature request as "exclusive declarations" instead of "exclusive properties". Sorry for that. I can edit it if you wish.

On a sidenote, since you make me think about it further, maybe a "declaration needed/dependency" could do the job too. As in:

vertical-align (needs) display: inline-*

**Comment by jeddy3** [comment]
@emmacharp Thanks for clarifying. I understand now.

I believe the [`stylelint-declaration-block-no-ignored-properties`](https://github.com/kristerkari/stylelint-declaration-block-no-ignored-properties) plugin is what you're after.

> On a sidenote, since you make me think about it further, maybe a "declaration needed/dependency" could do the job too. As in: `vertical-align (needs) display: inline-*`

You can explore this approach [in a plugin](https://stylelint.io/developer-guide/plugins/). It may trigger false positives, though, as Stylelint (as a static analysis tool) isn't aware of the DOM structure and final ruleset for an element. We won't create a built-in rule for this as they all must be free of false positives.

The former approach may have false negatives too, i.e. it doesn't catch problems when declarations exist in other declaration blocks. Which is why it's also a plugin.
