### ISSUE TITLE
Revert Node.js API returned resolved object change

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7141]
As pointed out in https://github.com/stylelint/stylelint/pull/7136#pullrequestreview-1579157299, we've introduced a potentially disruptive change in https://github.com/stylelint/stylelint/pull/7119. 

The [original request](https://github.com/stylelint/stylelint/issues/6604) was to change the behaviour of the CLI to make it easier to use husky and lint-staged. We also made breaking changes to the Node.js API as part of the pull request, likely impacting editor integrations. By adding the `code` property, we cleaned up the API but at a potentially high cost because integrations are slow-moving.

I believe most integrations use `warnings[]` for lint problems and `output` for the fixed code, e.g. VS Code's [warnings](https://github.com/stylelint/vscode-stylelint/blob/main/src/utils/stylelint/process-linter-result.ts) and [fixes](https://github.com/stylelint/vscode-stylelint/blob/main/src/utils/documents/get-fixes.ts). If we revert to using `output` for fixed code, integrations will not need to make changes.

Rather than add a `code` property, we can add one that always contains the formatted lint problems so that they are accessible even when the `fix` option is used:

- `errors` - a string that contains the formatted problems (regardless of whether `fix` is used)
- `output` - a string that contains the autofixed code when the `fix` option is used. For backwards compatibility, it also contains the formatted problems otherwise.

What would be the best name for the property? `errors` would align with:

- the CLI's behaviour of stdout (for fixed code) and stderr (for formatted problems)
- the `errored` flag

But it is not factually accurate as it could contain formatted warnings, but then `warnings[]` also contains errors... (if we clean up the API, we should do the whole lot in one go and assess if the impact is worth it).

Another option is `formatterOutput`.

Thoughts?

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for opening the discussion.

Personally, I prefer the `v16` current API since each property (`output` and `code`) has a clear role. There is no switching of `output` depending on a value of `fix`.

If we would keep `output` backward compatible and add a similar property (like `errors` or `formattedOutput`), unfortunately, we would hold the unclear API for a while (maybe until the next major version).

However surely, it's important to evaluate the effects of this breaking change.

- Can we estimate what will be the actual impact?
- Can we provide a way to avoid this breaking change, for example, by adding `stylelintVersion` property of `LinterResult`?

**Comment by Mouvedia** [comment]
I think we should keep `output` as is—for backward compatibility—with a `console.debug` until v17 **and** introduce 2 new properties that will split both responsibilities.  
Let's bikeshed the name of these new properties in the revert PR directly.

**Comment by ybiquitous** [comment]
Okay, I agree with reverting `output` for backward compatibility. Additionally, I suggest the following:

- add `code` property for fixed code
- add `report` property for problems report
- deprecate `output` property in a doc
  - if possible, we should emit some deprecation warning (by `result.warn()` rather than `console.debug()` like deprecated stylistic rules). But I think it's difficult to emit warnings when using `output` due to being too noisy.
- delete `output` with 17.0.0 (next major)

These new properties should help users migrate. Any thought?

**Comment by Mouvedia** [comment]
> But I think it's difficult to emit warnings when using `output` due to being too noisy.

That's why I wanted something that only third party developers should see.
i.e. `console.debug`

**Comment by jeddy3** [comment]
Also SGTM.

**Comment by ybiquitous** [comment]
Closed via #7183
