### ISSUE TITLE
SCSS syntax error reporting

### ISSUE THREAD

**Issue by zaalbarxx** [stylelint/stylelint#7173]
### What minimal example or steps are needed to reproduce the bug?

// vue
```html
<style lang="scss" scoped>
@use "sass:map": // colon instead of semicolon

.test {
    margin-top: $spacers, 3); //missing (
}
</style> 
```
### What minimal configuration is needed to reproduce the bug?

```json
{
    extends: [
        'stylelint-config-idiomatic-order',
        'stylelint-config-standard-scss',
        'stylelint-config-recommended-vue/scss',
    ]
}
```

### How did you run Stylelint?

npx stylelint "src/**/*.{vue,scss}"

### Which Stylelint-related dependencies are you using?

```json
{
"stylelint": "^15.10.3",
"stylelint-config-idiomatic-order": "^9.0.0",
"stylelint-config-recommended-vue": "^1.5.0",
"stylelint-config-standard-scss": "^11.0.0",
"stylelint-order": "^6.0.3",
"stylelint-scss": "^5.1.0",
"postcss-html": "^1.5.0",
}

```

### What did you expect to happen?

I would expect the syntax errors from SCSS to be reported by Stylelint, unless I'm missing something :) Maybe I don't fully understand what are the capabilities of Stylelint when it comes to parsing SCSS, but when I do something like that:
```
.test {
marg in-top: 12px; // space
}
```
the CssSyntaxError will be thrown, and the same does not happen for SCSS syntax. Is it a bug or do I need something else to check the correctness of the SCSS syntax? 

### What actually happened?

I get no errors by running the command.

**Comment by json-derulo** [comment]
The difference between CSS and SCSS is that SCSS needs to be compiled, while CSS runs natively in browsers. IMHO, Stylelint should not report errors in SCSS files since they are thrown during compilation anyway. Syntax errors in CSS files, on the other hand, should be reported by Stylelint since there is no compilation step that validates the syntax.

**Comment by ybiquitous** [comment]
@zaalbarxx Thanks for the report with reproducible info. I confirmed the behavior with this [minimal demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYKC2SBOBzAlgHYC0ALhAA7woAkAzhUmDNnQDQoDMAlCgL4g2IAGb4ANjABySDHEQwAHjIoSAdHTB06g8BEKjcCEMAA6hFChPgArnXIYAygE9CpJAqvUrFCHc11iDS0rNjMLK2xrCTpPND4zASFIfXxcADEIbCxSIwArOj0dWAptRFNzSxAfPy1A-1irABZVAAZVAA4QsMq7JwkxIlIGkABGAFZVEbbOKwSQPiA) using just [`postcss-scss`](https://github.com/postcss/postcss-scss).

```scss
a { margin-top: $spacers, 3) }
```

This seems a bug of `postcss-scss` (a SCSS parser) because it can parse the incorrect SCSS code unexpectedly:

```console
$ node -pe 'require("postcss-scss").parse("a { margin-top: $spacers, 3) }")'
<ref *1> Root {
  raws: { semicolon: false, after: '' },
  type: 'root',
  nodes: [
    Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Circular *1],
      source: [Object],
      selector: 'a',
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    }
  ],
  source: {
    input: Input {
      css: 'a { margin-top: $spacers, 3) }',
      hasBOM: false,
      id: '<input css 4WREmH>',
      [Symbol(fromOffsetCache)]: [Array]
    },
    start: { column: 1, line: 1, offset: 0 },
    end: { column: 31, line: 1, offset: 30 }
  },
  [Symbol(isClean)]: false,
  [Symbol(my)]: true
}
```

So, could you please file a report to [postcss/postcss-scss](https://github.com/postcss/postcss-scss)?
