### ISSUE TITLE
Deprecate CommonJS plugins

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7340]
### What is the problem you're trying to solve?

For 16.0.0, we've migrated our codebase to ESM (with tool-based hybrid CommonJS support) and added support for them.

We intend to be pure ESM for our next major release to update our dependencies, reduce our maintenance load and move with the times. We should deprecate support for CommonJS plugins in 16.0.0 to communicate our intent so that plugin authors are encouraged to migrate their plugins to ESM after 16.0.0 and before 17.0.0.

Ref: https://github.com/stylelint/stylelint/pull/7339#discussion_r1393908910

### What solution would you like to see?

The minimum would be changelog and migration guide entries, e.g.:

---
### Deprecated support for CommonJS plugins

We've deprecated support for CommonJS plugins, and we'll remove support for them in our next major release. 

You should update how your plugin imports and exports:

```diff js
-const stylelint = require('stylelint');
+import stylelint from 'stylelint';

/* .. */

-module.exports = createPlugin(ruleName, ruleFunction);
+export default createPlugin(ruleName, ruleFunction);
```

You should also:

- Add `"type": "module"` to your package.json.
- Replace `"main": "index.js"` with `"exports": "./index.js"` in your package.json.
- Update the `"engines"` field in package.json to Node.js 18: `"node": ">=18"`.
- Remove `'use strict';` from all JavaScript files.
- Use only full relative file paths for imports: `import x from '.';` → `import x from './index.js';`.
- Use the [`node:` protocol](https://nodejs.org/api/esm.html#esm_node_imports) for Node.js built-in imports.

---

Ideally, we'd also generate a deprecation warning (that respects the [`quietDeprecationWarnings`](https://stylelint.io/user-guide/options#quietdeprecationwarnings) option) when commonjs plugins are used. I'm not sure if this is possible, though?

**Comment by ybiquitous** [comment]
Totally agree with this idea. 👍🏼 

> Ideally, we'd also generate a deprecation warning (that respects the [`quietDeprecationWarnings`](https://stylelint.io/user-guide/options#quietdeprecationwarnings) option) when commonjs plugins are used. I'm not sure if this is possible, though?

I'm also unsure about this. It should be possible if we could run any code on calling dynamic `import()` with the info which module type is imported, but I cannot find such a feature... 😓

**Comment by Mouvedia** [comment]
> and before 17.0.0

I am probably in the minority but I would strongly prefer if it was _before 18.0.0_.
The reason being that there are many plugins that are not maintained anymore which are mature and stable.
It will require a lot of effort/time to transfer the ownership or create new packages for those.

**Comment by ybiquitous** [comment]
> there are many plugins that are not maintained anymore which are mature and stable

Yeah, this is our headache...

**Comment by newives** [comment]
If developers are forced to use `esm`, it should be announced to developers a long time in advance. For example, `stylelint` already supports `export default{}` and most plug-in developers can upgrade without changing too much code. Maybe `stylelint16` is a good transition because it supports both `CommonJS` and `esm`. After all, most of them have been developed so far. It will take a long time to completely move towards `esm`.

**Comment by jeddy3** [comment]
> It should be possible if we could run any code on calling dynamic import() with the info which module type is imported, but I cannot find such a feature...

Yes, I assumed that'd be possible too. However, if it's not, then we'll be OK with a changelog and migration guide entry.

I'll label as ready to implement and add to https://github.com/stylelint/stylelint/issues/6930.

**Comment by ybiquitous** [comment]
FYI, since dynamic `import()` can load a CommonJS module, CJS plugins may work after we remove support for them (unless we don't change the API).

**Comment by jeddy3** [comment]
My understanding was the deprecation is needed because plugins, unlike formatter and custom syntax, import Stylelint to use utilities like `report`. I believe eslint, prettier and other plugins don't do this. In hindsight, we should've taken a similar approach when we designed the plugin system many years ago.

I think our options are:
- deprecate cjs plugins to encourage the migration of plugins to ESM 
- rearchitect our plugin system so that plugins don't need to import stylelint

Can anyone think of other options? If not, I'm in favour of the first option because it generally feels like the whole JavaScript ecosystem is shifting towards ESM, and we may not have the resources to redesign our plugin system. And even if we did, it may not be possible without breaking changes.

**Comment by firefoxic** [comment]
Oh! I just today [replaced those utilities with an import from Stylelint](https://github.com/firefoxic/stylelint-codeguide/pull/6/commits/8dbb09e69f950b2d6782842038b9c29b677f448a) 😅

It's easier for me, I can just revert the commit. But in old plugins, authors will have to move them manually.

What about `stylelint.createPlugin` and `stylelint.lint`? Or is there no problem with them being "imported" into a CJS plugin?

**Comment by Mouvedia** [comment]
> [Replace "main": "index.js" with "exports": "./index.js" in your package.json.](https://github.com/stylelint/stylelint/issues/7340#issue-1994452869)

This should be removed. It's not necessary; it's equivalent but slightly less compatible with other tools that might only pick up `main`.

You should add a note saying that a dual ESM/CJS plugin that would target stylelint 14 and ≥15 would require _both_ `exports` and `main`. The reason being #6477, which pushed the minimum node version above 13.
i.e. since [`exports` was introduced in version 13](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_package_entry_points) a plugin supporting only stylelint ≥15 would only require one or the other

**Comment by Mouvedia** [comment]
> rearchitect our plugin system so that plugins don't need to import stylelint

- If it's not a big refactor, it's worth exploring.
Switching to ESM is finicky. Hoping that the whole ecosystem of plugins will be migrated during one major life-cycle is unrealistic IMHO.
- If it's too complicated, the deprecation should last 2 majors versions else we risk to have users not upgrading due to a lack of ressource required to fork/release the package internally.

**Comment by ybiquitous** [comment]
First, I'm in favor of switching Stylelint to pure ESM in 17.0.0 (next major) in order to:
- keep dependencies up-to-date
- reduce the package size by `.cjs` files
- reduce maintainer's issue triage work due to CJS
- etc...

As @jeddy3 commented, CJS plugins won't work with pure ESM Stylelint since CJS modules cannot import ESM modules. Sorry, I missed it.

> - deprecate cjs plugins to encourage the migration of plugins to ESM

I lean toward this deprecation, although I still understand the difficulty of rewriting the existing CJS plugins to ESM.

Perhaps providing a rewriting tool to ESM might help ease the pain of plugin authors...

> - rearchitect our plugin system so that plugins don't need to import stylelint

I doubt this policy change because:
- this rearchitecting *also* requires the rewrite of the existing plugins
- common utilities like [`@eslint-community/eslint-utils`](https://www.npmjs.com/package/@eslint-community/eslint-utils) are still necessary
- we should spend fewer resources on new rules for new syntax rather than internals

**Comment by ybiquitous** [comment]
As @Mouvedia suggested on https://github.com/stylelint/stylelint/issues/7340#issuecomment-1815035935, I agree with leaving the `main` field, too.

The [Node.js document](https://nodejs.org/api/packages.html#main-entry-point-export) says below:

> compatibility can be achieved by including the `"main"` field alongside `"exports"` pointing to the same module:
>
> ```json
> {
>  "main": "./index.js",
>  "exports": "./index.js"
> }
> ```

Instead of replacing `main`, how about suggesting just adding `exports`?

**Comment by ybiquitous** [comment]
For your information, Vite 5 (which is released today) [deprecates CJS Node API](https://vitejs.dev/guide/migration.html#deprecate-cjs-node-api).

Here's how to show the deprecation warning:
https://github.com/vitejs/vite/blob/2844a0f66e13006d7624ffb564a63af0f20276fa/packages/vite/index.cjs#L3

**Comment by jeddy3** [comment]
@ybiquitous It looks like we agree on switching to ESM in 17, and deprecating CJS plugins rather than attempting to rearchitect the plugin system. All your points make sense to me.

> Perhaps providing a rewriting tool to ESM might help ease the pain of plugin authors...

I agree that we should do our best to help plugin authors migrate, but a tool (even though ideal) may not be achievable.

We can start with a section in the migration guide. It doesn't need to be perfect because we can improve it as plugin authors provide feedback on what obstacles they encounter. They'll also have plenty of time to migrate, as it'll be at least a few months before we release the next major version.

When I was migrating stylelint-scales, switching code to ESM import and export statements wasn't an issue, whereas getting Jest to work was a pain point. Let's try to improve that experience, as most plugin authors use our Jest preset.

What can we do about:

- fixing Jest and our preset on Node.js@18?
- providing an alternative test rule runner?

For the latter, we could investigate the possibility of a `stylelint-test-rule-node` package that exports a `testRule()` function, which uses the built-in `node:test` and `node:assert`. That should work with ESM code out of the box.

It should ideally be close to a drop-in replacement for most plugins: 

```js
import testRule from "stylelint-test-rule-node"

testRule({ /* .. */ });
```

```diff json
{
  "devDependencies": {
-    "jest": "^29.7.0",
-    "jest-preset-stylelint": "^6.3.2",
  },
 "scripts": {
-     "test": "jest",
+    "test": "node --test",
  }
}
```

Ideally, we'd fix the Node.js@18 issue so that plugin authors can choose.

Has anyone else encountered pain points while migrating their plugin to ESM to test the prerelease? If so, please share so that we can ensure the first version of the migration guide covers these.

**Comment by firefoxic** [comment]
> providing an alternative test rule runner?

I tried a couple test suites to rewrite to `node:test` in my plugin. It was surprisingly easy. And everything worked well (and also several times faster). Although I took some of the simplest tests (without a lot of dependencies and complex code), but I think there will be no problems there too. I think the main problem will be the routine of replacing code fragments in the same way.

**Comment by firefoxic** [comment]
> Has anyone else encountered pain points while migrating their plugin to ESM to test the prerelease? If so, please share so that we can ensure the first version of the migration guide covers these.

I had a pretty specific problem, hardly relevant to anyone who needs to really put a lot of effort into rewriting cjs code in esm. The thing is that I already had the plugin in esm, and only for stylelint<16 I had to compile to cjs with babel. And when I tried to make at least an alpha-version for those who need cjs - it didn't start, because stylelint expected `default` immediately in the root of the plugin object, but I had the necessary `default` in a nested `default` inside an array (I don't remember exactly) and I got an error. In my case the fix would be more expensive than the profit, so I just deleted babel and made a new pre-release with already normally working esm.

Most plugins have cjs in the source code itself, not built by babel, rollup or whatever. So this problem should not occur.

**Comment by firefoxic** [comment]
> ```diff
> + import testRule from "stylelint-test-rule-node"
> 
> testRule({ /* .. */ });
> ```

That would be awesome 😍

**Comment by ybiquitous** [comment]
The idea of a new test helper using [`node:test`](https://nodejs.org/api/test.html) sounds great! 👍🏼

**Comment by Mouvedia** [comment]
> Instead of replacing main, how about suggesting just adding exports?

That's OK. What I am advocating is to separate points that are MUST from the ones that are MAY in the migration guide.
e.g. `exports` addition being one of the MAY

> They'll also have plenty of time to migrate, as it'll be at least a few months (or even a year) before we release the next major version.

If we can stretch to more than a year, it might be enough time if we have proper [warnings](https://github.com/stylelint/stylelint/issues/5291#issuecomment-1604292676) which respect `--quiet-deprecation-warnings`.

> For example, a stylelint-test-rule-node package that exports a testRule() function using the built-in node:test and node:assert.

👍

**Comment by ybiquitous** [comment]
If `node:test` would be sufficient, we might be able to provide new test helpers similar to [`jest-preset-stylelint`](https://github.com/stylelint/jest-preset-stylelint) *by the `stylelint` package itself*. For example:

```js
import { testRule, testRuleConfigs } from "stylelint/test";
```

**Comment by JounQin** [comment]
Is that a good idea to install test-only related codes for all regular users?

**Comment by jeddy3** [comment]
In the [example above](https://github.com/stylelint/stylelint/issues/7340#issuecomment-1816837516), the plugin object (rather than a locator to it) is passed to the `plugins: []` configuration object.  Let's include this pattern in the migration and writing plugins guides as part of the PR for this issue. And also update the jest-preset-stylelint README at the same time.

Ref: https://github.com/jeddy3/stylelint-scales/pull/94#issuecomment-1816817156

I think the deprecation is ready to be worked on if anyone has time. As Jest now works with some minor changes (that we can communicate in the migration guide), creating a `testRule` using `node:test` shouldn't block us from releasing `16.0.0`. It'd be really nice to have, though!

Jest migration changes for the guide:

```diff js
// jest.setup.js
- const { getTestRule } = require("jest-preset-stylelint");
+ import { getTestRule } from "jest-preset-stylelint";

- global.testRule = getTestRule({ plugins: [plugin] });
+ global.testRule = getTestRule();
```

```diff json
// package.json
{ 
  "scripts": {
-    "test": "jest",
+    "test": "cross-env NODE_OPTIONS=--experimental-vm-modules jest --runInBand"
  }
}
```

```diff js
// plugin.test.js
import plugin from "../index.js";
const {
  rule: { messages, ruleName },
} = plugin;

testRule({
+. plugins: [rule]
  /* .. */
});
```





> If `node:test` would be sufficient, we might be able to provide new test helpers similar to [`jest-preset-stylelint`](https://github.com/stylelint/jest-preset-stylelint) by the `stylelint` package itself.

What are the advantages and disadvantages of including it in `stylelint` or as a separate package? (I've no strong preference myself, just curious.)
