### ISSUE TITLE
Add `lightness-notation`

### ISSUE THREAD

**Issue by fpetrakov** [stylelint/stylelint#7359]
### What is the problem you're trying to solve?

I would like to specify the type of value of [lightness](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch#l) component

### What solution would you like to see?

A rule with two options: "number" | "percent". 

**"number":**
The following patterns are considered problems:
```css
a {
  color: oklch(70% 0.2 10);
}
```

The following patterns are NOT considered problems:
```css
a {
  color: oklch(0.7 0.2 10);
}
```

**"percent":**
The following patterns are considered problems:
```css
a {
  color: oklch(0.7 0.2 10);
}
```

The following patterns are NOT considered problems:
```css
a {
  color: oklch(70% 0.2 10);
}
```

**Comment by fpetrakov** [comment]
The [`hue-degree-notation`](https://stylelint.io/user-guide/rules/hue-degree-notation/ ) rule is quite similar to the proposed one

**Comment by fpetrakov** [comment]
@ai What do you think about this kind of rule?

**Comment by ai** [comment]
I would like to use this rule in my config

**Comment by ai** [comment]
@ybiquitous `C` is not % by the nature of OKLCH, since there is no 100%. C could be 2, 3 (in reality there are no devices to render it, but still). So even if it is possible, it is not useful to use.

**Comment by ai** [comment]
I think so. We can also apply it to `lch` and `lab` (`hsl`?).

**Comment by ybiquitous** [comment]
Ah, I got it. The new rule should be applied to color functions that can take a lightness (`L`) value. Let me list up...

- [`oklch(L C H[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch)
- [`oklab(L a b[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab)
- [`lch(L C H[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch)
- [`lab(L a b[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab)
- [`hsl(H S L[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl)

Let us know if there is anything else.

**Comment by fpetrakov** [comment]
Yep, but [`hsl` lightness can only be a percentage](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#l), so only `oklch`, `oklab`, `lch` and `lab`.

**Comment by fpetrakov** [comment]
Yes, but I'm not sure if `hsl` lightness component can take a number. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#l) and [CSS spec](https://www.w3.org/wiki/CSS3/Color/HSL#Example_B) it can only take a percentage value

**Comment by ybiquitous** [comment]
Hum, this [CSS spec](https://drafts.csswg.org/css-color/#the-hsl-notation) seems to say `hsl()` and `hsla()` can take `L` as a number or percentage:

> For lightness, `50%` or `50` represents the "normal" color, while `100%` or `100` is white and `0%` or `0` is black.

**Comment by fpetrakov** [comment]
Weird, I also tried to use `hsl()` lightness as a number in the latest Chrome and Firefox, and it didn't work. I guess, we should include `hsl()` and `hsla()` to follow the spec. By the way, the "CSS spec" I referenced before is not a spec, but a w3c wiki 😅

**Comment by jeddy3** [comment]
I'd use this rule, too.

How about?:

- Name: `lightness-notation`
- Primary option: `"percentage"|"number"`
- Secondary options: `exceptFunctions: []`
- Autofixable: Yes
- Message: `Expected "${unfixed}" to be "${fixed}"`
- Description: "Specify percentage or number notation for lightness"
- Section: "Enforce conventions" -> "Notation"
- Config: Yes, in standard with `"percentage"`

It'd check the lightness in:

- [`oklch(L C H[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch)
- [`oklab(L a b[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab)
- [`lch(L C H[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch)
- [`lab(L a b[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab)
- [`hsl(H S L[ / A])`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl)

When we autofix, let's account for differences in _percent reference ranges_, i.e. 100% is:

- 100 in HSL colour function
- 1.0 in the other colour functions

(Lightness in HSL is similar to [`hue-degree-notation`](https://stylelint.io/user-guide/rules/hue-degree-notation) where the unit is optional.)

And because of this, let's add an `exceptFunctions: []` secondary option that inverts the primary option:

```json
{ "lightness-notation": ["number", { "exceptFunctions": ["/^hsl/"] } ] }
```

---

We can add separate rules for things like chroma. When we do, let's remember they have interesting _percent reference ranges_ such as 100% = 0.4 for chroma.

**Comment by ai** [comment]
> When we do, let's remember they have interesting percent reference ranges such as 100% = 0.4 for chroma.

0.4 is not 100%.

For sRGB screen [max chroma](https://oklch.com/#69.73,0.3189,329.29,100) <0.31 for purple, but for other colors max chroma is different.

For P3 screen [max chroma](https://oklch.com/#84.71,0.358,145.06,100) is <0.36 for green.

For Rec2020 screens (hard to buy, the standard for future) [max chroma](https://oklch.com/#82.35,0.457,152.47,100) is <0.46 for green too (our eyes see more green colors).

**Comment by jeddy3** [comment]
Very interesting. I figured there would be more to unpick with these atypical percentage reference ranges. I pulled the "100% = 0.4" one for chroma from [the spec](https://drafts.csswg.org/css-color/#specifying-oklab-oklch) as an example. 

Let's loop back around to this when we open an issue for chroma notation so that we can unpick it in more detail.

(Thank you for oklch.com, btw. It's a great tool!)

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the blueprint! It's almost good, but I have a few questions about naming.

### Rule name `lightness-notation`

We have similar rules already: `alpha-value-notation` and `hue-degree-notation`.
(see also https://stylelint.io/user-guide/rules/#notation)

So, why do you prefer `lightness-notation` over `lightness-value-notation` (original proposal)? Including `-value` seems a bit verbose to me, but I'm concerned about consistency with `alpha-value-notation`.

### Option name `exceptFunctions`

We've never had `exceptFunctions`, although there are many `ignoreFunctions` options. Why do you choose `exceptFunctions`?

**Comment by jeddy3** [comment]
> why do you prefer `lightness-notation` over `lightness-value-notation`

The `alpha-value-notation` rule checks the [`<alpha-value>` data type](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types#color), whereas lightness is just lightness.

(In `hue-degree-notation`, `<hue>` is the data type and degree is the specific type of `<angle>` that the rule checks.)

> We've never had `exceptFunctions`, although there are many `ignoreFunctions` options. Why do you choose `exceptFunctions`?

Our [`except` options invert the primary option, whereas `ignore` ignores the pattern](https://stylelint.io/developer-guide/rules#keyword-ignore-and-except).

We typically prefer adding `except` options over `ignore` ones as they allow users to enforce the most consistency.

This is particularly useful for this rule because of `hsl(a)`'s atypical percent reference range.

For example, to enforce `<percentage>` for `hsl(a)` and `<number>` for everything else:

```json
{ "lightness-notation": ["number", { "exceptFunctions": ["/^hsl/"] } ] }
```

Which would enforce:

```css
a {
  color: hsl(0 0% 100%);
  color: oklch(1 0 0);
  color: oklab(1 0 0);
}
```

If we use an `ignore` option, rather than `except` one, it'd allow:

```css
a {
  color: hsl(0 0% 100);
  color: hsl(0 0% 100%);
  color: oklch(1 0 0);
  color: oklab(1 0 0);
}
```

Where the 100 in the first `hsl` is valid CSS according to the spec but a pattern users will likely want to avoid.

We haven't had occasion to add a [user-defined](https://stylelint.io/developer-guide/rules#user-defined-ignore) `except*` option before because our `except` options have applied to keywords.

Having said all that, the lightness in HSL is kind of funky. We can just check `*lab` and `*lch` in the first version of this rule and drop the `exceptFunctions: []` secondary option for now.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the detailed explanation. Now I understand the naming and the difference between `except` and `ignore`. 👍🏼 

> Having said all that, the lightness in HSL is kind of funky. We can just check `*lab` and `*lch` in the first version of this rule and drop the `exceptFunctions: []` secondary option for now.

Considering simplicity, dropping `hsl()` and `exceptFunctions` first sounds good. 👍🏼

**Comment by fpetrakov** [comment]
Just to clarify, is it ready to implement? I would like to take it

**Comment by romainmenke** [comment]
_I haven't had much time to keep track of everything lately and I missed this one._

-------

> When we do, let's remember they have interesting percent reference ranges such as 100% = 0.4 for chroma.

> 0.4 is not 100%.

- 100% is 0.4
- 100% is not "max chroma" for a given lightness and hue.

It's important to keep in mind that these are color notations, not actual colors.
After parsing and gamut mapping to display, the actual chroma will be much lower than 0.4 or 100%.

-------

As surfaced through experimentation in this thread some color notations work with percentages and numbers for `l` and other do not.

What isn't discussed in detail is why this is.

In previous iterations of the css-color-4 specification each color notation only allowed either percentages or numbers for specific channels.

- `rgb` only allowed all percentages or all numbers
- `hsl` only allowed all percentages or all numbers for `l` and `s`
- `lch` only allowed percentage `l` and `number` `c`
- ...

All these restrictions have been lifted and browsers are rolling out updates to match the latest syntax.

You can test this with : https://codepen.io/romainmenke/pen/wvNYKmR

Firefox Nightly for example has full support 🎉 

I'm in the process of adding this to mdn : https://github.com/mdn/browser-compat-data/issues/21404

-------

The motivation behind relaxing the syntax and for allowing both percentages and numbers in all channels (except hue), was that it shouldn't matter to CSS authors. They shouldn't have to think about which is correct or better. It should all just work.

I am not sure a rule for this should be added to Stylelint as neither percentages or numbers are better. Neither is more or less prone to issues.

If users want to enforce either for consistency then maybe a stylistic rule is a better fit?

**Comment by ybiquitous** [comment]
> If users want to enforce either for consistency then maybe a stylistic rule is a better fit?

This new rule aims to [enforce conventions](https://stylelint.io/user-guide/rules#enforce-conventions) rather than *a stylistic rule*. When saying *stylistic*, we usually consider the [deprecated stylistic rules](https://stylelint.io/migration-guide/to-15/#deprecated-stylistic-rules) supported by pretty printers.
