### ISSUE TITLE
--config doesn't work unless you start the file with `./`

### ISSUE THREAD

**Issue by jonathanong** [stylelint/stylelint#741]
seems to be `resolve-from`. was wondering what broke my test script, seems like it broke only when i don't prefix the file path with `./`

**Comment by davidtheclark** [comment]
Thanks for tracking this down @jonathanong. I did not anticipate this side-effect of https://github.com/stylelint/stylelint/issues/679. 

We can of course add documentation explaining this. Something like "Because you can pass npm packages by name, you'll need to prefix relative paths with `./`"

Technically, though, that means the change was breaking. It broke the test script. @jonathanong , @jeddy3 : Do you think we can get by just documenting this and considering the previous behavior a bug, or do we need new release?

**Comment by jonathanong** [comment]
I don't mind either solution. My biggest question is, "why do we even need resolve-from?" Doesn't seem like it adds any benefits except if you reference a folder or something, which I don't think you should be doing (the config file should always be a file)

**Comment by jonathanong** [comment]
O I c it's for external modules... Hmmm

**Comment by jonathanong** [comment]
Maybe just try with`./` prefix if the first try failed?

**Comment by davidtheclark** [comment]
@jonathanong Yeah, that's a solution that would keep the old behavior. Probably the best idea.

**Comment by jeddy3** [comment]
> Yeah, that's a solution that would keep the old behavior

Sgtm.
