### ISSUE TITLE
Deprecate GitHub formatter

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7447]
### What is the problem you're trying to solve?

Ref: https://github.com/stylelint/stylelint/issues/7430#issuecomment-1872329954

### What solution would you like to see?

Deprecate the GitHub formatter and remove it in the next major release.

Ideally, we'd link to a newly published GitHub custom formatter as part of the deprecation changelog entry.

**Comment by JounQin** [comment]
Deprecate it in a minor version and remove it in a major version?

**Comment by jeddy3** [comment]
Yes, that's correct. There'll be a separate issue for removing it. And we won't work on that one until we start on `17.0.0` further down the line.

**Comment by Mouvedia** [comment]
If we remove it and provide a package in the documentation, I'd support the deprecation/removal.

IMHO it should be accompanied by the integration of a JUnit formatter; probably based on [stylelint-junit-formatter](https://www.npmjs.com/package/stylelint-junit-formatter).  
The reason being that it's used by Circle CI and Bitbucket and Bamboo.
i.e. it's a de facto common format which addition is warranted

**Comment by ybiquitous** [comment]
When I looked for candidates, I found 2 packages:

- [`stylelint-formatter-github`](https://www.npmjs.com/package/stylelint-formatter-github)
  - Most popular, presented in Awesome Stylelint, but inactive
- [`stylelint-actions-formatters`](https://www.npmjs.com/package/stylelint-actions-formatters)
  - Active, considering the newer API (problem matcher)

So I'll contact an author of `stylelint-actions-formatters`.

**Comment by ybiquitous** [comment]
I just added `stylelint-actions-formatters` in https://github.com/stylelint/awesome-stylelint/pull/70

**Comment by ybiquitous** [comment]
> So I'll contact an author of `stylelint-actions-formatters`.

Done: https://github.com/xt0rted/stylelint-actions-formatters/issues/187

**Comment by ybiquitous** [comment]
Since I found an alternative package, I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

`process.emitWarning()` like #7550 will output a deprecation warning if `--formatter=github` or `stylelint.lint({ formatter: 'github' })` is used.

After this warning is released in a minor version (e.g. 16.x.y), let's remove the formatter in the next major version (17.0.0).

**Comment by romainmenke** [comment]
I am reopening this because I found that the current deprecation warning doesn't actually draw any attention to itself.

Setting `--formatter github` is something that you only do for lint runs with GitHub Actions.
But I don't think anyone looks at logs for GitHub workflow runs as long as CI is green.
So I don't think anyone will notice this.

-----

Maybe we can emit the deprecation itself as an annotation?

**Comment by Mouvedia** [comment]
> Can we achieve this easily?

> [`::warning file={name},line={line},endLine={endLine},title={title}::{message}`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-a-warning-message)
