### ISSUE TITLE
Fix `selector-max-specificity` README examples of the `ignoreSelectors` secondary option

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7495]
see : https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/lib/rules/selector-max-specificity/__tests__/index.mjs#L451

These tests are problematic for multiple reasons:
- `:global` and `:local` are non-standard and it isn't defined what their specificity is.
- `:global` and `:local` don't have any specificity of their own in `@csstools/selector-specificity`, so ignoring them to reduce their specificity seems weird?
- `:global` and `:local` do not support selector lists in implementations
  - `lightningcss` errors
  - `postcss-modules` mangles the output (`:global(.page, .bar)` -> `.page .bar`)

They also dominate the implementation of `selector-max-specificity`.

As far as I can tell the `ignoreSelectors` was also created with css modules too much in mind.
It acts like a hole punch. The AST node that matches doesn't contribute to specificity, but its child nodes do. Which works really well for `:global` and `:local` because they happen to be removed during compilation.

But I am not sure if this makes sense for any case other than css modules.
There isn't any test coverage for other pseudo selectors with child nodes, so I can't tell what the exact intention was here.

--------------

Proposal :
- fix the tests so that `:global` and `:local` are used as supported by implementations
- better define how `ignoreSelectors` works when it matches AST nodes with child nodes

**Comment by ybiquitous** [comment]
@romainmenke Thanks for the report. `ignoreSelectors` seemed to be added by PR #2874, quite a while ago (2017)! I'm honestly unsure about the background, but it seems a good opportunity to reconsider CSS Modules selectors (e.g. `:global`). 👍🏼 

In addition, thanks for trying `@csstools/selector-resolve-nested` with PR #7496!

**Comment by romainmenke** [comment]
Regressions or CSS modules compat are not really my primary concern here :)

CSS modules are supported in `@csstools/selector-specificity` so there is nothing that needs to happen for that in Stylelint when calculating specificity.

But the test however write CSS for CSS modules that isn't correct.
This is just bogus : 

```css
:global(.page, .bar)
:global(.page, :local(.bar))
```

Because these are bogus we can safely assume that no user will be writing this and that changes won't cause regressions.

--------------------

At the same time these test are the only coverage we have for `ignoreSelectors` in combination with functional pseudo classes.

There is no coverage with standard functional pseudo classes and `ignoreSelectors`.

I don't know what the calculated specificity should be for these :

- `ignoreSelectors` -> `:is`

```css
.foo :is(#bar, input) {} // [1, 1, 0] without ignore
```

Is that :
- `[0, 1, 0]` -> `:is` and all children are ignored
- `[1, 1, 0]` -> only `:is` is ignored, but not its children

`:is` already doesn't have any specificity of its own, it is as specific as its most specific argument.

The same is true for `:not`, `:has`, ...

- is there a use case for ignoring only a functional pseudo class but not its children?
- how do other ignore flags work? do they ignore the entire AST subtree?

---------------

This is different from non-functional pseudo classes.

```css
.foo :focus {} // [0, 2, 0] without ignore
```

Ignoring `:focus` does meaningfully affect specificity -> `[0, 1, 0]`

**Comment by ybiquitous** [comment]
Probably, I guess the following behavior would be correct: ⬇️ 

---

Given:

```json
{"ignoreSelectors": [":global"]}
```

Then:

```css
:global {} /* ignored */
:global(.foo) {} /* not ignored */
```

---

Given:

```json
{"ignoreSelectors": ["/:global\(.+\)/"]}
```

Then:

```css
:global {} /* not ignored */
:global(.foo) {} /* ignored */
```

**Comment by romainmenke** [comment]
Would it be ok to remove the bogus tests and to replace them with tests for standard functional pseudo classes?

Then at least there is coverage for the current implementation in a way that makes it clear what the expectations are.

**Comment by Mouvedia** [comment]
> At the same time these test are the only coverage we have for `ignoreSelectors` in combination with functional pseudo classes.

If I had to guess it was to cover a real use case; this seems reasonable to me.

> better define how `ignoreSelectors` works when it matches AST nodes with child nodes

If that's a documentation update please check #4105 as well.

> `:global` and `:local` do not support selector lists in implementations
> […]
> fix the tests so that `:global` and `:local` are used as supported by implementations

If true, 👍

**Comment by jeddy3** [comment]
Our end goal is to modernise and make our behaviour around specificity and nesting spec-compliant, which will benefit the majority of our users.

As such, I think we can remove barriers that'll hamper us in achieving this for our next major release, including removing options that may no longer be relevant. 

I suggest we remove the `ignoreSelectors` option (and related tests) as part of https://github.com/stylelint/stylelint/pull/7496. It may well be that everyone's use case is covered by:

> `:global` and `:local` don't have any specificity of their own in `@csstools/selector-specificity`

If not, a person can open a new issue with their use case, and we'll decide on the most modern way to cater to it.

 > how do other ignore flags work? do they ignore the entire AST subtree?

We've typically avoided broad ignore options like `ignoreSelectors` because of these types of problems. We've had better success with more focused ignore options like:

- [`ignorePseudoClasses`](https://stylelint.io/user-guide/rules/max-nesting-depth/#ignorepseudoclasses-regex-regex-string)
- [`ignoreContextFunctionalPseudoClasses`](https://stylelint.io/user-guide/rules/selector-max-id/#ignorecontextfunctionalpseudoclasses-regex-regex-non-regex)

We can reach for similar options to cater to specific use cases.

**Comment by ybiquitous** [comment]
I agree with replacing `ignoreSelectors` with more specific options. 👍🏼

Perhaps, I assume that CSS Modules selectors like `:global` or `:local` might be used in most use cases of `ignoreSelectors`. As we can regard them as *functional pseudo classes*, providing `ignoreFunctionalPseudoClasses` instead of `ignoreSelectors` makes sense to me in order to keep compatibility as much as possible.

E.g.

```json
{
  "selector-max-specificity": ["0,2,0", {"ignoreFunctionalPseudoClasses": [":global", ":local"]}]
}
```

```css
.foo .bar.baz {} /* '0,3,0' => reported */

:global(.foo) .bar.baz {} /* '0,2,0' => not reported */
```

So, I suggest the following steps:

1. Deprecate `ignoreSelectors` with the next *minor* version (16.x.0)
2. Add `ignoreFunctionalPseudoClasses` with the next *minor* version (16.x.0)
3. Remove `ignoreSelectors` with the next *major* version (17.0.0)

**Comment by Mouvedia** [comment]
> So, I suggest the following steps:
> 
> 1. Deprecate `ignoreSelectors` with the next _minor_ version (16.x.0)
> 2. Add `ignoreFunctionalPseudoClasses` with the next _minor_ version (16.x.0)
> 3. Remove `ignoreSelectors` with the next _major_ version (17.0.0)

Sounds reasonable.

In the meantime

> fix the tests so that :global and :local are used as supported by implementations

shouldn't hinder that plan.
@romainmenke Either emend, remove or replace the 6 tests that are affected; we can discuss the details in the PR.

<hr />

The documentation update could be skipped since we are planning to replace it.

**Comment by romainmenke** [comment]
I've opened https://github.com/stylelint/stylelint/pull/7688 to fix this specific issue.

I am aware that this is still labeled as `needs discussion` but I am hoping that showing the actual change illustrates the issue better and that we can move forward with this.

If this is not a change we want to make at this time, then that is fine aswel :)

--------------

Deprecating `ignoreSelectors` and adding `ignoreFunctionalPseudoClasses` can be separate issues?

**Comment by Mouvedia** [comment]
> Deprecating `ignoreSelectors` and adding `ignoreFunctionalPseudoClasses` can be separate issues?

If you fill them/it remember to add a task to #7396.

> I am aware that this is still labeled as `needs discussion`…

Is this the only rule affected?
`no-descending-specificity` has one test that uses `:global()`.

**Comment by Mouvedia** [comment]
Ill repurpose this ticket so that it can be accepted.
i.e. updating the tests is just a simple refactor and doesn't require a changeset
