### ISSUE TITLE
Add a severity secondary option

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#776]
Ref: https://github.com/stylelint/stylelint/pull/772#issuecomment-186474112

- [x] Add a `severity` secondary option and make a new `advice` level available via that.
- [x] Add a deprecation notice when warn is used telling people it will be phased out at the next major version.
- [x] Update the docs accordingly.

**Comment by davidtheclark** [comment]
@ngavalas: Are you going to have time to address this? If not, I can probably get to it this week. But I didn't want to step on your toes if you've already started.

**Comment by davidtheclark** [comment]
@ngavalas: With the new `severity` option it should be super easy and clean to add `advice` as a possibility.

**Comment by ngavalas** [comment]
Hey, I just saw this, sorry!  I did a bit of work on this over the weekend but then I had a flight (working from a different office this week for a conference) and haven't had any time to look at it since.  

Saw that you merged in that commit to add `severity`, it looks great!  Totally what we were looking for, thanks for getting to it; I appreciate it.
