### ISSUE TITLE
Add stylelint-config-adblock as a native stylelint rule

### ISSUE THREAD

**Issue by royhadad** [stylelint/stylelint#7810]
### What is the problem you're trying to solve?

I have a bug in production where certain elements are being hidden via adblockers due to their class name (e.g. "ad" "advertiser")
After a bunch of digging, I found [this stylelint config](https://github.com/wuhonglei/stylelint-config-adblock) that configures 1 rule, to detect the forbidden class names.

### What solution would you like to see?

Adding this rule as a built in rule

**Comment by ybiquitous** [comment]
@royhadad Thanks for the proposal. But, this proposal is against our built-in rule policy because supporting adblockers is not common:

> generally useful; not tied to idiosyncratic patterns 

https://github.com/stylelint/stylelint/blob/b5b7ebd75cef48941000d0ec47b587eb32cf916e/docs/developer-guide/rules.md?plain=1#L11-L14

Please consider introducing the config to [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint) to share if you're interested.
