### ISSUE TITLE
Use `emitDeprecationWarning` for rule deprecations

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7845]
### Request

https://github.com/stylelint/stylelint/pull/6561#discussion_r1678660168

### Reasons

1. for consistency
2. `--no-deprecation` should suppress _all_ deprecation warnings

### Do you have a proposal to fix the bug?

- update
https://github.com/stylelint/stylelint/blob/1ba1a0aeafaa124a4987a0135d511111cec3af0a/lib/lintPostcssResult.mjs#L138-L140
- add a new code to
https://github.com/stylelint/stylelint/blob/1ba1a0aeafaa124a4987a0135d511111cec3af0a/lib/utils/emitDeprecationWarning.mjs#L4-L8

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for opening the issue. If we switched to `emitDeprecationWarning`, would this be a breaking change? If not, we could ship this change in the next *minor* release.

**Comment by Mouvedia** [comment]
I don't know but if we had priority labels this would be _very low_ because we already have the `--quiet-deprecation-warnings` flag.
i.e. not respecting `--no-deprecation` is not a big deal if we have an alternative

**Comment by ybiquitous** [comment]
We have already had the [`--quiet-deprecation-warnings`](https://github.com/stylelint/stylelint/blob/1ba1a0aeafaa124a4987a0135d511111cec3af0a/docs/user-guide/options.md#quietdeprecationwarnings) flag/option, so this isn't a big deal.

If we were more careful, this should be shipped in the next *major* version because the reporting way for deprecated rules would change. See also our [versioning policy](https://github.com/stylelint/stylelint/blob/1ba1a0aeafaa124a4987a0135d511111cec3af0a/docs/about/semantic-versioning.md).

**Comment by Mouvedia** [comment]
> If we were more careful, this should be shipped in the next _major_ version because the reporting way for deprecated rules would change. See also our [versioning policy](https://github.com/stylelint/stylelint/blob/1ba1a0aeafaa124a4987a0135d511111cec3af0a/docs/about/semantic-versioning.md).

@ybiquitous `deprecated` rules are pretty rare outside of stylelint/stylelint, which has none currently.
The only one I could find is [`stylelint-scss/at-import-partial-extension`](https://github.com/stylelint-scss/stylelint-scss/blob/a689b55e41a4c582377f2b291236757e4594b429/src/rules/at-import-partial-extension/index.js#L18).
IMHO it could be done before the next major.
It's just a matter of consistency and it becomes essential if we accept stylelint-ecosystem-tester#38
