### ISSUE TITLE
New rule to enforce `@scope` usage

### ISSUE THREAD

**Issue by mrredtree** [stylelint/stylelint#7852]
### What is the problem you're trying to solve?

The `@scope` syntax of CSS is now available in browsers. From now on, the CSS architecture can be written without conventions like BEM, so...

### What solution would you like to see?

... I make the suggest for the Stylelint team to create a rule to enforce the usage of `@scope` instead of letting users to name selectors without it.

Reference: https://blog.logrocket.com/css-scope-replace-bem/

Thanks.

**Comment by Mouvedia** [comment]
Detecting specific class naming conventions to recommend `@scope` instead sounds like a job for a plugin to me.
Do you have an example where `@scope` would be recommended which wouldn't involve an existing convention?
i.e. what would be the name of the rule you are proposing?

**Comment by Mouvedia** [comment]
> selector-naming-pattern (inspired by selector-id-pattern)

You can already detect BEM naming conventions using `selector-class-pattern`.

**Comment by Mouvedia** [comment]
I think a potential rule would be akin to [`at-rule-property-required-list`](https://stylelint.io/user-guide/rules/at-rule-property-required-list).
i.e. `at-scope-class-required-list` which would warn when a class is used without being scoped

**Comment by Mouvedia** [comment]
@mrredtree Both comments were marked as off-topic from the start. I also excused myself before asking.
With the advent of chatgpt, it's hard to discern between humans and bot nowadays.

**Comment by ybiquitous** [comment]
I also agree with implementing such a rule as a *plugin* because this pattern for `@scope` doesn't seem to be applied to our criteria:

> generally useful; not tied to idiosyncratic patterns

-- https://stylelint.io/developer-guide/rules#define-the-rule

Please refer to our [document about writing plugins](https://stylelint.io/developer-guide/plugins) and share your plugin here or [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint) if it's published.
