### ISSUE TITLE
Write more documentation for post processor

### ISSUE THREAD

**Issue by ghost** [stylelint/stylelint#7853]
Edit: suggestions were discarded by Stylelint team, so they were erased.

**Comment by Mouvedia** [comment]
In the meantime check https://github.com/search?q=repo%3Astylelint%2Fstylelint%20lib%2F__tests__%2Ffixtures%2Fpostprocess-&type=code

**Comment by ybiquitous** [comment]
Hi @mrredtree, this document describes the processors. Can you take a look?
https://stylelint.io/user-guide/configure/#processors

If you think it's enough, please close the issue.

**Comment by ybiquitous** [comment]
@mrredtree I understand your motivation, but I don't think we need to describe the code details in this document because it would increase our maintenance work to sync the code with the doc.

It's probably easier to use TypeScript to understand this API and the example. TypeScript should help you use the Processor API. We have the type below:
https://github.com/stylelint/stylelint/blob/67c21375e12f695a3929bde27281d772dcdeaf93/types/stylelint/index.d.ts#L204-L210

Of course, if you are interested, you can open a pull request to improve the document. Please consider [contributing](https://stylelint.io/contributing) if you have time.
