### ISSUE TITLE
Is `color-function-notation` allowing a broken syntax?

### ISSUE THREAD

**Issue by astorije** [stylelint/stylelint#7927]
### What minimal example or steps are needed to reproduce the bug?

Given the following CSS:

```css
  box-shadow:
    0 0 5px 0 rgba(34 37 47 10%),
    0 10px 10px 0 rgba(34 37 47 10%);
```

### What minimal configuration is needed to reproduce the bug?

Simply extending `"stylelint-config-standard"`

### How did you run Stylelint?

```
stylelint "**/*.css"
```

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.6.1",
  "stylelint-config-standard": "36.0.0"
}
```

### What did you expect to happen?

I would expect Stylelint to raise this as an issue in favor of the syntax that includes a `/`:

```css
  box-shadow:
    0 0 5px 0 rgba(34 37 47 / 10%),
    0 10px 10px 0 rgba(34 37 47 / 10%);
```
<img width="289" alt="Screenshot 2024-08-12 at 13 33 44" src="https://github.com/user-attachments/assets/1b4f6ecd-3bad-4921-8e23-6e8753cb21a0">

### What actually happened?

Instead Stylelint was perfectly happy with it, but Chrome (v126.0.6478.127) is not:

<img width="313" alt="Screenshot 2024-08-12 at 13 34 47" src="https://github.com/user-attachments/assets/35ec657f-7217-4604-ba2e-5ea6cfa6904a">

**Comment by romainmenke** [comment]
@astorije Thank you for the report.

I don't think this rule is intended to validate color syntax.
It enforces either comma separated or space separated syntax for consistency in a single codebase.

There is however a different rule that can validate color syntax: [`declaration-property-value-no-unknown`](https://stylelint.io/user-guide/rules/declaration-property-value-no-unknown/)

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgIwgA8BaAZwAskoIB3eLXXABhRYFYAHQ1lAJwHM8SABQBmACwpRAdhTjZARiYBSAJQAaBjmYolXXU30sBQsZJlzFK1QG4sAXwaY8aLQRIUqtetm04W7EZ8giISUrLyKAD0Bmqavjp63Ek8JqHmEbIxSmp2mI6YIOogAGYAlgA2MABySAC2cIgwhPUcVQB0YKSkReAQmOX8CCAYmCgo6CDNODCYUKST8CgA2ljj45OkOACeVRVlmDjEkANl-GQ4SHNIvFCTaygAuvEbILwArlULCK5j65OwMAVG5IHBlfrEDi8CAcGC8HbEABuSAq7xgxEwEGI70wAGtMTRsD9ljgPjBHg8CvZeidBgAxCC8Oqg4YAK1I-V6sA4PUQo1eW12MH2h0WExAwJmW0mL3Fgr2ByOtLOFyuUBudx+k0lMGlIAcIHsQA)

**Comment by astorije** [comment]
Hi @romainmenke, thank you for the quick response!
Mmh interesting. Shouldn't this be enabled in the `standard` config then? It seems to me that it could easily prevent bugs, and I think it's even more so warranted in the config since `color-function-notation` is enabled in `standard`.

**Comment by romainmenke** [comment]
As far as I know there are two reasons why `declaration-property-value-no-unknown` hasn't been added to a shared config yet.

This rule uses `csstree` to do syntax checking and `csstree` isn't that actively maintained.
Each newly added CSS feature appears to be invalid until `csstree` is updated.

Our implementation of this rule might not be fully mature yet. Given that it possibly warns on every value we want to make sure that there aren't too many false positives.

**Comment by astorije** [comment]
That makes a lot of sense, thank you @romainmenke!
In the meantime, would it be a good idea to update `color-function-notation` so it detects a missing `/`? I realize it's not the ideal, generic solution, but that would have saved us a bug without having to rely on a rule that potentially has false positives 😅

**Comment by romainmenke** [comment]
From our docs:

https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/rules.md#define-the-rule

> ### Define the rule
> 
> A rule must be:
> - for standard CSS syntax only
> - generally useful; not tied to idiosyncratic patterns
> 
> And have a:
> - unambiguous finished state
> - **singular purpose that doesn't overlap with other rules**

The singular purpose of `color-function-notation` is to either enforce space separated or comma separated, not check the validity of either.

Expanding the scope of `color-function-notation` would give it a dual purpose.

I think that it would be better if we can improve `declaration-property-value-no-unknown` :)

**Comment by Mouvedia** [comment]
We will eventually have to track all the csstree issues somehow.
Right now the label _upstream_ is not sufficient because it doesn't account the PRs that have been opened on their side but were never merged.

I am dubious that the rule will ever be at a stage where its addition to `stylelint-standard-config` will be warranted.
It would require someone from the CSS WG to monitor it so that it's always updated.
i.e. so that we are always ahead of the inevitable false positives

**Comment by romainmenke** [comment]
> It would require someone from the CSS WG to monitor it so that it's always updated

Several people from the CSSWG (myself included) are working on this.
Having machine readable data about the CSS language is important for many tools (e.g. editors, docs, linters, ...)

The people working on [`@webref/css`](https://www.npmjs.com/package/@webref/css?activeTab=readme) are also actively trying to get `css-tree` to switch over to it.

The current blocker is more the lack of active maintenance on `css-tree`.
Which, unfortunately, is outside of the control of Stylelint and the CSSWG.
However, this is open source and forks can be created 😛

All of this is indeed slow moving because everyone always has too little time and too many projects :)

**Comment by Mouvedia** [comment]
> However, this is open source and forks can be created 😛

@romainmenke https://github.com/stylelint/stylelint/pull/6511#issuecomment-1597837797
