### ISSUE TITLE
declaration-block-no-redundant-longhand-properties --fix breaks nested Sass properties

### ISSUE THREAD

**Issue by Baedda** [stylelint/stylelint#7931]
### What minimal example or steps are needed to reproduce the bug?

```
.test {
    padding: {
        top: 10px;
        right: 10px;
        bottom: 10px;
        left: 10px;
    }
}
```

### What minimal configuration is needed to reproduce the bug?

{
    extends: 'stylelint-config-standard-scss'
}

### How did you run Stylelint?

stylelint src/styles/** --fix

### Which Stylelint-related dependencies are you using?

{
    "stylelint-config-standard-scss": "^13.1.0"
}

### What did you expect to happen?

Either

```
.test {
    padding: {
        block: 10px;
        inline 10px;
    }
}
```

or

```
.test {
    padding:10px;
}
```

or nothing.

### What actually happened?

.test {
    padding: {
        inset: 10px 10px 10px 10px;
    }
}

What becomes .test { `padding-inset` } in CSS, what is an invalid property.

### Do you have a proposal to fix the bug?

At the moment my only idea would be to exclude `margin`/`padding `from the rule using `ignoreShorthands`.

**Comment by ybiquitous** [comment]
@Baedda Thanks for the report. We can see the behavior in the following demo:

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AXGBnFACYAdAdrigA4CGUUAlvgObw4FFEoTH0CMADMQB4DcjFEQBOlGgAsUHbv0FEARhBQsAttN4DCQlABsYAMylYuGwQF9GWlm2MzNIsZPWyti5RDW3TWvYeeazEAAaEH1KPQA5UhU4RBgeaOI9JHQwdHRg8Ah8MJoEEDx8LCxcEHi0fCh0UvoAbQJi4tLMAE89HWoUAFpIHLEuzFJK0mEoAbTqkAasAF0CQJDe3IAxCGEVUhR8gCt0bMzYYgzEQqaQVvbOmpKQHU2MIWDp5pQ2mA78bqX+weHR8fS11KdzQmFK8xAZiAA)

```scss
.test {
	padding: {
		top: 10px;
		right: 10px;
		bottom: 10px;
		left: 10px;
/* =>
		inset: 10px;
*/
	}

	top: 10px;
	right: 10px;
	bottom: 10px;
	left: 10px;
/* =>
	inset: 10px;
*/
}
```

As you see in the demo code above, unfortunately, this behavior is expected because the Stylelint built-in rules support only the standard CSS and don't support non-standard CSS syntaxes like Sass. This code uses Sass's [Nesting Property Declarations](https://sass-lang.com/documentation/style-rules/declarations/#nesting) which is unsupported.

There are a few options to work around:
- Use the `ignoreShorthands` secondary option as you described above.
- Ignore reported lint problems via `/* stylelint-disable */` comments.
- Propsoe to add a new rule to [stylelint-scss](https://github.com/stylelint-scss/stylelint-scss). The rule would extend the built-in rule `declaration-block-no-redundant-longhand-properties` like `scss/at-rule-no-unknown`.

**Comment by Baedda** [comment]
@ybiquitous thanks for the explanation. I didnt notice that s`tylelint-config-standard-scss` is from a different maintainer, because it was mentioned in the official Stylelint documentation. Thats why I created this issue here. I will add a proposal in the right repository then
