### ISSUE TITLE
Better grunt support

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#858]
On Twitter I'm seeing a lot of comments recently about people struggling to use stylelint with grunt. (A bunch of them are in German so I don't really understand!) I myself haven't a actually explored existing grunt plugins much (just started poking into the existing gulp plugin); but it looks like whatever *does* exist needs to be improved and clarified, or else something else needs to be built.

Just opening this issue to see if people have opinions, ideas, etc., and if anybody wants to do further exploration and development.

**Comment by ntwb** [comment]
I _can_ do this, I'm using Grunt with WordPress, I'll take a look at some of those tweets this afternoon and see what I can do.

**Comment by trilodge** [comment]
Got it running together with grunt-sass and postcss + postcss-scss and postcss-autoprefixer and so on. Preparing a gist at the moment for that. However i got some issues with some rules which are throwing "undefined rule" or similar errors. E.g. https://github.com/stylelint/stylelint/blob/master/src/rules/block-no-single-line/README.md

**Comment by ntwb** [comment]
@trilodge Drop a link to your Gist and I'll happily take a look

I think your issue with the `block-no-single-line` rule will be because this is the stylelint 4.5 rule name, this rule was previously `declaration-block-no-single-line` in stylelint 4.4 which is the current shipped version and is being deprecated in favour of that new name to ship in the next release of stylelint.

**Comment by trilodge** [comment]
ah okay. than it's a lil confusing if u start with https://github.com/stylelint/stylelint/blob/master/docs/user-guide/example-config.md for the configuration. because all the new stuff is stated there.

**Comment by trilodge** [comment]
@ntwb have a look at: https://gist.github.com/trilodge/97e657309cb24977efbc

**Comment by jeddy3** [comment]
> ah okay. than it's a lil confusing if u start with https://github.com/stylelint/stylelint/blob/master/docs/user-guide/example-config.md for the configuration. because all the new stuff is stated there.

Sorry about that. I could see how it would be confusing.

We've just released `4.5.0` and so everything should be aligned now.

**Comment by trilodge** [comment]
@jeddy3 ... yup. works like a charm. updated my gist as well to the latest 4.5.0 release and updated the .stylelintrc with the new rules.

**Comment by davidtheclark** [comment]
@ntwb , @trilodge : I think there would probably be benefit in having a `grunt-stylelint` module that we promote, just like we've been talking about `gulp-stylelint`. The reason is primarily for reporting that is consistent with the CLI and takes advantage of stylelint-specific features, rather than having to run through postcss-reporter. Also it might be easier for some people to wrap their heads around. Do you think that might be worthwhile?

**Comment by trilodge** [comment]
@davidtheclark I think it would be better if there will be a `grunt-stylelint`, it's quite cumbersome to gather all the infos from all the pages and stuff.

**Comment by jeddy3** [comment]
> The reason is primarily for reporting that is consistent with the CLI and takes advantage of stylelint-specific features... Do you think that might be worthwhile?

It feels like there are a few connected issues swirling around:

- Changes to `postcss-reporter`: https://github.com/postcss/postcss-reporter/pull/23#issuecomment-195642137 & https://github.com/stylelint/stylelint/issues/843
- logOutput option for the PostCSS Plugin: https://github.com/stylelint/stylelint/issues/792
- Managing deprecations when `postcss-reporter` is used with `throwError: true`: https://github.com/stylelint/stylelint/issues/869
- Advocating `gulp-stylelint`: https://github.com/stylelint/stylelint/issues/846
- Syntax errors log to console as text when JSON reporter is used: https://github.com/stylelint/stylelint/issues/883

I'll have to admit I haven't got a firm grasp on what our plan is. 

How does `stylelint` being a PostCSS plugin fit in with the emergence of `gulp-stylelint`?

**Comment by davidtheclark** [comment]
Here's my thinking right now -- I think the issues you mention can be split up like this:
- Next time we make deprecations we try using regular PostCSS messages instead of warnings, hoping that doesn't break the build of people using stylelint within a PostCSS plugin chain.
- Experiment with catching syntax errors and handling them specially.
- See what we can do to improve gulp-stylelint, grunt-stylelint, and whatever-else-stylelint so that those can be used (in place of gulp-postcss, grunt-postcss, etc.) and then gulp/grunt/whatever users can get the best stylelint-specific reporting that we can manage.

So the idea is that once gulp/grunt/whatever plugins are good enough to be recommended, stylelint *can* still be used as a postcss plugin but with a caveat: it has to be reported just like any other postcss plugin, which means that nothing stylelint-specific can happen. Most people would want special stylelint-specific reporting, so would be better off using the *-stylelint plugins.

**Oh but I just thought of another idea while typing**: What if we make a new PostCSS plugin: stylelint-reporter? It's like postcss-reporter but filters messages to get only those applicable to stylelint, and handles all of stylelint's special stuff, like deprecations, invalid options, severities. Then we'd say that  people should use *that* after the PostCSS plugin stylelint in their plugin chain, instead postcss-reporter ---- then we wouldn't have to worry much about the gulp/grunt plugins that we don't maintain. Thoughts? I think I'm liking that idea ...

**Comment by jeddy3** [comment]
> What if we make a new PostCSS plugin: stylelint-reporter?

Ooo, that's a really nice idea. I think that's the best solution as, as you said, we needn't worry much about the runners we don't maintain. It also means we can continue to piggy back on the PostCSS's healthy community, including [their *13* runners](https://github.com/postcss/postcss#runners).

Shall we call it `postcss-stylelint-reporter` to be inline with the PostCSS plugin guidelines?

> Then we'd say that people should use that after the PostCSS plugin stylelint in their plugin chain, instead postcss-reporter

Am I right in thinking that a user would also be able to use `postcss-stylelint-reporter` *as well as* (rather than *instead of*) other reporters like `postcss-reporter` and `postcss-browser-reporter`?  Similar to `postcss-reporter`, `postcss-stylelint-reporter` would have a `clearStylelintMessages` option which clear the stylelint messages. This would allow a user (by *not* using this option) to use both `postcss-stylelint-reporter` and `postcss-browser-reporter`, similar to how Maxime [is doing over in statinamic]
(https://github.com/MoOx/statinamic/blob/next/boilerplate/scripts/webpack.config.babel.js#L59) with `postcss-loader`.

Would `postcss-stylelint-reporter` handle severities correctly? So that there wouldn't be a need for a `throwError` option (as in `postcss-reporter`), as errors are thrown by default (whereas things like `warning` and `advice` aren't)?

The more I think this through the more I think your idea is spot on. Fingers crossed!

**Comment by davidtheclark** [comment]
Yeah, I think this will be the solution to all our problems and answer to all our prayers. But I'm doing taxes, so not going to start on it today :(

**Comment by davidtheclark** [comment]
That said, @jeddy3 or anyone else, if you feel like making a repo and starting in on this, go for it!

**Comment by jeddy3** [comment]
> But I'm doing taxes

That's never fun! I did mine recently too.

I'm unlikely to find time this weekend, but if anyone else fancies starting it then look to the existing [`stringFormatter`](https://github.com/stylelint/stylelint/blob/master/src/formatters/stringFormatter.js) for a good place to start.

**Comment by davidtheclark** [comment]
Closed in favor of #917.
